### ISSUE TITLE
glTF next: KHR_texture_coordinate glTF Next specification 

### ISSUE THREAD

**Issue by UX3D-nopper** [KhronosGroup/glTF#1044]
As discussed here, a high demand for a texture coordinate modifier is needed e.g. applying a texture matrix:
https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/35#issuecomment-316397046

**Comment by stevenvergenz** [comment]
Related proposed extension: #1015

**Comment by steveghee** [comment]
could perhaps be defined as a property of the material that is applied to that texture channel?

**Comment by McNopper** [comment]
WIth a quick thought, I would apply it to a mesh and not the material.
E.g. u want to use the same material on two objects, but u need to scale it for one object:
The material can be reused, using this approach.

**Comment by steveghee** [comment]
quite the opposite; I want o apply multiple materials to a mesh; I have my wooden box with a sticker (decal) applied; the wood is one material - potentially multiple textures (PBR) with 1 set of transforms etc.  My sticker/decal is another material - very probably different specular reflectivity etc, and would be positioned perhaps differently on the mesh. of course I might just burn this into the texture_1 cords when I publish the model, but I might also want it to by moveable, so the transform could be dynamic.  Hence the transform really applies to how the material is mapped to the mesh, and not to the mesh itself.

**Comment by stevenvergenz** [comment]
Normally if you wanted to apply multiple materials to a mesh, you would need to break the mesh into multiple primitives, each with a material. Either that, or use a spec map/etc. to make that region distinct. But since ultimately you want its location to be dynamic, and glTF doesn't support animating material properties, what you'll probably need to do is write a custom shader that can layer multiple textures of multiple types (base color, specular, normal, etc.) onto an object. Each layer would probably need offset/rotation/scale taken into account too. And you'll need to be real careful about how your UVs are laid out.

In any case, the only way glTF is going to support this out of the box is a separate decal primitive that floats in front of your actual mesh. It's not ideal, and has a lot of problems, but it's as close as you can get without a lot of work.

**Comment by steveghee** [comment]
handling co-located decal meshes etc. is a lot more work than writing a custom shader!    As you say, in practice, most glTF data will be static output (not animated) so the info could be baked into diffuse and spec maps etc.

**Comment by donmccurdy** [comment]
Closing this issue out, to direct feedback to https://github.com/KhronosGroup/glTF/pull/1015
