### ISSUE TITLE
Support for primitive restart

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/glTF#1142]
For triangle strip/line strip primitive types, it would be useful to support primitive restart (with fixed index 2^n - 1).

**Comment by pjcozzi** [comment]
Thanks for the suggestion, @Themaister!  Will certainty be useful for graphics APIs beyond WebGL 1.

**Comment by lexaknyazev** [comment]
Apparently, we need to discuss this within glTF 2.0 lifecycle.

WebGL 2.0 behaves as if primitive restart is always on with fixed index (255, 65535, or 4294967295). [The rationale from the spec](https://www.khronos.org/registry/webgl/specs/latest/2.0/#NO_PRIMITIVE_RESTART_FIXED_INDEX):
> This compatibility difference was introduced in order to avoid performance pitfalls in Direct3D based WebGL implementations. Applications and content creation tools can be adjusted to avoid using the maximum vertex index if the primitive restart behavior is not desired.

This means that some engines would need to manually rebuild index buffer in some cases which goes against glTF's goal.

Action items:
- [ ] Add a note about this to the spec.
- [ ] Add a validation warning on index buffers containing restart values.

Optionally, depending on ecosystem status:
- [ ] Disallow primitive restart values in index buffer.

/cc @donmccurdy @bghgary @emackey

**Comment by lexaknyazev** [comment]
Same issue with Vulkan (although this feature can be disabled).
From `VkPipelineInputAssemblyStateCreateInfo`:
> `primitiveRestartEnable` controls whether a special vertex index value is treated as restarting the assembly of primitives. This enable only applies to indexed draws (`vkCmdDrawIndexed` and `vkCmdDrawIndexedIndirect`), and the special index value is either `0xFFFFFFFF` when the `indexType` parameter of `vkCmdBindIndexBuffer` is equal to `VK_INDEX_TYPE_UINT32`, or `0xFFFF` when `indexType` is equal to `VK_INDEX_TYPE_UINT16`. Primitive restart is not allowed for “list” topologies.

**Comment by lexaknyazev** [comment]
Actual implementation details are even more cumbersome. D3D11 may have different behavior with different GPUs or driver versions. More details:
https://bugs.chromium.org/p/angleproject/issues/detail?id=708
https://bugs.chromium.org/p/angleproject/issues/detail?id=2035

Metal also seems to have primitive restart always on with max values.

The solution seems to be to generate test models for each combination of primitive mode and index buffer datatype with primitive restart token in them. And to test all these models with engines running on different backends. After that, we should be able to make proper decision.

@bghgary Is it something that could be easily done with the asset generator?

**Comment by bghgary** [comment]
Sure. Can you file an issue?

**Comment by lexaknyazev** [comment]
Just for better context, 
**primitive restart** - is a feature of input assembly stage that restarts current primitive when vertex index value is the maximum possible value for a given index buffer type (e.g., 65535 for uint16).

API support looks like this:

| Mode | OGL ES 2 | OGL ES 3 | WebGL 1 | WebGL 2 | Vulkan | D3D11 | Metal |
|----------------|:----------:|:--------:|:-------:|:-------:|:--------:|:-----:|:------:|
| Point List | Off | On / Off | Off | On | Off | On | On (?) |
| Line List | Off | On / Off | Off | On | Off | On | On (?) |
| Triangle List | Off | On / Off | Off | On | Off | On | On (?) |
| Line Loop | Off | On / Off | Off | On | On / Off | N/A | N/A |
| Line Strip | Off | On / Off | Off | On | On / Off | On | On |
| Triangle Strip | Off | On / Off | Off | On | On / Off | On | On |
| Triangle Fan | Off | On / Off | Off | On | On / Off | N/A | N/A |

- **On** - primitive restart is always enabled.
- **Off** - primitive restart is always disabled.
- **On / Off** - primitive restart can be configured.
- **N/A** - API doesn't support given primitive mode.

Possible short-term actions:

### Declare that glTF 2.0 doesn't support primitive restart and all values in an index buffer (including primitive restart value) must refer to actual vertices.

This will work for the most cases, except:
A mesh containing _exactly_ 65535 vertices will be rendered incorrectly on WebGL 2, D3D11, and Metal unless an engine checks for this case and fix the index buffer by rewriting it to uint32 thus taking more GPU memory. The second solution is to split the mesh (topology-aware) and use more than one draw call.
#### Curious case of UINT8 index buffer
Since Metal and D3D11 do not support uint8 index buffer (so engines are already rewriting it to uint16), only WebGL 2 engines will produce incorrect result for meshes of 255 vertices.

### Declare that glTF 2.0 doesn't support primitive restart and all values in an index buffer must refer to actual vertices. Disallow primitive restart values.

Exporters must be updated, but engines are fine as they are now. There's a chance that there are models (with meshes made of exactly 255 or 65535 vertices) violating this rule, however their rendering is inconsistent anyway.

**Comment by emackey** [comment]
I'm in favor of your comment here: https://github.com/KhronosGroup/glTF-Blender-IO/pull/56#issuecomment-432518390 saying that we should just decrease the UINT16 cutoff to avoid this issue.  The same change should be made to https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/329 as well, if we do this.

**Comment by lexaknyazev** [comment]
This would require adding a note to the spec (and a new validation issue).

**Comment by emackey** [comment]
Sounds good to me.  It seems the glTF 2.0 ecosystem still depends heavily on older APIs that don't offer primitive restart.  So, 2.0 models should avoid those values.  Objections?

**Comment by lexaknyazev** [comment]
I don't follow the reasoning re older APIs but agree that disallowing primitive restart values is a better way moving forward than updating engines.

**Comment by emackey** [comment]
This issue is addressed in glTF 2.0 with #1476.

Should we keep this issue open so that primitive restart can be added in a future version of glTF?

**Comment by lexaknyazev** [comment]
@pmconne A few initial comments:
- There is no need for extra buffer views because index accessors may have appropriate offsets.
- The proposed design provides a complete alternative to the core definition of mesh primitives. In my opinion, this is unnecessary because it's generally redundant, reduces further mesh/primitive extensibility, and potentially enables unwanted discrepancies, e.g., mismatching materials in the extension object and the core primitives. An alternative extension object design could contain just lists of primitives that could be combined and alternative index accessor references.

Please open a new issue or PR to discuss this further.
