### ISSUE TITLE
How to keep mesh index consistency among several key frame meshes?

### ISSUE THREAD

**Issue by PsycoTodd** [KhronosGroup/glTF#1152]
I am trying to use gltf to store several meshes as the key frame for a animated model. The model is single mesh but each of its pose's mesh are also stored in the file.

So first I get all these meshes aligned and to fbx. And use fbx to gltf converter. However I notice that the accessor of gltf shows more vertices number than the original.  For instance' a 8 vertices cube now in gltf has 24 vertices. So seems there is some extra vertices generation. 

What is the reason for that?

And the big issue is that the index accessor, although have the same length among the key frames, do not have extract same index value. So the one to one map of index is not maintained.

What should I do to keep index map same among key frames?

Thank you.

**Comment by donmccurdy** [comment]
You may have better luck getting an answer on this by filing an issue on the FBX2glTF converter. But as a side note, you may want to use [Morph Targets](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#morph-targets) for this — for example, the Blender glTF exporter can create morph targets from Blender shape keys.

**Comment by PsycoTodd** [comment]
@donmccurdy  Thank you for suggestions, let me point this out to the fbx convert channel.

**Comment by javagl** [comment]
> However I notice that the accessor of gltf shows more vertices number than the original. For instance' a 8 vertices cube now in gltf has 24 vertices. So seems there is some extra vertices generation.

A wild (but justified) guess about this: glTF is single-indexed. Mainly because this is the format that will be required for rendering, e.g. with OpenGL. Other file formats (that are not so much targeting the *runtime*) are multi-indexed. (I'm not familiar with FBX, though). 

This basically means: When you have two triangles that share one vertex ('C' in this example) 

    A   D
    |\ /|
    | C |
    |/ \|
    B   E

then this vertex *can* have two different texture coordinates: Once the texture coordinates that it needs as part of the triangle ABC, and once the texture coordinates that it needs as part of the triangle CDE. In order to properly render this structure, the vertex basically has to be duplicated.

**Comment by PsycoTodd** [comment]
@javagl Thank you for the answers. I think that is very clear. Need to check with the convert to see if it is what the convert does ( suppose it is since it targets a run time environment). If that is the case, then their algorithm may be pretty difficult to maintain the index consistency since each duplication process may occur individually? Hope they may have a parameter to enforce that.

**Comment by zellski** [comment]
I'll respond in the FBX2glTF thread too, but all the responses above sound correct. I agree that the 24 vertices almost certainly come about because that's how hard edges are represented. And while the converter is not ever likely to preserve meshes untouched the way you want (it rips the geometry to shreds as a very basic part of its operation), blend shapes / morph targets should do the trick. Then each vertex essentially contains an array of alternate positions, one for each of your poses. As a plus, you can trivially interpolate between them.

**Comment by snagy** [comment]
Technically, if a mesh doesn't contain any normals the 2.0 spec specifies that hard normals should be calculated, but I'm not sure how most engines interpret this.

>Implementation note: When normals are not specified, client implementations should calculate flat normals

**Comment by donmccurdy** [comment]
^can confirm flat normals are used in threejs in this case. Going to close this unless there’s more we can do.
