### ISSUE TITLE
Clarification on byteStride requirement

### ISSUE THREAD

**Issue by zellski** [KhronosGroup/glTF#1198]
[In the spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#data-alignment) we are told that "`byteStride` must be defined, when two or more accessors use the same `bufferView`."

How generally true is this? Is it a general statement for all accessors -- indices, attributes, animation?

I would've assumed so, but:
- Several of the Khronos sample models (generated via COLLADA2GLTF) place the indices of multiple mesh primitives into a single `bufferView`, shared by many accessors (using different `.byteOffset`), and yet there is no `.byteStride` to be seen.
- The Khronos validator seems to go out of its way to restrict testing for `.byteStride` to the accessors of mesh primitive attributes. No such test is done for the indices accessor, nor for animations.

Who's right? The spec, or the sample models & validator?

**Comment by lexaknyazev** [comment]
The `byteStride` property is [valid only for vertex attributes](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#bufferviewbytestride). Using it with other data will result in validation error.

**Comment by zellski** [comment]
Ahh, there it is. Thanks.

It might be nice to just s/two or more accessors/two or more vertex attribute accessors/ in the spec, but I see now that the information is there.

**Comment by TrabacchinLuigi** [comment]
I still don't get it.
I'm working on a GLB/GLTF converter and i got this `MESH_PRIMITIVE_ACCESSOR_WITHOUT_BYTESTRIDE` so i went through the docs and read and read and i see no reason i should get this error, i keep all my buffers separated and tightly packed i have just one view on every one of them and many accessor with an offset

**Comment by lexaknyazev** [comment]
The rule is: `bufferView.byteStride` must be defined when two or more vertex attribute accessors (e.g. `POSITION` and `NORMAL`) use it.

**Comment by lexaknyazev** [comment]
@TrabacchinLuigi 
If there's a particular asset that wrongly triggers this error, please consider sharing it here (it's possible to drag-n-drop zip files to GitHub).

**Comment by TrabacchinLuigi** [comment]
[server.zip](https://github.com/KhronosGroup/glTF/files/3838924/server.zip)
I belive this one triggers it wrongly, hope i'm not wasting your time... but this drome me crazy

**Comment by lexaknyazev** [comment]
In the provided asset, accessors `1`, `5`, `9`, and `13` (named `default_positions`, `default_1_positions`, `default_2_positions`, and `default_3_positions`) all point to the buffer view `1` (named `Positions`) that does not have `byteStride` defined. Same with normals and UVs.

**Comment by TrabacchinLuigi** [comment]
Yes, as i said, but why would i need that bytestride for ? that is the question... all those accessors have offsets a type and a count (data can still be read) ... if there is a requirement of strided data i don't get it... 
why should i make a new bufferview for every accessor ? i'm gonna end with a bigger json than the binary files ...
Why should i use a bytestride is gonna be harder to implement... the file opens.

All this freedom is painful, just say how u want the data to be written.

**Comment by lexaknyazev** [comment]
Buffer views used for mesh attributes roughly correspond to GPU buffer objects with vertices data. For that reason the distance in bytes between consecutive vertices (i.e. stride) must be the same for the whole buffer view. 

When the buffer view is used by just one accessor, it's somewhat reasonable to assume that the effective stride is equal to the `componentLength * componentCount`. For instance, `FLOAT` Vector3 accessors have a stride of `4 * 3 = 12`. So the spec allows omitting it in such a case unless the computed stride is not divisible by 4 (GPU requirement), for instance, Vector3 with `UNSIGNED_SHORT` components must have a stride at least of 8 bytes instead of `3 * 2 = 6`, i.e., it has to be stored as `x|x|y|y|z|z|0|0`.

When the buffer view is used by more than one accessor, there's a possibility that their effective strides don't match, so the spec requires the stride to be explicitly written. The provided asset opens because attributes that use the same buffer views happen to have the same effective stride.

Looking at the provided asset, here's how the issue could be fixed.

**Option 1. Non-interleaved storage, group by attribute**
Keep everything as it is, just add `bufferView.byteStride` with values of `12` to positions and normals and with value of `8` to UVs.

**Option 2. Non-interleaved storage, group by stride**
Positions and normals have the same format with stride of 12, so they could use the same buffer view like (using names from the asset):
```
default_positions | default_normals | default_1_positions | default_1_normals | ...
```

UVs still need another buffer view as their stride is `2 * 4 = 8`:
```
default_texcoords | default_1_texcoords | default_2_texcoords
```

**Option 3. Interleaved storage.**
This option allows packing attributes of different formats in the same buffer view by rearranging vertex data so that per-vertex values are grouped by vertex rather than by attribute.

This layout would allow storing vertex data of all primitives that have similar sets of attribute formats in the same buffer view.

Concretely, for mesh primitives 0, 1, and 2:
```
bufferView.byteStride = 3 * 4 + 3 * 4 + 2 * 4 = 32

bytes of buffer view for each vertex:
  px|px|px|px|py|py|py|py|pz|pz|pz|pz|nx|nx|nx|nx|ny|ny|ny|ny|nz|nz|nz|nz|tx|tx|tx|tx|ty|ty|ty|ty

where
  px,py,pz - Position
  nx,ny,nz - Normal
  tx,ty - UV

accessors' offsets for mesh.primitives[0]:
  position: 0
  normal: 12
  uv: 24

accessors' offsets for mesh.primitives[1]:
  position: 0 + 32 * 128
  normal: 12 + 32 * 128
  uv: 24 + 32 * 128

accessors' offsets for mesh.primitives[2]:
  position: 0 + 32 * 128 + 32 * 16
  normal: 12 + 32 * 128 + 32 * 16
  uv: 24 + 32 * 128 + 32 * 16
```

The remaining `mesh.primitives[3]` has no UVs, so its vertices could either be stored in a separate buffer view (with the stride of 24) or in the same buffer view as other primitives with each vertex padded with 8 zeros to match the stride.

See this chapter of glTF-Tutorials for more examples:
https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_005_BuffersBufferViewsAccessors.md

**Comment by TrabacchinLuigi** [comment]
THANK YOU!
This makes a lot more sense! finally I've understood why it still opens, why it's considered an error, and the purpose of the stride (that i tough it was just a convenient way to store vertex data consecutively).
One last question: are there any performance drawbacks in some of those methods ?

**Comment by tfmertz** [comment]
Does anyone know if there is a sample model available that uses the Interleaved Storage for testing implementations. Thanks!

**Comment by bghgary** [comment]
If you want more specific samples for testing, check out https://github.com/KhronosGroup/glTF-Asset-Generator/tree/master/Output/Positive/Buffer_Interleaved.
