### ISSUE TITLE
How to express the ParametricSurface or ParametericCurve?

### ISSUE THREAD

**Issue by xiongbigbear** [KhronosGroup/glTF#1206]
How to express the ParametricSurface or ParametericCurve?Such as a circle ,ellipse,bspline surface,only mesh to express it?Is there any example?

**Comment by donmccurdy** [comment]
Hi @xiongbigbear — because glTF is a transmission and loading format it focuses on expressing 3D objects in ways closest to what graphics APIs will accept, rather than formats used within an editor. As a result, surfaces and curves are not supported, and conversion to points/lines/meshes should be done in another tool before converting to glTF.
