### ISSUE TITLE
KHR_texture_hdr extension

### ISSUE THREAD

**Issue by UX3D-nopper** [KhronosGroup/glTF#1220]
Environment map will be defined without HDR textures.

However, for PBR and IBL, HDR textures are required.

**Comment by bhouston** [comment]
I think that environment maps and other complex lighting scenarios should not be specified within the glTF file format for the time being.  Correct lighting specification (IES, physically accurate lights) is complex and currently outside of the scope of glTF - at least what I have seen of it.

**Comment by donmccurdy** [comment]
@bhouston you may want to chime in on https://github.com/KhronosGroup/glTF/issues/946 (environment maps) or https://github.com/KhronosGroup/glTF/pull/1223 (lights) instead.

> Correct lighting specification (IES, physically accurate lights) is complex and currently outside of the scope of glTF - at least what I have seen of it.

I'm likewise nervous about what inclusion of environment maps would mean for the scope of glTF, but some users will at least want to use glTF for full scenes. We may need to justify a decision for environments based on the scope we think glTF should have mid-to-long-term. The current scope of glTF is an implicit result of the feature set, and not (yet) any clear consensus on model vs. scene transfer.

**Comment by bhouston** [comment]
@donmccurdy I think with when you add features to a new format without discipline everything seems like a good idea until you are left with an unwieldy mess that nobody can actually implement correctly and consistently.   We are seeing horrible consistency issues with glTF even at its current feature level and the extensions that I think are absolutely necessary will just make it worse.  I think we should keep it focused on a "model" format rather than a "scene" format.

**Comment by lexaknyazev** [comment]
Closing, since the work on this is being done in other threads.
