### ISSUE TITLE
KHR_materials_diffractionGrating extension

### ISSUE THREAD

**Issue by UX3D-nopper** [KhronosGroup/glTF#1222]
For having diffraction grating effects, we want to make this extension to become a KHR_ extension.

Diffraction Grating e.g.:
https://www.alanzucconi.com/2017/07/15/the-nature-of-light/

**Comment by donmccurdy** [comment]
Would encourage interested parties to weigh in here — this feels like a feature that should perhaps begin as a vendor extension.

**Comment by bhouston** [comment]
This diffraction grating idea is overkill.  The CG world has been implementing iridescence using falloff for a decade and it works pretty well.  https://clara.io/view/d4523acd-3a64-44bc-876d-dea12dfdbd3f

The issue is that diffraction grating abstraction is not general enough for all types of anisotropic effects, thus falloff is a better concept.

**Comment by UX3D-nopper** [comment]
Discontinued.
