### ISSUE TITLE
sketchup export gltf, the gltf will lose some thing. such as material

### ISSUE THREAD

**Issue by CharellKing** [KhronosGroup/glTF#1227]
in sketchup:
![abc](https://user-images.githubusercontent.com/1913489/35634933-e5271560-06e7-11e8-850d-8078d04253b0.png)

but in gltf view:

![abcde](https://user-images.githubusercontent.com/1913489/35634992-0b1e8866-06e8-11e8-95cf-56ce2f613b4d.jpg)

below is my sketchup file. how can i solve the problem ?
[组件_412.zip](https://github.com/KhronosGroup/glTF/files/1682470/_412.zip)

**Comment by CentaurMare** [comment]
@CharellKing 
OK, what is going on here, is that the material of the columns between the posts which is being exported is the default (nil) material.

The reason that this material is being exported is because it is actually the default (nil) material in the Sketchup model. Sketchup allows components with nil materials to be 'painted' with a parent material, yet retain a nil material per face. This allows the same component to be reused with a different material,. Unfortunately, due to limitations of the Ruby Sketchup API, it is not easy to get the material from the Ruby script, (especially if it is a texture).

The good news is that there is a work-around: if you simply paint the individual components with the chosen material, it works fine...
![gltf](https://user-images.githubusercontent.com/30219662/35643148-8426410a-0719-11e8-8a7d-3c083e725ee3.png)

@donmccurdy, yes this is my extension. Unfortunately it seems that users of the glTF export script can't report issues on the Sketchup Extension Warehouse, I guess they never built that feature into their website.

**Comment by CharellKing** [comment]
@CentaurMare, in ruby api, you can get some component's parent and get the parent material

**Comment by CharellKing** [comment]
i can do it for you. i can solve it.

**Comment by CharellKing** [comment]
@CentaurMare  sketchup' file format is not open source. so i must decompile some tools to analyze it. it's very hard

**Comment by CharellKing** [comment]
@CentaurMare  sketchup' file format is not open source. so i must decompile some tools to analyze it. it's very hard

**Comment by CharellKing** [comment]
@CentaurMare could your plugin open source to let us improve it

**Comment by CentaurMare** [comment]
I'm aware that I can get the components parent material, however the issue is when that material is a texture. Sketchup has no way defined in the Ruby API for saving that texture to a file unless that texture is applied to a face, and in that case, there may not be a face defined holding that texture.

The way to fix that would be to temporarily apply the material to a new face, but that is then changing the model, which for an export process isn't something I'd want to do. As why should an export process cause the model to need to be saved?

So if you can come up with a way to save the material textures to disk, without reading them from the faces in the model and without causing the model to be modified, let me know!

I will consider open sourcing the code, no promises there.

**Comment by CharellKing** [comment]
if you don't open sourcing the code, i'll  implement the tools myself.  Also i use your plugin in mac os x, your plugin crashes. in windows, your plugin is ok.

**Comment by pjcozzi** [comment]
Given that this is not a spec related issue, should we close this?

**Comment by donmccurdy** [comment]
Feel free to open issues here, like this one, if there’s no other obvious place to put them. But as this thread is no longer active let’s close the issue.
