### ISSUE TITLE
Missing links on reference card

### ISSUE THREAD

**Issue by dakom** [KhronosGroup/glTF#1232]
The reference card/pdf at https://www.khronos.org/files/gltf20-reference-guide.pdf contains some links at the end which are 404:

- https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_pbrSpecularGlossiness

- https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_cmnBlinnPhong

- https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_lights

- https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_technique_webgl

**Comment by javagl** [comment]
These had been added before the extensions have been organized into subdirectories (and even back then, some of the extensions had been in a very early state). 

I'll fix them and prepare an update of the card ASAP.

(I opened https://github.com/javagl/gltfOverview/issues/3, but will leave this one here open until it's done, otherwise people might easily overlook it)

**Comment by javagl** [comment]
Fixed as of https://github.com/javagl/gltfOverview/commit/7532b4e451e449caf0a1e05cf5d9639a086d4914
