### ISSUE TITLE
Point size and line width

### ISSUE THREAD

**Issue by bghgary** [KhronosGroup/glTF#1277]
When using primitive mode POINTS, LINES, LINE_LOOP, LINE_STRIP, what is the expected point size and line width? Should they be 1?

**Comment by takahirox** [comment]
Voting for 1 because 1 is initial value.

I want point size and line width in the spec. (It seems chrome still has line width issue tho https://bugs.chromium.org/p/chromium/issues/detail?id=60124.)

**Comment by donmccurdy** [comment]
What would be the implications of leaving this undefined? glTF 2.0 defines only PBR materials, and there is no physically-based choice for point and line primitives.... 

Line width support isn't likely to be fixed in WebGL or OpenGL; it's been deprecated from the desktop OpenGL spec. The last comment in that Chromium bug sums it up pretty well. I think `1` is the reasonable default, but also wouldn't want to discourage applications from using polygon-based lines if that suits their use case.

**Comment by bghgary** [comment]
> What would be the implications of leaving this undefined?

I'm not sure. If we expect implementations to look the similar then I think we should put an implementation note?

The spec currently says this:
> Implementation note: When the 'mode' property is set to a non-triangular type (such as POINTS or LINES) some additional considerations must be taken while considering the proper rendering technique:
> For LINES with NORMAL and TANGENT properties can render with standard lighting including normal maps.
> For all POINTS or LINES with no TANGENT property, render with standard lighting but ignore any normal maps on the material.
> For POINTS or LINES with no NORMAL property, don't calculate lighting and instead output the COLOR value for each pixel drawn.

So PBR lighting is valid for points and lines if normals are specified.

> I think 1 is the reasonable default
> more abstract representation of a point or line

If both of these happen, what unit is 1?

**Comment by donmccurdy** [comment]
> 

> > I think 1 is the reasonable default
> > more abstract representation of a point or line

> If both of these happen, what unit is 1?

WebGL applications will not be able to consistently render lines at any width but `1px`, I don't think we want to require any particular way of polygonizing lines. The idea that lines represent something more abstract than a GL draw call would lead me to say we leave point/line widths undefined, and put that in `KHR_technique_webgl` instead (for points only).

**Comment by bghgary** [comment]
I'm concerned we have not have consistent implementations if we leave them undefined, but maybe I'm overthinking this.

**Comment by gkv311** [comment]
Just a couple of thoughts.

1px is actually not very nice definition for "consistent" displaying.
I suppose that nowadays all developers are aware about **HiDPI**/Retina displays (mobile/desktop - nevertheless). 1-pixel width line looks _**too narrow**_ on 2x scale display and 3x scale display makes line worse even further! Though non-integer scale factors like 1.5x make more fun.

For this reason, LINE primitives became almost useless with deprecation of glLineWidth() in OpenGL...
That's especially funny, taking into account that Core Profile is the only thing that actually disallows using glLineWidth() in modern applications - every GL developer knows that all drivers still implements this feature in Compatibility Profile, and even all OpenGL ES drivers that I know support line widths higher than 1 (save the Angle project)! It is difficult to understand why vendors have not returned this feature at least in form of GL extension...

**Comment by donmccurdy** [comment]
There is a tension here — we prefer consistent implementations, and we've been careful to ensure consistency for PBR materials (which are broadly used).

However, the only consistent thing we could put into the specification here would be 1px line widths and N-px (square) points. But practically, 1px line widths and square, distance-agnostic points are not likely to be broadly used. WebGL users are probably using these as inputs to custom shaders, or convert line primitives to mesh-based lines. Cesium users probably want point size based on distance from camera, etc. 

So, I'd rather not add point/line size properties to the specification just for the sake of having something to enforce, if applications are not likely to use it. This might be more appropriate for the WebGL extension.

Adding a fixed 1px-width requirement to the spec is OK with me, but feels more appropriate as an implementation note so that applications are still "conformant" if they choose to do something more appropriate (because there is often something more appropriate for a given context).

Suggested:

> **Implementation note:** The core glTF specification does not define size and style of point or line primitives at this time. Point and line widths of `1px` in screen space are suggested for consistency, but applications may use various techniques to render these primitives as appropriate.

**Comment by emackey** [comment]
@donmccurdy Sounds good.  I'll point out that while adding a point size to the vertex shader in WebGL does produce a square pattern of fragments in the rasterizer, it's up to the fragment shader to actually decide on alpha values and use of discard for each of those fragments.  A simple shader could make the points round, or triangular, or any other shape that fits in the square provided.  Since each rendering engine comes equipped with its own PBR shader for glTF PBR materials, presumably each engine would also be free to include its own shader for round points, if desired.

**Comment by emackey** [comment]
The reserved variable `gl_PointCoord` tells the fragment shader where you are inside a multi-pixel point. 
 Cesium [uses it here](https://github.com/AnalyticalGraphicsInc/cesium/blob/0e81d599b91c70d55dc05e134e5c798a8cd74af6/Source/Shaders/PointPrimitiveCollectionFS.glsl#L13) for round points.

**Comment by pjcozzi** [comment]
@donmccurdy there's three +1's above, perhaps open the pull request?

**Comment by donmccurdy** [comment]
Opened #1290.
