### ISSUE TITLE
How to bind bones with vertices in skeleton animation?

### ISSUE THREAD

**Issue by Morozoov8** [KhronosGroup/glTF#1320]
I read glTF tutorial and specs many times and still have some misunderstanding.
How to bind bone's with corresponding vertices and weights? 
I can't find connection between bones or joints and it's vertices.

For example model RiggedSimple.gltf.  This model has one mesh and node number one refers on it. 
Mesh contains fields JOINTS_0 and WEIGHTS_0 for vertexInflunce. But how I can understand which vertex associate which bone or joint?
Also field skin contain a list of skeleton joints. I can to build skeleton tree using it and node hyerarchy, but still can't associate vertices of joints fot true animation.
 
Bones and joints really different things? And if joints is known I can to build bones?  Or it's only diffrent names. I use OpenSceneGraph for it.
 P.S. Sorry for my English. Not native.

**Comment by lexaknyazev** [comment]
The values of `JOINTS_0` contain 4 bone indices per vertex. Those indices correspond to the elements of `skin.joints` array.

**Comment by Morozoov8** [comment]
Yes, understand, thank you!
 Found here the same https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_020_Skins.md.
So joints and bone is the same in glTF?

**Comment by javagl** [comment]
The question was also asked at https://stackoverflow.com/questions/49899193/skeleton-animation-in-gltf-with-openscenegraph-how-to-bind-bones-with-vertices (now deleted). I didn't yet have the time to write an appropriate answer, there because *if* I answered, I'd like to add some images and explain all this in more detail, maybe using the `RiggedSimple` scene as an example. But maybe it's even better to discuss this here, so that the relevant parts may eventually be added to the tutorial.

> So joints and bone is the same in glTF?

They are not exactly the same. The "bones" do not *explicitly* exist in glTF. You can imagine that the "bone" is simply given by the connection between one joint node and its parent. The `skin` only contains all joint nodes that are part of the skeleton. So as an example: Imagine you have a `skin` like this:

    "skins": [ 
      { "joints" : [ 0, 1, 2, 3 ] }
    ],

Then you only know that there exists a bunch of nodes that are part of the skeleton:

             0
              
              
             1
               
                
          2     3


The **structure** of the skeleton (and thus, which "bones" actually exist) is only determined by the hierarchy of the `node` objects. For example, the hierarchy could be defined like this:

    "nodes": [
      { "children" : [ 1 ] }
      { "children" : [ 2,3 ] }
      { ... }
      { ... }
    ]

This means that the bones are arranged as follows:

             0
             |
             |
             1
            / \
           /   \
          2     3

But it could also be defined like this:

    "nodes": [
      { "children" : [ 1 ] }
      { "children" : [ 2 ] }
      { "children" : [ 3 ] }
      { ... }
    ]

Which would mean that there are these bones:

             0
             |
             |
             1
            /  
           /    
          2-----3

(sorry for the ASCII art, but it hope that it helps to make the point clear)

**Comment by Morozoov8** [comment]
Thank you for your time and answer!
I continue to work with skinning and have other question. 
For vertex shader I need to get skinMatrix. For getting skinMatrix need to get JointMatrix, which consist of three matrices: globalTransform, globalJointTransform, inverseBindMatrix. 
InversBindMatrix lays in skin attribute, I found it. 
But for other two can't to realize. 
     globalJointTransform is parameters in node? Such as translation, rotation, scale or just matrix?
For example in model RiggedSimple.gltf:
    
{
            "children": [
                3
            ],
            "translation": [
                0.0,
                -3.156060017772689e-7,
                -4.1803297996521
            ],
            "rotation": [
                -0.7047404050827026,
                -0.0,
                -0.0,
                -0.7094652056694031
            ],
            "scale": [
                1.0,
                0.9999998807907105,
                0.9999998807907105
            ]
        },

 So, what is globalJointTransform then?

**Comment by javagl** [comment]
In general the "global transform" of a node is the product of the (local) transforms of all nodes, starting at the root node, up to the respective node. Some more details about the "global transform" are explained in https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_004_ScenesNodes.md#global-transforms-of-nodes 

(Suggestions for improvements are welcome, of course)

So you cannot determine the *global* transform of the node from `RiggedSimple` that you posted as an example, *without* knowing the transforms of the parents of this node. 

---

Regarding the transforms that are used for computing the joint- and skin matrix: Admittedly, I could need a refresher here as well. I haven't worked on the *implementation* details of this for a while. And there have been some changes between glTF 1.0 and 2.0. 

So take the following with a grain of salt.

Intuitively:

 - the `globalTransform` is the transform of the node that defines the `skin`. 
 - the `globalJointTransform` is the global transform of the joint node that appeared as one of the nodes in the `skin.joints`  array.

So when you encounter the `skin` in one node, then you compute the global transform of this node, as described in the link above, to obtain the `globalTransform` (and take into account the `skeleton` here - sorry, I still have to sort out the details about that). 

Then you compute the global transform of the nodes that appear in the `skin.joints` array, to obtain the `globalJointTransform` for each.

Then the joint matrix of a node `j` is computed as

    jointMatrix(j) = 
        globalTransform^-1 *      // The "^-1" here means the inverse of this transform
        globalJointTransform *
        inverseBindMatrix(j);

As mentioned in the comment: In order to compute the joint matrix, you have to compute the **inverse** of the `globalTransform`. You can imagine this as "removing/eliminating any transform that you are not interested in, for the skinning computations". 

---

I'll try to improve the `Skins` section of the tutorial, once I can allocate the time for that. Particularly, the `skin.skeleton` node is not properly explained there at all. For now, I can just leave the pointer to https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#skins here for details about how to handle the `skeleton` node.

**Comment by donmccurdy** [comment]
There have been quite a few issues opened with questions about how to implement skinning - i think it’s safe to assume that skinning is a complex enough topic in general that developers would welcome tutorials. We’re also working toward creating a glTF forum, which may help for this sort of discussion.

In the meantime, I’ll close this issue.
