### ISSUE TITLE
Animation start time behavior

### ISSUE THREAD

**Issue by bghgary** [KhronosGroup/glTF#1327]
If the first sampler input of an animation has a time value greater than 0 (say 1.5), what should the runtime behavior be?

1. Start at 1.5 seconds.
2. Start at 0 seconds using clamped behavior, wait for 1.5 seconds, then continue the rest of the animation.

three.js does 2
BabylonJS currently does 1
Sketchfab, as far as I can tell, does 1
Unity does 2

The original issue here:
https://github.com/BabylonJS/Babylon.js/issues/4224

**Comment by javagl** [comment]
> Start at 0 seconds using clamped behavior

Just to clarify: By "clamped behavior" you mean that at 0.0 seconds, the model should have the same state as it will have at 1.5 seconds? 

Pseudocode:

    node0 : {
        translation: [ 0,0,0 ]
    }

    animation: {
        target: node0.translation,
        time:   [   1.5,     2.5   ],
        values: [ (1,0,0), (2,0.0) }
    }

So the difference here would be that the node 

- **either** has a translation of (0,0,0) at the beginning, and then jumps to (1,0,0) at time 1.5 
- **or** has a translation of (1,0,0) at the beginning, because that's what the animation will start with

Correct?

(I'm just wondering: If this is the issue, then the difference only becomes apparent when the "default" (un-animated) state differs from the first state that appears in the animation. But of course, this should be made clear in the spec)

<sub>(Vaguely related: https://github.com/KhronosGroup/glTF/issues/573 and https://github.com/KhronosGroup/glTF/issues/1179 )</sub>

**Comment by donmccurdy** [comment]
By `first sampler input of an animation` I assume you mean _earliest_ sampler, not the first sampler listed in the array, or the sampler of the first channel, right? `(1) Start at 1.5s` does not seem inappropriate for cinematic playback, but for three.js it would mean throwing away delay information that could very well have been intentional when multiple animations are being used, so I would want to stick with (2) there... A cinematic viewer built on three.js can always normalize clip start times if desired.

Whether the clamped behavior should be enforced, I don't know. What if two animations were queued to affect the same node:

```
node1.clipA ---------------|--|--|--|--|--|
node2.clipB --|--|--|--|--|----------------
node2.clipC ---------------|--|--|--|--|--|
```

One assumes that `clipA` should clamp, and `clipB`'s actual keyframes should override `clipC`'s implicit "clamp", but this is a fairly specific prescriptive thing for us to say when the spec is mostly silent on runtime playback of multiple clips.

**Comment by bghgary** [comment]
@javagl 
> Just to clarify: By "clamped behavior" you mean that at 0.0 seconds, the model should have the same state as it will have at 1.5 seconds?

Yes, this is what I mean.

@donmccurdy 
> By `first sampler input of an animation` I assume you mean earliest sampler, not the first sampler listed in the array, or the sampler of the first channel, right?

I mean the earliest sampler input value from any sampler within one animation.

**Comment by bghgary** [comment]
> Whether the clamped behavior should be enforced

I think if we go with 2, then it should be, similar to the clamping behavior in #1179.

**Comment by pjcozzi** [comment]
@bghgary does this need a spec update or implementation note?

**Comment by bghgary** [comment]
@bghgary does this need a spec update or implementation note?

+1 on @donmccurdy's wording. I think this should be normative and not an implementation note.

**Comment by donmccurdy** [comment]
Proposed #1348.
