### ISSUE TITLE
Node.SRT and  animation keyframe

### ISSUE THREAD

**Issue by senthuran-lkn** [KhronosGroup/glTF#1368]
Hi. I see that the node can only store SRT data when it is targeted for animation.

so let say that for frame N I computed the Frame SRT matrix M1, so do I have to multiply with the node SRT matrix?

The reason I'm asking this question is that I have  a gltf model with 4 skinned animations.
In my  code I'm interpolating the keyframe SRT and creating a final world matrix. 
This works fine for the first animation but the rest looks like they are not transformed properly.
So I have tried chaning the code by Multiplying the Frame Matrix with the node SRT matrix and its even worst. 

According to the spec: 
"When a node is targeted for animation (referenced by an animation.channel.target), only TRS properties may be present; matrix will not be present."
It seems like the node TRS should be multiplied with the key frame interpolated SRT matrix.

**Comment by senthuran-lkn** [comment]
I have closed this issue because I had a bug in my matrix multiplications,  It seems like as the spec says the frame N matrix multiplied with the SRT matrix fixed the issue.

**Comment by moll** [comment]
I wanted to confirm the same thing --- you're saying the static TRS properties are also to be taken into account when that node is being animated? In other words, a node that has both a static translation property and an animation translating it, gets it final position from the sum of the static and dynamic translation?

**Comment by zellski** [comment]
Each local node property that's targeted by an animation **overrides** that specific property. Local node properties that are **not** animated retain their static values, if provided. And of course, the local node is still relative to the world matrix, as determined by ancestral parts of the scene graph.

I'm not sure exactly what @senthuran-lkn is saying in his closing comment. It's not the case that you'd multiple e.g. a node's local scale by a scale value for that node that comes from an animation.

(Or at least I hope it's not, because then I am doing bad things in FBX2glTF.)

**Comment by moll** [comment]
Thanks, @zellski! Just as you replied, I was writing https://github.com/KhronosGroup/glTF/issues/1425. I raised another question there, so I'll leave it open for both another confirmation and perhaps until the spec gets clarified, too.

**Comment by emackey** [comment]
Yes, the animation **overrides** (does not multiply with) the existing static node values.  Do we need a sample model to demo/test this?

**Comment by bghgary** [comment]
Repeating what I said in the other thread:
> The asset generator project has a test for overriding the local transform from an animation. Test 05 from https://github.com/KhronosGroup/glTF-Asset-Generator/blob/master/Output/Animation_NodeMisc/README.md
