### ISSUE TITLE
Must slerping between quaternions for an animation curve always go the short way round?

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF#1395]
ie. when interpolating from q1 to q2, should q2 be replaced with whichever of {q2, -q2} is closest to q1?

Please see https://github.com/KhronosGroup/glTF-Sample-Models/issues/185.

The text in the spec is

> When targeting a rotation, spherical linear interpolation (slerp) should be used to interpolate quaternions.

Apparently most implementors have read this to mean that the short way round must be used but this is not implicit in the text.

And what about cubic interpolation?

**Comment by bghgary** [comment]
> And what about cubic interpolation?

I don't think there are multiple ways to interpret the cubic interpolation. The [math in the appendix](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#appendix-c-spline-interpolation) is what should be used to get the resulting value.

**Comment by stevenvergenz** [comment]
Any official word on this? Is short-way around assumed? This is inconsistent between players right now (Windows 3D Viewer vs Unity).

**Comment by lexaknyazev** [comment]
Two consecutive rotation quaternions define a great circle on which the intermediate values are located. Technically, the sign of their dot product defines whether the short or the long path is selected for the interpolated values.

For example with three intermediate points,

- Positive dot product
  - `q0 = [0, 0, 0.7071, 0.7071]` (+90° around the Z axis)
  - `q1 = [0, 0, 1, 0]` (+180° around the Z axis)
  - Interpolated angles (each step is +22.5°): 90°, 112.5°, 135°, 157.5°, 180°.

- Negative dot product
  - `q0 = [0, 0, 0.7071, 0.7071]` (+90° around the Z axis)
  - `q1 = [0, 0, -1, 0]` (-180° around the Z axis)
  - Interpolated angles (each step is -67.5°): 90°, 22.5°, 315°, 247.5°, 180°.

 Since the spec is silent on this topic, we have three options:
- State that each two consecutive quaternions denote the short path, regardless of their dot product sign.
  - Pros: seems like most engines already assume that.
  - Cons: slightly less efficient data storage in some cases, extra runtime logic, some engines may have different assumptions.
- State that consecutive quaternions must not have negative dot products, leave interpretation of such data undefined.
  - Pros: no engine updates.
  - Cons: invalidating some models (including our samples), putting the extra burden on exporters.
- State that the path selection depends on the dot product sign.
  - Pros: Potentially more efficient data storage, less runtime operations.
  - Cons: Likely breaking the ecosystem.

@emackey @bghgary @donmccurdy @javagl WDYT?

**Comment by emackey** [comment]
@scurest As a point of reference, are any of these better or worse for Blender's sake?  Do you happen to have an opinion on which would be best for the glTF ecosystem?

**Comment by scurest** [comment]
IMO (1) (two consecutive quaternions denote the short path, regardless of their dot product sign) is already the case (based on the sample and what implementations actually do) and just needs to be added to the text.

I don't think there are any particular implications for Blender though beyond that obviously (1) is already what is implemented there.

**Comment by emackey** [comment]
Agreed, I think sticking to (1) for the sake of minimal breakage is the right path here.  Thanks @scurest.

**Comment by lexaknyazev** [comment]
If we specify (1) as the required interpretation, I think we should still recommend exporters to generate continuous quaternion sequence.
