### ISSUE TITLE
support for models without indices ?

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/glTF#14]
We agreed to start conservative by doing so, though we are aware it can be not convenient for points. Keep track of this here for now.

**Comment by mlimper** [comment]
> requiring indices until we get significant community feedback otherwise. Here the current language I have in the spec:

Here's some community feedback :-)

Since release 1.0 is coming closer, I just wanted to ask if it really makes sense to force the "indices" property?

It would help to use non-indexed data even for some cases where you render triangles, for example when using flat shading (since the per-face normals require you to duplicate vertices anyway, you'll end up without any re-use of data).
This seems like a quick win, by just defining indices to be an optional property... or would that cause problems?

**Comment by pjcozzi** [comment]
I agree that indices should not be required.  I think we need to tweak the spec a bit, but I haven't looked closely.  See https://github.com/KhronosGroup/glTF/issues/60#issuecomment-136769807

Let's continue the conversation in that issue.
