### ISSUE TITLE
asymmetric tangents in cubic spline

### ISSUE THREAD

**Issue by andreasplesch** [KhronosGroup/glTF#1411]
In glTF cubic spline interpolation requires an in tangent and an out tangent for each data point/vertex:

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#appendix-c-spline-interpolation

This means that the in and out tangents can be different.

```
in0 p0 out0
in1 p1 out1
```
in and out are the tangents, p are the points

However, at least Wikipedia claims here

https://en.wikipedia.org/wiki/Cubic_Hermite_spline
https://en.wikipedia.org/wiki/Cubic_Hermite_spline#Interpolating_a_data_set

that the only sensible choice for interpolating a data set of connected intervals is to have the same tangent at connected points. Is that the case in practice ? I could not really find examples of cubic spline animation other than from the asset generator.

~~This would mean that the out tangent of one interval is equal to the in tangent of the next interval.~~
This would mean that the out and in tangents are the same.

```
out0 p0 out0
out1 p1 out1
out2 p2 out2
```

While this choice could be left to the generator, it may make more sense to just require a single tangent for each point (the out tangent). Having a single tangent reduces file size and makes implementation simpler (arguably).

So the question really is if asymmetric tangents occur in practice, and if not, if it makes sense to modify CUBICSPLINE for a future glTF, or introduce a CUBICSPLINE2 mode.

**Comment by bghgary** [comment]
> Cubic_Hermite_spline

The intention of stating cubic Hermite spline in the appendix is just for the equation. This is perhaps misleading and we can add some clarification.

> asymmetric tangents occur in practice

I have seen animations where the in and out tangents are different and intended to be a non-smooth transition in the animation.

Would you like to open a PR updating the wording in the appendix to make it less misleading?

**Comment by andreasplesch** [comment]
Yes, sharing tangents at connected points actually simply means in tangent = out tangent. I have corrected above.
Well, if asymmetric tangents for non-smooth transitions do occur, there may not be a need for much of an update. The question was not about how to apply the formula but if it makes sense to distinguish in and out tangents. See #1412 for suggested wording updates.
I think asymmetric tangents result in 'overshooting', eg. having the change in curvature not at a point/key frame.
Non-smooth transitions may need to be represented by repeating a key with the same value but different tangents.

**Comment by emackey** [comment]
I think a good example is a bouncing ball.  You need sharp, discontinuous curves where the ball reflects off a surface.

![bouncing](https://user-images.githubusercontent.com/1235080/43605235-c17b77d8-9665-11e8-9088-5eb213738bf4.gif)

**Comment by andreasplesch** [comment]
Yes, excellent example. Do you have a corresponding glTF animation ?

**Comment by emackey** [comment]
Actually yes!

[BouncingAnimationTest.zip](https://github.com/KhronosGroup/glTF/files/2255365/BouncingAnimationTest.zip)

@donmccurdy I discovered something while debugging the animation export code, trying to get Blender to cough up a real `CUBICSPLINE` for this as opposed to a bunch of tiny baked linear frames.  In my original Blend file, I had a Z channel with the keyframes shown above, and I had disabled X and Y channels with a single keyframe each, that weren't really animated but were just there as a consequence of creating a location animation in Blender.

The export was hitting [this test for matching keyframe counts](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/cc9501221204775e30513b1c9c436ae6383211ba/scripts/addons/io_scene_gltf2/gltf2_animate.py#L64-L65).  From there it decided on `CONVERSION_NEEDED` instead of `CUBICSPLINE`.

I fixed my blend file by deleting the X and Y sub-channels, leaving only Z.  After that the export was willing to write a true `CUBICSPLINE` into the glTF.

@andreasplesch The output of the ball bouncing animation in this case ended up in accessor index 7.  I dumped the contents with VSCode (Blank lines added by me to separate individual keyframe outputs)

```
    0.00000     0.00000     0.00000 
    0.00000     5.00000     0.00000 
    0.00000     0.00000     0.00000 

    0.00000    -9.41095     0.00000 
    0.00000     0.00000     0.00000 
    0.00000     9.08742     0.00000 

    0.00000     0.00000     0.00000 
    0.00000     5.00000     0.00000 
    0.00000     0.00000     0.00000 

    0.00000    -9.82252     0.00000 
    0.00000     0.00000     0.00000 
    0.00000    10.26358     0.00000 

    0.00000     0.00000     0.00000 
    0.00000     5.00000     0.00000 
    0.00000     0.00000     0.00000 
```

Note that the Z channel has been converted to Y, per glTF's Y-up orientation.  The first three lines show the ball starts at Y=5, padded with zeros for in and out.  This pattern is repeated for each of the three keyframes at the top.  Lines 4 to 6 and 10 to 12 show keyframes at Y=0 (the bottom), with the in and out Y vectors heavily modified.

**Comment by andreasplesch** [comment]
Thanks. It looks nice and bouncy in the three.js viewer and the babylon sandbox. I tried to go literally by the spec. and the formula in another viewer but it does not look quite the same, more smooth and no real bounces. Let me carefully check things.

**Comment by donmccurdy** [comment]
Here's the three.js interpolation code, if that's helpful: https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTFLoader.js#L901-L954

**Comment by andreasplesch** [comment]
Thanks. Yes, that is what I also thought should be done. Through some experimenting I found now that I get a better result if I do not scale the tangents by td, the interval between the frames. In my viewer (x3dom) this must be related to how time is provided to the interpolator as a fraction of the total duration of the animation, not in seconds. This does not affect p (t in the formula) and therefore the s factors (the basis function) but apparently affects the scaling of the tangents by the interval. 
Let's see. The formula expects the interval to be in seconds. The tangents are provided in units/second, probably. How would one convert intervals of fractional time to seconds ?
```
td = ft * d
ft : fractional interval
d : duration of animation
```
That's it.
Since the duration of the bounce animation is 3.3s and there are 4 intervals, each interval is about 0.75s. So not scaling (equivalent to 1s intervals) was close enough by coincidence. It will just be necessary to keep track of the total duration and factor it in.
I think it will be quite useful to have such an example included/generated in a test suite.

**Comment by andreasplesch** [comment]
In
https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTFLoader.js#L901-L954
the s factor computation could be slightly optimized:
```
                var s0 = 2 * ppp - 3 * pp + 1;
		var s1 = ppp - 2 * pp + p;
		var s2 = - 2 * ppp + 3 * pp;
		var s3 = ppp - pp;
```
to
```
                var s2 = - 2 * ppp + 3 * pp;
		var s3 = ppp - pp;
                var s0 = 1 - s2;
		var s1 = s3 - pp + p;
```
May not be worth the trouble.
