### ISSUE TITLE
Animation: scope for channel target id/path

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#142]
This is the first in a series of questions (over the next week or so) to help me nail down my glTF animation implementation and properly word the spec.

In our current design, given a channel's target, e.g.,

``` javascript
"target": {
  "id": "_-1236436",
  "path": "translation"
}
```

Am I correct that:
- `id` can only reference a `node`?
- `path` must be `"translation"`, `"rotation"`, or `"scale"`?

I am OK with only having TRS animations for glTF 1.0, but are we confident that we won't need breaking changes to make this support `instanceTechnique` parameters for example?

**Comment by pjcozzi** [comment]
Given that this is not a breaking change, isn't widely used AFAIK, and I don't think we would have time to implement it, I suggest we push this from 1.0.

**Comment by carlsonsolutiondesign** [comment]
Events, data and color binding and animation.  Strike out animation from the spec and show me how your events, color and data binding are better than D3 + X3DOM???

**Comment by pjcozzi** [comment]
@carlsonsolutiondesign I am not following.  We would not remove animation from the spec.  My suggestion is to keep animation targets as they are currently scoped (node transforms) and then widen the scope (e.g., to target material parameters) in an upcoming glTF version when we have enough time to implement it and make sure the design is solid.

@tparisi I still suggest we go this route.

**Comment by tparisi** [comment]
@pjcozzi I'm not sure what the issue is here any more. Maybe close this and open others e.g. 1) add the ability to animate arbitrary properties and 2) add texture matrices as properties that could be animated.

**Comment by pjcozzi** [comment]
I'm going to leave this open, but drop the `1.0` label since it has a lot of useful discussion.  When we revisit, we can divide it into two issues if needed.

**Comment by carlsonsolutiondesign** [comment]
My apologies.  I googled glTF animations and I thought this was the word on animations for 1.0.  node animations are likely enough.


How do you do animations? Is it in the JSON or otherwise?

John
On Sep 16, 2015, at 12:56 PM, Patrick Cozzi <notifications@github.com<mailto:notifications@github.com>> wrote:


@carlsonsolutiondesign<https://github.com/carlsonsolutiondesign> I am not following. We would not remove animation from the spec. My suggestion is to keep animation targets as they are currently scoped (node transforms) and then widen the scope (e.g., to target material parameters) in an upcoming glTF version when we have enough time to implement it and make sure the design is solid.

@tparisi<https://github.com/tparisi> I still suggest we go this route.

**Comment by carlsonsolutiondesign** [comment]
Let me be plainer about my goals:

I still think data-driven and sensor driven animation is important.  Can someone who is familiar with the giTF spec comment on data-driven animation?  Or at least, animation of data provided to glTF from outside glTF?  That is, can I provide different data sets for the same animation?
How does this work?  Do I modify the JSON and send it back through the pipeline, or do I keep the JSON the same and just modify the live data?  Where is the live data stored?  What are the JSPath or JSONPath solutions in this area?

What’s the best way to combine 3D and multidimensional data for a final visualization?  Time to look into cesiumjs I guess.

John
On Sep 16, 2015, at 1:22 PM, John Carlson <john@carlsonsolutiondesign.com<mailto:john@carlsonsolutiondesign.com>> wrote:

My apologies.  I googled glTF animations and I thought this was the word on animations for 1.0.  node animations are likely enough.


How do you do animations? Is it in the JSON or otherwise?

John
On Sep 16, 2015, at 12:56 PM, Patrick Cozzi <notifications@github.com<mailto:notifications@github.com>> wrote:


@carlsonsolutiondesign<https://github.com/carlsonsolutiondesign> I am not following. We would not remove animation from the spec. My suggestion is to keep animation targets as they are currently scoped (node transforms) and then widen the scope (e.g., to target material parameters) in an upcoming glTF version when we have enough time to implement it and make sure the design is solid.

@tparisi<https://github.com/tparisi> I still suggest we go this route.

**Comment by pjcozzi** [comment]
@carlsonsolutiondesign animations are stored in JSON, and the keyframes are stored in binary.  There's an example here (search for "animations"): https://raw.githubusercontent.com/AnalyticalGraphicsInc/cesium/master/Apps/SampleData/models/CesiumMilkTruck/CesiumMilkTruck.gltf

**Comment by pjcozzi** [comment]
glTF animations are key-frame animations stored as part of the glTF.  An engine could modify/add/remove these at runtime, but, at least in Cesium, that use case is handled by giving users direct access to the transform for each node so they can modify it.  This [Cesium example](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Interpolation.html&label=All) may also be of interest to you.

If you have more Cesium questions, please post them on the [Cesium forum](http://cesiumjs.org/forum.html) so we can keep this repo focused on glTF.

**Comment by pjcozzi** [comment]
Replaced by #1191 for easier tracking.
