### ISSUE TITLE
Consider a user forum?

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF#1500]
We currently have:

- Github: https://github.com/KhronosGroup/glTF/issues (for spec/extension discussion)
- Gitter: https://gitter.im/KhronosGroup/glTF (for realtime, unstructured discussion)

Would anyone be interested in a forum, for archived discussion of (non-spec, non-extension) topics? For example, to post a project you're working on and get feedback, or to get help with glTF-related tools. I think end-users of the format are probably not comfortable posting that sort of thing on GitHub, and discussions in Gitter disappear pretty quickly.

**Comment by lexaknyazev** [comment]
There's also a [Stack Overflow tag](https://stackoverflow.com/questions/tagged/gltf).

> I think end-users of the format are probably not comfortable posting that sort of thing on GitHub

And even if they are, spec's GitHub doesn't work well for such things.

**Comment by javagl** [comment]
A forum could be useful to fill the gaps between the issue tracker, the gitter and stack overflow:

- a chat does not work for longer, structured discussion
- general questions or problems with tools etc. are not exactly "issues" that belong into the glTF issue tracker. I think that we're already observing the effect of abusing the issue tracker here for general discussion: People are asking questions in the hope for an advice. I think the issue tracker could **greatly** benefit from a clearer focus on **only** spec-related issues.
- stack overflow may be reasonable for *some* sorts of questions. But I noticed that most questions are not really specific for glTF, but rather about things like "How to achieve X with glTF in tool Y". And people might hesitate to ask there, because ... stack overflow is *"Not Very Welcoming®"* ;-)

So +1 for a forum.

**Comment by donmccurdy** [comment]
Related, there is now a Khronos Group Slack workspace, which includes a glTF channel: https://twitter.com/thekhronosgroup/status/1067478830972108800. Slack and a forum could be complementary, I think, but Slack and a Gitter channel may be redundant..

**Comment by Ybalrid** [comment]
A forum would probably be useful really useful! What's great about a forum is that it maintains the discussions in a clean order by topic, and is easily search-able. It also can be a nice area to discuss glTF related projects, and keep the GitHub issues for talking about the actual glTF specs and the other related documents present in this very repository.

**Comment by emackey** [comment]
@donmccurdy Any thoughts on ThreeJS's discourse?

**Comment by donmccurdy** [comment]
I do like Discourse, definitely the most polished forum platform I've used. [W3C WIGC](https://discourse.wicg.io/) uses it too. If we are going to create a forum, the only downside I see with Discourse is that Khronos already has a bunch of forums, including COLLADA and KTX, using vBulletin: https://forums.khronos.org/.

**Comment by pjcozzi** [comment]
Twitter poll results:

![image](https://user-images.githubusercontent.com/782098/49654246-5012f400-fa05-11e8-86e5-32a4bc293cd0.png)

See the full twitter thread: https://twitter.com/pjcozzi/status/1070433721801674757

Generally, community preference is a forum or maybe Stack Overflow - but not something more chat focused like Slack or Gitter, due to search-ability.

**Comment by donmccurdy** [comment]
I think Stack Overflow should be considered a complement to whatever else we choose... It's a useful place to help users and find answers, but doesn't allow any sort of unstructured discussion, show-and-tell, or broad questions.

**Comment by emackey** [comment]
Stack Overflow is awesome, but polices itself to be rigidly question + answers, not like the general discussion of a forum.  So I think a forum can co-exist with SO and one chat channel.

I think the choice is down to either a Discourse forum as linked above, or the existing Khronos vBulletin.  The latter fits in with the rest of the Khronos ecosystem, and is likely the lowest friction to get set up officially, but the look of it is very dated.  glTF is supposed to look modern and shiny.  The Discourse one looks a lot more modern, but would be disconnected from all other Khronos forums.

**Comment by fraguada** [comment]
Re. the discourse route, they offer a [free hosted instance for open source projects](https://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/). The requirements:

- [x] 15+ contributors
- [x] Your project has a clear need for discussions (see FAQ below)
- [x] Please understand that approval is ultimately at our discretion as we work out the details of this program.
- [x] ~Must be hosted on GitHub~ GitHub is no longer a requirement.
- [x] ~2000+ stars~ Star count is no longer a requirement.

Since discourse.threejs.org was setup, the terms have changed, specifically:

> You will get a sub-domain of your choosing on the *.discourse.group domain, e.g. myproject.discourse.group.

This used to be:

> We require a sub-domain with a specific convention, i.e.: discourse.example.org. This is the only piece of “branding” we require.

[source](https://web.archive.org/web/20170111210157/https://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/)

and

> There is a bandwidth limit of 50k monthly page views, equivalent to half of our Standard hosting plan.

Their standard hosting plan used to include 100k monthly page views.

Regarding the pageviews, these are the stats for discourse.threejs.org:
<img width="594" alt="screenshot 2018-12-12 at 22 56 51" src="https://user-images.githubusercontent.com/1014562/49901404-67b50700-fe61-11e8-8453-5a91dce23c3e.png">

and overall since the beginning:

<img width="1148" alt="screenshot 2018-12-12 at 22 56 12" src="https://user-images.githubusercontent.com/1014562/49901471-90d59780-fe61-11e8-9dc8-6d11fe6766f0.png">

As you can see, discourse.threejs.org is over the monthly pageviews offered when first beginning (if I'm reading discourse stats right), and it took probably a year to get there. November 2018 was roughly 150k pageviews I guess.

I only mention this because the terms they mention can be hit rather quickly for a healthy project with a lot of traction. Looking at the differences in scope and community between glTF and three.js, I'd say the discourse terms are pretty decent for the glTF project and I'd argue it would be a great place to build and support the community, probably even more so than for a project like three.js, that is getting a good deal of questions from people consuming the library, and fewer questions from people contributing to the project. 

Finally, I think @emackey's comments are very relevant:

>  The Discourse one looks a lot more modern, but would be disconnected from all other Khronos forums. Is that a deal-breaker?

Since I've contributed very little to this project, I'd be very interested to hear what others with more cred would think on this point.

**Comment by donmccurdy** [comment]
[Forums](https://community.khronos.org/) and [Slack](https://www.khronos.org/news/permalink/khronos-developer-slack-5bfc62eb261764.20435008) are now available.
