### ISSUE TITLE
inverseBindMatrices and orthogonality?

### ISSUE THREAD

**Issue by Ziriax** [KhronosGroup/glTF#1507]
At first sight the spec doesn't mention anything about this, but are the skin inverse bind matrices allowed to be non-orthogonal, e.g. skewed / not decomposable into TRS?  I hope it is allowed ;-)

**Comment by lexaknyazev** [comment]
@donmccurdy @bghgary any thoughts on this?

**Comment by donmccurdy** [comment]
Great question... I don't know what the implications of this would be. We do require that node matrices be decomposable to TRS, so my first reaction would be consistency, but I'm willing to be talked out of that.

**Comment by scurest** [comment]
It has to be allowed because the composition of TRS transforms is not necessarily a TRS transform and the inverse of a TRS transform is not necessarily a TRS transform (because of non-homogeneous scalings; example follows). The prototypical use of the inverse bind matrices is to have them be the inverses of the compositions of the node's TRS transforms (literally the inverses of the bind matrices), which would be disallowed if they (the inverse bind matrices) were required to be orthogonal.

More ambiguous is whether the last row of an inverse bind matrix can be anything other than (0 0 0 1). Because when you apply a 4x4 matrix to a 3-vector to get another 3-vector, when you come back from homogeneous coordinates you can either discard the final component, (x, y, z, w) -> (x, y, z), or perspective divide out by it, (x, y, z, w) -> (x/w, y/w, z/w). These are the same if the last row of the matrix is (0 0 0 1), but they're different otherwise, and different implementations might do different things.

<p align=center><img src="https://user-images.githubusercontent.com/11024420/49898509-db81f000-fe1e-11e8-9f4b-dd1f0f7b0615.png"></p>

**Comment by Ziriax** [comment]
@scurest: very nicely formulated. That's why I said I hope it was allowed. We perform a lot of non-uniform scaling on our cartoony characters, and we often have non-orthogonal inverse bind matrices because of this. 

So yes, it must be allowed IMO2

Thanks

**Comment by Ziriax** [comment]
@bghgary Inverse bind matrices are not stored in nodes, neither in glTF nor Unity3D as far as I can recall, the [Mesh.bindPoses](https://docs.unity3d.com/ScriptReference/Mesh-bindposes.html) array holds `Matrix4x4` values

**Comment by bghgary** [comment]
@Ziriax, I am agreeing that inverse bind matrices don't need this requirement. Only node transforms need to be decomposable. Sorry for not being clear.

**Comment by lexaknyazev** [comment]
Should the last row still be `(0 0 0 1)`?

**Comment by kcoley** [comment]
I came across a model today exported from the Babylon Maya glTF exporter.  The glTF validator indicates that there is an error in the accessor  containing the inverse bind matrices data, but the model is able to run in Babylon.js and Three.js
[test.zip](https://github.com/KhronosGroup/glTF/files/2734712/test.zip)

Looking at the matrices of the inverse bind matrices, the last row is not `(0 0 0 1)` on the last row for some of the matrices.  

I was wondering if this should not be considered a validation error?

**Comment by lexaknyazev** [comment]
The updated spec requires the last row to be equal to `(0 0 0 1)`.
