### ISSUE TITLE
Question about extension usage

### ISSUE THREAD

**Issue by Kaesebrot84** [KhronosGroup/glTF#1524]
What are extensions exactly? I. e. I would like to include  the `KHR_materials_pbrSpecularGlossiness` in my application. Is this extension just a specification? Are there any tools that allow to incorporate those extension into my gtlf files? 
I am using `Blender` for model creation. Is it possible to use the `KHR_materials_pbrSpecularGlossiness` extension like I would do with `pbrMetallicRoughness`?

In Blender I export to gltf via [Blender glTF 2.0 Exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter#blender-gltf-20-exporter)

**Comment by donmccurdy** [comment]
For a (sort of technical) introduction to extensions, I would start here: https://github.com/KhronosGroup/glTF/tree/master/extensions#about-gltf-extensions. Glad to answer other questions you might have, too.

Most tools will support at least some glTF extensions — some are very common (KHR_materials_unlit) and others a little more use-case-specific. Where do you want to use the files you're creating?

The (older) Blender exporter you link to does support the `KHR_materials_pbrSpecularGlossiness` extension, but requires a special Cycles node because Blender itself doesn't have a spec/gloss PBR material. See https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/docs/user.md for details.

Unless you particularly need spec/gloss PBR, I would advise using the newer Blender exporter (https://github.com/KhronosGroup/glTF-Blender-IO) which doesn't require special nodes and can export metal/rough PBR from Blender's default Principled BSDF node much more easily. However I don't think it supports that extension for spec/gloss PBR. If spec/gloss is very important to you, using a tool that is designed for it like Substance Painter (which also supports this extension, I believe) is probably a better idea.

**Comment by Kaesebrot84** [comment]
@donmccurdy Thanks that helped. I am using my assets in WebGL2, btw.
