### ISSUE TITLE
Geometry twisted while given a vary large coordinate(e.g. under epsg:3857)

### ISSUE THREAD

**Issue by intckarl** [KhronosGroup/glTF#1610]
Hello,

When having gltf and glb file georeferenced, the coordinate could be very large, for example here in Beijing, China, a typical coordinate under epsg:3857 would be something like:

> "x":12958095.124851028,"y":4865499.469870342,"z":0

Then the model will look like this:
![QQ截图20190510113815](https://user-images.githubusercontent.com/14276240/57501035-83411280-7318-11e9-93db-ec334717a914.jpg)

I believe this is a bug. could you fix this, please?
Thank you.

**Comment by javagl** [comment]
One can argue about whether this is a "bug". In any case, it will be hard to "fix" it, because you're (almost certainly) simply hitting the limits of what can be represented with `float` values. At least, a similar issue was discussed quite a while ago: https://github.com/KhronosGroup/glTF/issues/781#issuecomment-263252480 (it's also *geographically* similar, for that matter ;-)). 

Depending on the model and the viewer that you are using, there might be workarounds, though. Maybe someone who has more experience with the large values that appear in GIS systems can give a hint here.

**Comment by intckarl** [comment]
@javagl  Thank you for reply.
Do you mean that in float value there can only be 7 significant digits?
If so, is there any chance to add support of double value to the spec?
Or just add epsg code for the client to render accordingly?

**Comment by javagl** [comment]
I hope that someone who has a deeper knowledge about rendering will jump in here.

But until then: Yes, the values that you mentioned will exhaust the ~7 significant digits of `float`, so that vertices collapse or are placed at the wrong position.  And I'm pretty sure that support for `double` in the spec is not realistic, because even if glTF supported it, there wouldn't be any support in engines, graphics APIs and drivers in sight. (In Vulkan, maybe?)

How such a large translation could sensibly be represented has to be answered by a rendering/GIS expert. I can only say that the geometry data *in the glTF asset itself* should not contain such a large translation.

**Comment by intckarl** [comment]
In that case I should just close this topic, thank you!
