### ISSUE TITLE
KHR_image_ktx2 scheme missing metadata offset & size.

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/glTF#1619]
Doesn't it need `metadataByteOffset`, `metadataByteLength`, `imagesByteLength` and `uncompressedImagesByteLength`?

**Comment by lexaknyazev** [comment]
I thought that since metadata has JSON representation, there's no need to keep a pointer to its original form. It may be useful for custom keys, so I'll add it.

Considering that `levels` array has byte lengths for each level, I don't think that we need to keep the aggregates. As a general rule, I'd avoid data redundancy to reduce the number of corner cases.

**Comment by donmccurdy** [comment]
We are planning to skip the `KHR_image_ktx2` extension, and the scheme data mentioned above, and instead rely on the `KHR_texture_basisu`  (as well as potential non-basis IBL extensions) to explicitly allow KTX references from image entries.
