### ISSUE TITLE
Why is UNSIGNED_BYTE/UNSIGNED_SHORT valid for quaternion storage?

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glTF#1622]
The spec enumerates 5 possible storage formats for quaternions when used as output data for animation samplers: FLOAT, normalized BYTE/UNSIGNED_BYTE, normalized SHORT/UNSIGNED_SHORT.

FLOAT and normalized signed formats make sense (although 1+7 bits per quaternion component are pretty bad as far as quality goes). However, normalized unsigned formats are incapable of representing most rotations. Is this an spec bug, or is this by design?

~(separately, three.js and Babylon.js don't support non-FLOAT formats correctly, not sure if there are other implementations that do)~

**Comment by zeux** [comment]
Additionally, the description of animation output says "When targeting TRS target, the accessor.componentType of the output values must be FLOAT.", but the valid component types for quaternion list more types - so probably the spec should say "When targeting translations/scale target, the accessor.componentType of the output values must be FLOAT" instead?

**Comment by bghgary** [comment]
> normalized unsigned formats are incapable of representing most rotations. Is this an spec bug, or is this by design?

See https://github.com/KhronosGroup/glTF/pull/1136#discussion_r148049283

> the description of animation output

See https://github.com/KhronosGroup/glTF/issues/1183. It looks like we updated the schema without updating the property reference. The property reference is intended to be generated from the schema, but we haven't done it recently due to https://github.com/KhronosGroup/glTF/issues/1013.

I think for now, we can fix the property reference manually. @zeux Would you like to open a PR for this?

**Comment by bghgary** [comment]
> Babylon.js don't support non-FLOAT formats correctly

I've fixed the Babylon.js issue with non-float animation data. https://github.com/BabylonJS/Babylon.js/pull/6451

**Comment by zeux** [comment]
I will make a PR with a property reference update, thanks! I've also fixed the three.js issue (https://github.com/mrdoob/three.js/pull/16659) so we should be good.
