### ISSUE TITLE
No documentation on calculating global joint transformations

### ISSUE THREAD

**Issue by scgehin** [KhronosGroup/glTF#1630]
The quick reference sheet, specification readme, and tutorial all fail to mention how to calculate the global joint transformations. This has caused me a lot of trouble that could have been easily avoided.
The quick reference sheet only states "For each node whose index appears in the joints of the skin, a global transform matrix can be computed." This is extremely unhelpful. The other two resources I mentioned fail to mention the global joint transforms at all.
I'd greatly appreciate it if the quick reference sheet at the very least could explain how to calculate it properly.

**Comment by vpenades** [comment]
Calculating the global transform is a standard procedure.

Every node in the scene has a transform calculated using the rotation, translation and scaling of the node. This transform is sometimes called "the local transform"

The global transform of a node, also called "the world transform", is just the local transform of the node, multiplied by the world transform of its parent.

So essentially, a node has both a local and a world transform. The skinning system just states that you should use the world (global) transform of the node, not the local transform.

**Comment by scurest** [comment]
Cf #1035.

**Comment by javagl** [comment]
As vpenades mentioned above: The phrase "global transform of a node" basically means: "The product of all local transforms on the path between the root and the respective node" - that's also how it is explained in https://github.com/javagl/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_004_ScenesNodes.md#global-transforms-of-nodes (and in the quick reference sheet / overview).

---

Could a minor rewording solve the issue? :

> The **global transform** of a node is given by the product of all local transforms on the path from the root to the respective node

<sup>(In the nodes section, making it **bold** to make clear that this is a coined term)</sup>

...

> For each node whose index appears in the joints of the skin, <strike>a</strike> the **global transform** matrix can be computed

<sup>(In the skinning section, saying "the" instead of "a", and also making it **bold**)</sup>

Otherwise, it could be rephrased (in the overview and tutorial) to something like

> For each node whose index appears in the joints of the skin, the **global transform** matrix can be computed, as described in [link:] the section about Nodes

**Comment by javagl** [comment]
@scgehin The overview contains the statements

> "For each node whose index appears in the joints of the skin, a global transform matrix can be computed."

and

> "The global transform of a node is given by the product of all local transforms on the path from the root to the respective node."

Do you think that making the words "**global transform**" bold (and thus, making them a "coined term") could resolve the issue? 

Otherwise, any hints about how to resolve this issue would be appreciated.

**Comment by vpenades** [comment]
A global transform AKA world transform, is the matrix that transforms a mesh to world space.

A local, or relative, transform is the transform of a node relative to its parent node (if any).

Typically a scene graph node stores its local transform, and you calculate its world/global transform by concatenating the local transforms of every node down to the root node/scene.

@javagl these are very basic operations when dealing with scene graphs in 3D space, that is, converting from local to world and from world to local, and they're not specific of glTF, but a standard in the 3D industry, and available in pretty much every 3D format that has a scene graph. That's why I guess nobody considered adding documentation for it.

**Comment by javagl** [comment]
@vpenades  That was *roughly* what I thought, but I'd hesitate to close this issue **iff** there is something in the spec that should be clarified, or something in the overview that should be improved. But unless there is further activity, recommendations or comments, I'd close this issue soon.

**Comment by lexaknyazev** [comment]
Both global and joint-specific node transforms have been clarified in the AsciiDoc spec release.
