### ISSUE TITLE
License restrictions on vendor extensions

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/glTF#1641]
Hi there,

are there any requirements concerning the license of vendor extensions?
Moreover, is there any legal framework for the inclusion of vendor extensions?

Thanks in advance,,
Ludwig

**Comment by donmccurdy** [comment]
Author's GitHub account has been deleted, so I'll answer briefly and close this issue.

Vendor extensions may be used however the vendor sees fit. They don't have to be published or licensed at all, although we do encourage participation on GitHub so that everyone isn't doing the same things redundantly.

I'm not sure how to answer the second part of the question, because I'm not sure what "inclusion" of vendor extensions means. Inclusion in the core glTF specification? That would require a standardization process with IP ramifications, yes. Inclusion in a vendor's custom glTF file? That's totally fine.
