### ISSUE TITLE
Units: What should be meters: raw data or final transforms data?

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF#1725]
Hello,

I think there is a fuzziness in the specification that need to be clarified, about units.
Specification currently says:

> The units for all linear distances are meters

But what exactly must be in meters?

Taking an example:
I have a cube that visually is 2x2x2 meters, centred on the world.
This can be:

*  A mesh (min value of -1, max value of +1) expressed in meters, with a corresponding node without any scales. This is the case where raw data are in meters

* A mesh (min value of -1000, max value of +1000) expressed in millimeters, with a corresponding node with a scale (on the node or on one of the parents) of 0.001. This is the case where only the final result will be in meters.

Visually, the 2 cubes will 2x2x2, but this can lead to different results when the glb file is used by 3D Software (in case of procedural textures based on object texture coordinate).

Some part of specification where these 2 possibilities must/can have some consequences:
* Mesh instances: if raw data are not meters, every node that will instance the mesh need to take care of _scale_ value used to be sure to get back to meters

* Skinned Mesh: if raw data are not meters, because transforms on the node are ignored for skinned meshes, another node (a join node) must take care of the scaling to be sure to stick with meters.

* other?

My preferences goes heavily to have the raw data in meter to avoid all thse scaling checks/management to be sure to have a final result in meter.

**Comment by vpenades** [comment]
The final scene should be in meters, how you reach the final state of the model is up to you.

But in practice, nobody is paying attention to this requirement; in my daily experience, I'm finding all sorts of incorrect scales. Actually, roughly 75% of all the models I open from various sources are off scale.

So don't worry too much about it.

**Comment by julienduroure** [comment]
> But in practice, nobody is paying attention to this requirement; in my daily experience, I'm finding all sorts of incorrect scales. Actually, roughly 75% of all the models I open from various sources are off scale.
So don't worry too much about it.

I worry about it. In my daily experience, I need/must be aware of scaling used.
This is the aims of this specification to carry about it, and avoid any misunderstanding of data.

**Comment by vpenades** [comment]
Sure, I'm just saying that there's no way to validate a model to be in the correct scale, except by visual inspection, so authors are exporting glTFs with invalid scales all the time. 

In the end the solution we found is to make a tool to rescale models, since there's no way to guarantee before hand that models have correct scale.

**Comment by donmccurdy** [comment]
It's true that models in the wild can have very arbitrary scales, not least because they're often converted automatically from formats with looser (or no) real-world  units. Despite that, I do think the spec should at least be clear enough that users for whom exact units are necessary know what to do.

Two concerns with requiring raw data to reflect world units:

- incompatible with quantization (see draft: [KHR_mesh_quantization](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_mesh_quantization)), which formats raw data for minimum memory/transmission footprint and scales the node accordingly.
- many converters seem to wrap the whole scene in a 100x or 1/100x transform when coming from formats like FBX. I wish they'd scale raw data instead, but understand that's much harder when accounting for animation.

**Comment by emackey** [comment]
Also, imagine a case where a single mesh (with a single set of raw data) was referenced by multiple nodes in the scene, with different scale transformations on the different nodes.  For example, a single "crate" mesh used multiple times to make big and small crates in a stack of crates.

If the raw data scale were specified, it would never be appropriate to have multiple scalings of that data in the node tree.  It doesn't strike me as a reasonable thing to require.

**Comment by emackey** [comment]
Another example: In CesiumJS, a geospatial rendering framework, great care is taken to portray the Earth at actual scale (either as a WGS84 ellipsoid, or with terrain data on top).  Cities and buildings are rendered at actual size and expected to align with terrain.  The world units are meters in CesiumJS.  When you load a glTF file, all of the transformations are applied to the raw data, and the resulting transformed meshes are expected to be correctly sized in a meter-scale world.

@julienduroure If there's a particular use case where scaling of raw data is preferred, perhaps a glTF extension could indicate models where this is the case?  Or do I misunderstand the desire here?

**Comment by bhouston** [comment]
The final units after transformed into world space should be in meters.  If you want the internals to have non-annoying transforms (e.g. 1/100 scales, etc.) all the better but it should not be required.
