### ISSUE TITLE
question, how should the geometry be stored & structured in the binary buffer?

### ISSUE THREAD

**Issue by sebbekarlsson** [KhronosGroup/glTF#1727]
I am referring to what's being mentioned here: https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#binary-buffer

If one was to store geometry in this buffer, how should it be stored?
A list of vertices? matrices?

Thank you.

**Comment by javagl** [comment]
The question is a bit broad and unspecific. The tutorial shows [the buffer, bufferView, and accessor concepts](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_003_MinimalGltfFile.md#the-buffer-bufferview-and-accessor-concepts), with a pointer to the section where these are explained in more detail.

The **tl;dr** is:

- Indices and vertex attributes (like positions and normals) are defined using an `accessor`
- An `accessor` refers to a section of a `bufferView`
- A `bufferView` is a section of a `buffer`
- The `buffer` is the raw data that is stored as the "chunk 1" in the binary glTF

The section about buffers, bufferViews and accessors from the [glTF overview](https://github.com/javagl/gltfOverview/releases/download/v2.0.0b/gltfOverview-2.0.0b.pdf) (1 MB PDF file) may also be helpful here.

**Comment by sebbekarlsson** [comment]
@javagl  Thank you for your answer.

A "buffer" is also very unspecific.
From the PDF you linked, I can read that a buffer with the byte length of 35 is being mentioned.
I might be blind or something, but how exactly does this buffer contain geometry?

Do you have a code example? Preferably C. Thank you

**Comment by sebbekarlsson** [comment]
From the PDF:
> The chunkData contains the actual data of the chunk. This may be
the ASCII representation of the JSON data, or binary buffer data. 

So how is this binary buffer data structured?
How does it represent geometry?

**Comment by javagl** [comment]
My C is a bit rusty, to be honest. The best way of explaining it may also depend on whether you *have* geometry data and want to write it as a GLB, or whether you have a GLB and want to extrat the geometry data. 

But I'll try to convey some ideas. Imagine you have the full contents of a GLB file:

    unsigned char* binaryGltfFileContents = readFullGlbFile();

The structure of the data is shown in this image from the specification:

![Image0](https://raw.githubusercontent.com/KhronosGroup/glTF/master/specification/2.0/figures/glb2.png)

The actual geometry data is stored in "Chunk 1". So you can skip the header (12 bytes) and chunk 0 (which contains the JSON), to arrive at the beginning of chunk 1:

    unsigned char* geometryBuffer = binaryGltfFileContents  + 12 + chunkLength0;

Until now, this is only some dumb sequence of bytes. It might be geometry data, or indices, or animation data. You don't know that. In order to **interpret** this data, you have to use the information that is contained in the JSON part. Using the [TriangleWithoutIndices](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TriangleWithoutIndices) sample as an example, the JSON contains this information (simplified) : 

```
  "bufferViews" : [
    {
      "buffer" : 0,
      "byteOffset" : 0,
      "byteLength" : 36,
      ...
    }
  ],
  "accessors" : [
    {
      "bufferView" : 0,
      "byteOffset" : 0,
      "componentType" : 5126,
      "count" : 3,
      "type" : "VEC3",
       ...
    }
  ],
```
Imagine you have read the information from the JSON part, into some `structs`, so that you can access the properties like `bufferViews[0].byteOffset` or `accessors[0].count`. 

The information that is contained in the JSON part of the example tells you that the data in the `geometryBuffer` has the following layout:

![Image1](https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/TriangleWithoutIndices/screenshot/triangleWithoutIndices.png)

So in order to obtain the actual vertex positions, you can do the following:

    unsigned char* geometryBuffer = ...;
    unsigned char* attributesBufferView = geometryBuffer + bufferViews[0].byteOffset;
    unsigned char* positionsAccessor = attributesBufferView + accessors[0].byteOffset;

    // From the 'accessor' information in the JSON part, you know:
    // - The data type is GL_FLOAT, because of "componentType" : 5126
    // - The data represents 3D vectors, because of "type" : "VEC3",
    // - There are three 3D vectors, because of "count" : 3
    // So do the nasty casts:

    float* positions = (float*)positionsAccessor;

    // And access the data:
    float p0x = positions[0];
    float p0y = positions[1];
    float p0z = positions[2];

    float p1x = positions[3];
    float p1y = positions[4];
    float p1z = positions[5];

    float p2x = positions[6];
    float p2y = positions[7];
    float p2z = positions[8];

(Usually, you don't access the data at this level - in many cases, you're just sending it to the GPU via some OpenGL API calls - but the above is intended to get the idea across)

---

My guess about where the question comes from:

In other file formats, you often store geometry data in a "known form". For example, a file might contain a sequence of bytes, and the *specification* tells you something like "The first 36 bytes are actually a `float[3][3]`, which represent the vertex positions of a triangle". In glTF, this is not the case. The binary data that is stored in glTF can be everything: Vertex positions, indices, texture coordinates, animation keyframes... So you have to take a look at the JSON to figure out *what* the data actually means. (And if that sounds strange or overly complicated at the first glance, let's just say: There are reasons for doing it like that...)

**Comment by sebbekarlsson** [comment]
@javagl 
Thank you so much for this very detailed explanation!
I think I understand now.

There is no "specified" or "known" format of this binary buffer.
It entirely depends on what you put in it.

And yes, your guess was right.
This is exactly where my question came from, I thought it was a bit confusing since it lacked a proper
definition of what structure the buffer had.

Once again, thank you! This helped me to understand it.

**Comment by javagl** [comment]
Some time ago, we considered adding something in the [glTF-Tutorials](https://github.com/KhronosGroup/glTF-Tutorials) that focuses more on *implementation* issues. Something like a "minimal WebGL renderer that renders a (simple\*) glTF", or "the core lines of C/C++ code that show how the data from the buffer is supposed to be sent to OpenGL". 

\* : What is a "simple" glTF? That's the caveat: Such an example always will have to leave out some features - otherwise, it would be a dozen pages showing *one* way of implementing a glTF renderer (and *very* few people really want to do this "from scratch"). So the example could probably only show the parts that are related to the `buffer`/`bufferView`/`accessor` concepts, and not show the more sophisticated elements like PBR, animations or skinning...

---

However: Assuming that the core of the question is answered now, I'm closing this. Feel free to reopen it if there are follow-up questions.
