### ISSUE TITLE
Materials got swapped into weird places, exporting from blender in gltf or gltb format into godot engine.

### ISSUE THREAD

**Issue by KiNobeku** [KhronosGroup/glTF#1767]
I exported my model shown on the first picture of the link down below in gltf format from blender but once I imported into godot engine the materials wer swapped into weird places
[https://blender.stackexchange.com/questions/167734/wierd-textures-from-importing-gltf-file-from-blender-into-godot-need-help-fixi](url)
are there any fixes for this?

**Comment by donmccurdy** [comment]
@KiNobeku does your model look correct in other viewers, like these?

- https://gltf-viewer.donmccurdy.com/
- https://sandbox.babylonjs.com/

If so, I'd suggest filing a bug against Godot Engine. If not, you can report a bug on the Blender addon (https://github.com/KhronosGroup/glTF-Blender-IO). This repository is for the file format itself, rather than those programs, so I'll close this issue for now.
