### ISSUE TITLE
glTF camera with parent scale

### ISSUE THREAD

**Issue by bghgary** [KhronosGroup/glTF#1822]
A question come up recently with glTF camera with parent nodes that have scale. The [spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#cameras) doesn't explicitly say.

> Cameras are contained in nodes and thus can be transformed.

Do we expect the scale of parent nodes of a camera to affect the camera's matrix?

See these two thread for some context (first one is not completely glTF related, but good for context):
https://forum.babylonjs.com/t/camera-minz-and-maxz-do-not-work-properly-when-camera-parent-is-scaled/11267
https://forum.babylonjs.com/t/camera-animation-messed-up-using-gltf-from-blender/11426

**Comment by javagl** [comment]
It's hard to imagine how a scaling (particularly a non-uniform scaling) could be stirred together with things like the aspect ratio or the factors of an orthographic camera. Of course, the result can be expressed by some fairly trivial matrix math, but considering a scene graph like

    root
    |
    nonUniformScale
    |
    rotation
    |
    camera

When animating the rotation, the effects that this will have on the actual, rendered result are hard to imagine...

(The linked threads are quite technical, and refer to other viewers/libraries and best practices, so I probably cannot say anything profound here. I'm slightly leaning towards saying that the scaling should not affect the camera matrix due to the unpredictable results. But at the same time, scaling might be the only way to express certain kinds of "camera zoom animations" in glTF right now...)

**Comment by lexaknyazev** [comment]
Addressed in the AsciiDoc spec release.

**Comment by bghgary** [comment]
@lexaknyazev  It would be good if we can close issue with a reference to where the fix is, so that there is an answer linked to the issue.

Is this where it's addressed in the spec?

https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#view-matrix
> The view matrix is derived from the world transform of the node containing the camera with the scaling ignored.
