### ISSUE TITLE
Broken links in glTF Readme

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/glTF#1930]
The following links no longer lead to the intended resources:

- [How I got involved in glTF and Khronos](http://blog.virtualglobebook.com/2013/03/how-i-got-involved-in-gltf-and-khronos.html). Patrick Cozzi, WebGL Meetup. March 2013
- [Convert FBX format to glTF format on Blender and animate it with Three.js](https://ryo620.org/blog/2018/02/to-gltf-from-fbx-by-blender/) (Japanese) by Ryosuke Sakaki. February 2018

**Comment by javagl** [comment]
We could probably tag them, like **[Archived]** or so, and use the archive links at https://web.archive.org/web/20170507043518/http://blog.virtualglobebook.com/2013/03/how-i-got-involved-in-gltf-and-khronos.html or https://web.archive.org/web/20200423162535/https://ryo620.org/2018/02/to-gltf-from-fbx-by-blender/ (not sure whether the latter is the right one). Otherwise, they should probably just be removed.
