### ISSUE TITLE
When I import the file I exported, the shapes are broken.I observed the same problem in the blender shading part and godot?

### ISSUE THREAD

**Issue by mrParabol** [KhronosGroup/glTF#1976]
I exported my file as gltf in blender. When I import my file into the blender, the image is corrupted in the shading section.
blender version: 2.92
system: Manjaro

link to the gltf file I exported:
https://disk.yandex.com.tr/d/MueVWriNZVIJEQ

The blender file I imported from the gltf format(the blender file is in the zip file):
https://disk.yandex.com.tr/d/x8hhAAf1_02BNQ

my original model's blender file link:
https://disk.yandex.com.tr/d/KYjXfYHN6nxfIA

Note: I have the same problem when I import from godot.
link to my godot project:
https://disk.yandex.com.tr/d/0PDhCV7yLHOwBw

thanks for your help in advance.

**Comment by donmccurdy** [comment]
Hi @mrParabol — this repository is for the glTF file format specification. Blender and Godot are separate projects, and we can't provide support for them here. That being said,

1. The original `.blend` uses *Blend Mode: Alpha Hashed* on all (!) of its materials. The glTF format doesn't support that, and neither does Godot unless you write a custom shader for it. For any material that is fully opaque, be sure to use *Blend Mode: Opaque* instead.

![Screen Shot 2021-05-03 at 10 44 37 AM](https://user-images.githubusercontent.com/1848368/116912593-49503180-abfd-11eb-89e2-0d89d1af7120.png)

2. Since Blender can't export this mode to glTF, it chooses *Alpha Blend* instead. That's a reasonable choice for semi-transparent materials, but since most of this model is opaque, it causes a lot of further issues.

I would suggest using Alpha Blend for the semi-transparent fabric, Alpha Clip for the hair, and Opaque for everything else. There may be other ways to work around this in Godot, or the Blender stack exchange (https://blender.stackexchange.com/) is often helpful too.
