### ISSUE TITLE
Is there any alternatives to texture coordinates compatible with gltf

### ISSUE THREAD

**Issue by memoefe** [KhronosGroup/glTF#1985]
In the project I work on we use **texture coordinates** to apply our textures without distortion(i dont use uv's because I have over thousand objects and unwraping each of them would take eternity, also to create 'fake' reflections using reflection output.

Is there any alternatives in blender that i can use to get those effects with nodes that are compatible with gltf.

The gem with 'fake reflection', images move in it like it is a reflection. I need to recreate this in gltf.
![image](https://user-images.githubusercontent.com/84917169/119875677-b1a9de80-bf2f-11eb-9a5e-0ef3e7903016.png)

**Comment by donmccurdy** [comment]
Currently UV texture coordinates are required when using textures in glTF. I believe there are options to bake UVs in Blender, without manual unwrapping, so this doesn't necessarily have to take much time and can be automated. If there are alternatives to UVs that are both (1) supported in Blender, and (2) supported in realtime engines, perhaps something else could be proposed.

At the moment I think the closest proposal is https://github.com/KhronosGroup/glTF/issues/1889 (procedural textures) but it's a large proposal, and not finished or implemented anywhere yet.

For Blender-specific workarounds (i.e. to generate UVs efficiently or otherwise get the same effect) it may be best to use https://blender.stackexchange.com/ or https://blenderartists.org/.
