### ISSUE TITLE
EXT_mesh_gpu_instancing breaks even if the animation is on an unrelated object.

### ISSUE THREAD

**Issue by RenaudRohlinger** [KhronosGroup/glTF#1995]
Hello!

When using EXT_mesh_gpu_instancing if the export_animation setting is = 1 the EXT_mesh_gpu_instancing extension will throw "error: instance: Instancing is not currently supported for animated models." even if the animation is on an unrelated item (for example a camera).

Basic reproduction:
[untitled.blend.zip](https://github.com/KhronosGroup/glTF/files/6641887/untitled.blend.zip)

GLTF File result with export_animation:0
![image](https://user-images.githubusercontent.com/15867665/121770141-86b3c180-cba2-11eb-8752-75c17fbb690f.png)

GLTF File result with export_animation:1
![image](https://user-images.githubusercontent.com/15867665/121770159-a34ff980-cba2-11eb-9370-8d73b7a7f6d4.png)

**Comment by donmccurdy** [comment]
The error message you mention is from the glTF-Transform `instance()` function. As the message suggests, the implementation does not currently support applying `EXT_mesh_gpu_instancing` to models containing animation, and throws an error instead:

https://github.com/donmccurdy/glTF-Transform/blob/416f3085545f62daba70a5eb19b143f8ceecd5cb/packages/functions/src/instance.ts#L24-L26


This repository manages the glTF file format, and not any particular software package, so I'll close the issue here. But if you could share a `.glb` that you believe should support instancing, but doesn't currently, please feel free to open a feature request to remove this limitation at https://github.com/donmccurdy/glTF-Transform.

**Comment by RenaudRohlinger** [comment]
@donmccurdy Ok I understand. For the moment I added a new feature to this gltf addon that automatically detect and export all instance collections:
https://github.com/RenaudRohlinger/blender_gltf_scripts
