### ISSUE TITLE
In the 2.0 Specification Are Morph Targets going to contain the same Morphs OR can they contain different amounts within a Primitive??

### ISSUE THREAD

**Issue by genusistimelord** [KhronosGroup/glTF#2013]
Like for example if the first target is 

```
{
    "NORMAL": 33,
    "POSITION": 32,
    "TANGENT": 34
},
```
then will all other targets in the array be exactly the same Or can they contain anything within the Primitive?

**Comment by lexaknyazev** [comment]
Since a morph target contains attribute deltas, any omitted attributes should keep their base values provided by the `primitives[i].attributes` object.

Although the spec does not explicitly disallow per-target differences, it would good to ensure that implementations are fine with that.

@donmccurdy @bghgary @emackey

**Comment by bghgary** [comment]
Babylon.js implement should allow this. Will need a test model to be sure.

**Comment by genusistimelord** [comment]
Thank you for your Quick Reply. This has been very helpful.

I hope you will be able to Add this to the Read me Specification so others can know this =]!

**Comment by donmccurdy** [comment]
three.js:

- morph POSITION is required
- morph NORMAL is optional, and may be disabled when limited vertex attributes are available
- morph TANGENT is ignored entirely

I'm not sure what would happen if a morph target provided normals but not positions, this is probably not supported. morphing other attributes (e.g. color or UVs) is technically possible, but I don't believe any implementation exists.

Is there a real use case for morphing normals while not also morphing positions? or do you have in mind to provide normals for some targets but not others? I'm not sure what the clarification should be in this case.

**Comment by emackey** [comment]
Re-reading the original post in this issue, perhaps a concrete example would shed some light:

```
"primitives" : [
                {
                    "attributes" : {
                        "POSITION" : 0,
                        "NORMAL" : 1
                    },
                    "indices" : 3,
                    "targets" : [
                        {
                            "POSITION" : 4,
                            "NORMAL" : 5
                        },
                        {
                            "POSITION" : 6,
                        },
                        {
                            "POSITION" : 7,
                            "NORMAL" : 8
                        },
```

I did some quick testing with the `MorphStressTest` sample model, removing `NORMAL` from some of the morph targets in the second primitive.  The results are disastrous in several engines.

I recommend we disallow this, by saying that each of the morph targets in a given primitive MUST have the same attributes as the first.

**Comment by lexaknyazev** [comment]
Since morph targets are deltas, the "missing" attributes could be "fixed" by adding sparse accessors without buffer views (since they would be initialized to zeros). Given that such "fix" doesn't change the semantics of the asset and engines could do it on-load, I'd rather leave the spec as-is.

Regardless of the asset validity, an engine shouldn't throw shader compilation errors or read from uninitialized memory (typical reason of random geometry corruption).

**Comment by emackey** [comment]
I can understand this might be too strong a spec change given the current timing.  But I would consider different numbers of morph target attributes to be a "bad smell" in the model file, worthy of a glTF Validator warning at least, even if it's technically legal.
