### ISSUE TITLE
Trying to run wetzel on an extension schema throws warning, empty output

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/glTF#2109]
In converting the glTF 2.0 extensions to asciidoctor I'm trying to run wetzel on the corresponding schemas. Following how it's done for the 2.0 core spec schemas, it complains about "Unable to find $ref glTFProperty.schema.json" and generates an empty output file:

> $ cd extensions/2.0/Khronos/KHR_materials_specular  
> $ npx wetzel -n -a=cqo -m=a -p schema -e JsonSchemaReference.adoc -i '["gltfchildofrootproperty.schema.json", "gltfid.schema.json", "gltfproperty.schema.json"]' -c "icon:check[]" -k "\*\*MUST\*\*" schema/glTF.KHR_materials_specular.schema.json > PropertiesReference.adoc'  
> npx: installed 3 in 1.058s  
> Unable to find $ref glTFProperty.schema.json  
> $ wc PropertiesReference.adoc  
> 0 0 0 PropertiesReference.adoc

wetzel is a black box to me, so I'd appreciate guidance on how to get useful output for an extension schema.

**Comment by javagl** [comment]
<sup>One could consider to open this issue in the `wetzel` repo, because it is not strictly related to glTF itself</sup>

wetzel is a black box for me as well, but I had a short look at this: There is a `searchPath` option that may help to solve the immediate issue. It is documented as 

> The path string that should be used when loading the schema reference paths

and it seems to be possible to insert the path to the directory that contains the `glTFProperty.schema.json` file here.

Using the command that you showed caused the same output for me. But the following is the contents of a Windows BAT file that  worked:
```
node bin/wetzel.js ^
    -n -a=cqo -m=a ^
    -p "schema" ^
    -e "JsonSchemaReference.adoc" ^
    -i "['../../KhronosGroup/glTF/specification/2.0/schema/glTFChildOfRootProperty.schema.json', '../../KhronosGroup/glTF/specification/2.0/schema/glTFid.schema.json', '../../KhronosGroup/glTF/specification/2.0/schema/glTFProperty.schema.json']" ^
    -s "../../KhronosGroup/glTF/specification/2.0/schema/" ^
    -c "icon:check[]" ^
    -k "**MUST**" ^
    ../../KhronosGroup/glTF/extensions/2.0/Khronos/KHR_materials_specular/schema/glTF.KHR_materials_specular.schema.json > PropertiesReferenceMaterialsSpecular.adoc
```
*Important notes:*

- The `^` is the "line separator" on Windows. This corresponds to the `\` on Linux.
- The crucial line is the one that starts with `-s`, containing the path (on my local file system) that contains the `glTFProperty.schema.json`. 
- There was a bit of a hiccup with `'` and `"` for enclosing strings or arrays of strings or strings with arrays of strings - things might be different in Linux here - if it does not "just work" with the `"path"`, you might want to 'just try' it with `'path'` (using single quotes).

**Comment by oddhack** [comment]
@javagl thanks - this is working OK for me now.
