### ISSUE TITLE
Clarification needed: recommended way to compress time values when using EXT_meshopt_compression for animations

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/glTF#2119]
The section on meshopt contains hints for compressing rotation and position data, but doesn't contain information about how to pack the time values:
https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Vendor/EXT_meshopt_compression/README.md#compressing-animation-data

As I've come across files that use an "exponential" filter for time values (which results in broken animation due to the reduced time accuracy the longer the animation is) I think some clarification would be nice even if the section is non-normative.

cc @zeux 

For reference, https://github.com/donmccurdy/glTF-Transform/issues/489

**Comment by zeux** [comment]
gltfpack (which I'd recommend as the reference compressor for EXT_meshopt_compression) disables filters on the time track. When uniform sampling is used for animation, there's no real need for the filters - since the delta between the keyframe times is the same in floating point, due to the construction of floating point numbers even without filters the delta encoding is very efficient.

**Comment by donmccurdy** [comment]
Thanks @zeux! I will make the update in https://github.com/donmccurdy/glTF-Transform/pull/492. I had trouble finding all of the various cases in the gltfpack codebase and did guess on several; you can find my selections (before the 'input' fix) here:

https://github.com/donmccurdy/glTF-Transform/blob/a5dba5d9632d14a446db540f197c83b6305b2a12/packages/extensions/src/ext-meshopt-compression/encoder.ts#L135-L178

A table of suggestions may be helpful for the document I agree, but doesn't need to be normative.
