### ISSUE TITLE
Crash when scene contains a Bezier curve

### ISSUE THREAD

**Issue by KyleNBurke** [KhronosGroup/glTF#2160]
I'm using the 3.2 beta and if you simply add a Bezier curve to the scene then export the scene using the gltf exporter with the default configuration, blender will crash. This does not happen with 3.1.2.

The exact build is `blender-3.2.0-beta+v32.018acc568893-windows.amd64-release`.

**Comment by javagl** [comment]
This repository is for issues related to the glTF specification. From the description, it sounds like this issue is related to the Blender Plugin, and should be discussed in https://github.com/KhronosGroup/glTF-Blender-IO/issues . (Although it _might_ also be an issue of Blender itself, but that has to be analyzed). If you are opening it there: If there is any further information, like an exact error message or some sort of log/trace, then people would probably appreciate if this was included in the issue description.

**Comment by KyleNBurke** [comment]
Apologies, wrong repository.
