### ISSUE TITLE
why glTF forbid matrix for animations?

### ISSUE THREAD

**Issue by LeHibou2** [KhronosGroup/glTF#2173]
Hi,
May someone tell me why the spec forbids the use of matrices for animated elements in favor of separate TRS buffers?
Genuine question, really don't know the reason.

Isn't it better to have precomputed matrices to accelerate the process, even by a little?

Thanks,

**Comment by javagl** [comment]
A short pointer to a proposal for extensions that may allow animating other elements: https://github.com/KhronosGroup/glTF/pull/2147 

But animating matrices is really tricky. Even for a quaternion (i.e. the current `rotation`), one has to be careful to interpolate it _properly_: Instead of a plain, linear vector interpolation, one as to use a [slerp](https://en.wikipedia.org/wiki/Slerp). Interpolating matrices adds a whole new level of complexity. Imagine two matrices

    1,  0,  0,  0
    0, +1,  0,  0,
    0,  0,  1,  0,
    0,  0,  0,  1

and

    1,  0,  0,  0
    0, -1,  0,  0,
    0,  0,  1,  0,
    0,  0,  0,  1

What should be the state of interpolating between these matrices at t=0.5? The straightforward answer would be

    1,  0,  0,  0
    0,  0,  0,  0,
    0,  0,  1,  0,
    0,  0,  0,  1

Ouch - you got an all-zeros row there. Generally, the state of the matrix may be messed up arbitrarily (i.e. it may be non-invertible). At the very least, the interpolated state may not make sense _geometrically_.

There _are_ solutions for that. For example, http://mesh.brown.edu/DGP/pdfs/Alexa-sg2002.pdf - but that's far beyond what could reasonably be covered by a file format specification.

**Comment by LeHibou2** [comment]
@javagl aaah! I get it now, thanks Marco
