### ISSUE TITLE
KHR_mesh_quantization wrong description

### ISSUE THREAD

**Issue by fxxjdedd** [KhronosGroup/glTF#2237]
https://github.com/KhronosGroup/glTF/blob/9bbb8479e7a68d7733949e783e4b6b730cc7b557/extensions/2.0/Khronos/KHR_mesh_quantization/README.md?plain=1#L51

... using integer storage can reduce precision loss as ...

should be:

... using integer storage can cause precision loss as ...

**Comment by bghgary** [comment]
Would you like to contribute a PR with the change?

**Comment by scurest** [comment]
The sentence structure strongly suggests it does mean "can reduce precision loss" actually. It provides a benefit of normalizing (can avoid dequantization transform), then weighs it against a benefit of not normalizing (reduced precision loss).

Dequantizing non-normalized values is `n * Q`. Converting to normalized (u8) values means `(n / 255) * (Q * 255)`. Generally it's true those are not equal for all values of n because of float round off.

**Comment by lexaknyazev** [comment]
Yes, the original sentence is correct, although a bit confusing. It suggests that _unnormalized integer_ attribute storage combined with external transforms may have better precision.

**Comment by fxxjdedd** [comment]
Thanks, I now grasp the meaning of the sentence, changing it like this makes it easier for me to understand:

however, if the data is not in `[0..1]` or `[-1..1]` range, **it's better to use an unnormalized(integer) storage, so that precision loss can be reduced**, as standard glTF normalization factors such as `1/255` and `1/65535` are not representable exactly as floating-point numbers. 

----

But I still have a few questions:

1. In the gltf buffer, `componentType: byte normalized` is stored as bytes or normalized floats?

2. Is it because normalizing data within the range of [0,1] or [-1,1], is basically the same as dequantizing it, so we don't need to do it again?

3. In the second question, this "**optimization**" doesn't work for data outside the range of [0,1] or [-1,1], so dequantizing is necessary to reduce precision loss as well as use an unnormalized storage?

**Comment by donmccurdy** [comment]
> In the gltf buffer, componentType: byte normalized is stored as bytes or normalized floats?

The accessor stores "normalized integers". Borrowing the OpenGL definition, _"A Normalized Integer is an integer which is used to store a decimal floating point number."_ The accessor component type may be uint8, int8, uint16, or int16.



The original vertex attribute values may have any range. When creating a quantized asset, values should first be mapped to the [0,1] or [-1,1] range by some transformation, with the inverse of that transformation being applied to the node or texture transform as described in [Decoding Quantized Data](https://github.com/KhronosGroup/glTF/blob/9bbb8479e7a68d7733949e783e4b6b730cc7b557/extensions/2.0/Khronos/KHR_mesh_quantization/README.md#decoding-quantized-data). A loader can then display the asset without needing to know anything directly about the dequantization parameters. Dequantization occurs implicitly when applying the usual scene graph transforms and UV transforms.

If it would be helpful to see an example implementation, you can find one here:

https://github.com/donmccurdy/glTF-Transform/blob/be190a1141bc4b80b43395e87e7c7051f51b1ae2/packages/functions/src/quantize.ts#L95-L118

**Comment by zeux** [comment]
I think a better change would be to say "using unnormalized integers instead of normalized integers can reduce precision loss". In both cases, there's going to be precision loss due to quantization; however, normalized integers typically carry an extra precision loss of 0.5 ULP due to another decoding operation (normalization). In practice this is not very likely to matter compared to the quantization error.
