### ISSUE TITLE
Does the glTF support EXT_mesh_features  now?

### ISSUE THREAD

**Issue by insar-dev** [KhronosGroup/glTF#2239]
Does the glTF support EXT_mesh_features  now?

Thanks.

**Comment by javagl** [comment]
The `EXT_mesh_features` extension is currently only a pull request at https://github.com/KhronosGroup/glTF/pull/2082 


The pull request has not been merged yet, because it still has to be reviewed by a member of the Khronos Group. It is basically a _proposal_ for an extension. Vendors may choose to provide preliminary support for this extension in their applications. Clients may provide feedback in the pull request. It is still maked as a 'Draft', so it might still change (but it is very unlikely that there will be _significant_ changes).

(And of course, the extension is not _ratified_, but that's a high, formal hurdle that is not even considered for this extension for now)
