### ISSUE TITLE
CBOR as a recognized gltf format?

### ISSUE THREAD

**Issue by kion-dgl** [KhronosGroup/glTF#2319]
CBOR is a new standard from the IETF: https://www.rfc-editor.org/rfc/rfc8949.html

It allows for encoding and decoding of objects with the binary representation intact, without having to use base64. In this case it's the size of GLB, with the convenience of GLTF embedded.

I wrote a small sample over here: https://github.com/kion-dgl/three-cbor-loader with the live version here: https://kion-dgl.github.io/three-cbor-loader/ as a small proof of concept. A CBOR model can be parsed with minimal changes to existing GLTF loader. 

![Screenshot 2023-09-05 at 05-11-09 CBOR Loader](https://github.com/KhronosGroup/glTF/assets/25621780/f3e3b65c-761b-444f-8471-db64ec9355b2)

**Comment by donmccurdy** [comment]
/cc https://github.com/KhronosGroup/glTF/issues/2321#issuecomment-1711829469

Aside – I continue to feel that "glTF Embedded" is a problem in the ecosystem, and would like to see this option removed entirely from tools like Blender. Self-contained GLB, or glTF with external resources, are sufficient options for every use case I've encountered (speaking as a three.js maintainer).

**Comment by javagl** [comment]
> with the convenience of GLTF embedded.

+ 

> "glTF Embedded" is a problem in the ecosystem

The only aspect of "convenience" is that it is easily human-readable, and ... this seems to be lost with CBOR, as far as I see.
The main use of embedded glTF (for me) was always that of creating "simple demo assets" - specifically, assets without textures. 

---
Yes, at that point, one could argue that _fully_ inlined JSON, like
```
"meshes" : [ {
  "primitives" : [ {
    "attributes" : {
      "POSITION" : [ 1.0, 2.0, 3.0, ... ]
    }
  }
}
```
would even be simpler than the `attribute->accessor->bufferView->buffer->base64-string` path (and one could even make the point that this would be more compact than the base64 encoded buffer in nearly _all_ cases!), but such "fully inlined JSON" that was never the goal.

**Comment by OR13** [comment]
I'm not a domain expert to speak to the application but the general benefits on CBOR are:

1. conceptual closeness to JSON (Maps, Lists, Scalars + Buffers).
2. JOSE / COSE closeness for signing and encryption
3. CBOR Diagnostic is meant to help with readability
4. Another place you see CBOR show up is constrained environments, not sure if that is relevant to this topic.

Sounds like the embedded representation is where CBOR would have helped most (because JSON does not handle binary well), and the recommended approach is to not use embedded format?

Are there  scenarios where the max json depth or document size blocks use cases?

Is there a gltf form other than embedded that would be worth semantic compression as opposed to generic compression?

**Comment by donmccurdy** [comment]
I view this as an area that needs to be approached with a clearly-defined problem, rather than with a solution.

In general, the JSON content in glTF is a _small_ chunk of metadata defining offsets into a larger, separate binary chunk. The binary chunk is carefully structured so that particular sections of it can be uploaded directly to the GPU.

While it's possible to contrive glTF files where JSON is a limiting factor, for the defined goals of the format — transmission to runtime — such files will have deeper challenges, like high node graph sizes or GPU draw call counts, which changes to serialization cannot address. Handling this scale requires other considerations — formats wrapping glTF, like 3D Tiles, are a good example here.

The recommended approach is to use `.glb` when a self-contained file is required, and `.gltf` with external buffers and textures where external resources are preferred. In both cases, base64 is avoided entirely.

**Comment by kion-dgl** [comment]
> The recommended approach is to use .glb when a self-contained file is required, and .gltf with external buffers and textures where external resources are preferred. In both cases, base64 is avoided entirely.

I think the design here is different from what the standard is providing. I mostly wanted to get it on the radar that it can be applied. I'm okay to close this issue.
