### ISSUE TITLE
glTF should specify more aspects of assets

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/glTF#24]
just copyright is not enough, in many COLLADA files we get the autoring_tool. We should probably propagate this information.
We should also gave a property to specify which converter is being used to produce a given glTF asset.

Putting for the record other Patrick thoughts here:
   * _Also need url for copyright image?_
* _COLLADA2JSON_
   * _Create `asset.copyright` from COLLADA author and copyright?_. <Fabrice +1 for that>
   * _Convert COLLADA geographic_location.  glTF uses radians, not degrees._
   * _Convert kml/kmz location to geographic_location.  Convert kml/kmz orientation and scale to a transform._

**Comment by pjcozzi** [comment]
I suggest we close this for the draft 1.0 spec.

**Comment by pjcozzi** [comment]
No additional schema update needed for 1.0.  See https://github.com/KhronosGroup/glTF/blob/spec-1.0/specification/schema/asset.schema.json

**Comment by tpendergrass** [comment]
I believe you dropped an element of the initial argument: "Convert kml/kmz orientation and scale to a transform." I'm using GIS software to convert shapefiles into buildings for CesiumJS. Unfortunately, when exporting the model, the software places the unit scaling in the kml instead of creating properly scaled geometry. Seeing as kml/kmz and collada are such close format friends, I feel it's worth accounting for the Scale factor at least.

**Comment by pjcozzi** [comment]
@tpendergrass the glTF asset should always be in meters, which is also what Cesium expects.  If you think there is a bug in COLLADA2GLTF or Cesium, please submit a bug in the corresponding repo with sample data.
