### ISSUE TITLE
Clarify anisotropy usage

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#2407]
The extension says:
> All meshes with materials that use anisotropy **SHOULD** supply `TANGENT` vectors as a mesh attribute. If `TANGENT` vectors are not supplied for such a mesh, the mesh **MUST** supply a `normalTexture`, and tangents are computed according to rules in the [Meshes section](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#meshes) of the glTF specification. Likewise when `TANGENT` vectors are not supplied for a mesh, the mesh **MUST NOT** supply different texture coordinates on the `normalTexture` and `anisotropyTexture`.

This section should have more details, specifically answering the following questions:
1. It's clear that two sets of tangent vectors are unwanted hence the requirement to not use two separate texture coordinate sets for normal and anisotropy textures. But why cannot anisotropy texture coordinates be used for tangent space derivation when a normal texture is not present?
2. What rules apply to the tangent space (and why) when an anisotropy texture is not present? Another section of the extension spec defines that texture sampling returns a constant value in this case; it clearly does not have any texture coordinates.

**Comment by emackey** [comment]
We talked about these questions during PBR TSG today, and @lexaknyazev was present.  But for everyone else, I'll try to summarize here:

Generally, tangent space should be defined by supplied `TANGENT` vectors for best visual results, and when that's the case, the `TEXCOORD_0` values for any and all texturemaps become irrelevant.  In the absence of `TANGENT`, we allow tangents to be derived automatically from the `TEXCOORD_0` values of `normalTexture` because that's the only other valid source of TBN matrices per fragment in the core spec, but visually, this does not look nearly as good.  When this was first released we decided to deliberately disallow additional fallback behaviors, as they not only look bad but would place additional burdens on implementations to compute TBN matrices from previously unknown sources.  Also, implementations should not be asked to compute more than one TBN matrix per fragment.

This means that tangent vectors come only from (a) the mesh attribute `TANGENT`, or as a fallback (b) the `TEXCOORD_0` of `normalTexture`, and no where else.  One of the two is always required for any material using `KHR_materials_anisotropy`, and the normative language declares it so.

Separately, the tangents and bitangents may be rotated in the surface plane (the UV plane) by a pair of 2D vectors: One supplied by the `anisotropyRotation` JSON, the other supplied per pixel in `anisotropyTexture`.  In both cases the 2D vector of `+X` is the identity vector, indicating no rotation.  The two rotations stack together.  The default sample value for `anisotropyTexture` is the encoded version of `(1.0, 0.0)` (which encodes to `(1.0, 0.5)` due to the lack of negative numbers in texels) and yields no rotation.

But note: The `anisotropyTexture` uses `TEXCOORD_0` to assign placement of its values on the 3D model, but never to assign orientation of tangent vectors themselves.  The placement of the tangent vectors is guaranteed by the requirement to always supply either mesh attribute `TANGENT` or a `normalTexture` with a `TEXCOORD_0`.

Thus, a default "color" may be given as the default sample value of a non-existent `anisotropyTexture`. You don't need to know where it applies: It applies everywhere on the mesh using this extension.  There's no need for a default `TEXCOORD_0` value to go along with the default color for this input.

**Comment by lexaknyazev** [comment]
Revisiting the current language reveals a logical inconsistency.

If `TANGENT` data is present:
- The tangent space is defined with mesh attributes.
- A normal texture may have any UV index.
- An anisotropy extension may be used.
- An anisotropy texture **may have any UV index**.

If `TANGENT` data is not present but a normal texture is present:
- The tangent space is generated from vertex positions, vertex normals, and UVs associated with the normal texture.
- A normal texture still may have any UV index.
- An anisotropy extension may be used.
- An anisotropy texture **must have the same UV index as the normal texture**.

---

Tying the "same UV" requirement to the tangent space origin makes little sense from the point of "do not have two tangent space definitions", so we should either drop it entirely or always require it.

**Comment by emackey** [comment]
I think this might have been... intentional?

In the case where the `TANGENT` attribute exists, it definitively establishes tangent space for use both by normal mapping (if present) and anisotropy (if present) regardless of any UV coordinates on any texturemap in the material.  The normal map and its coordinates may be entirely absent and the anisotropy will work fine without it in this case, with or without any anisotropyTexture.  Or both could be present using different UV sets, I suppose.  The latter situation would be a little weird because presumably the `TANGENT` attribute came from only one of the two sets.

When `TANGENT` is missing from the mesh attributes, things get stickier.  We require the normal map to exist, and we generate tangent space from the normal map's UVs, because this is the only other core source of tangent space and we can't have two sources. In this situation, if the anisotropy texture happens to also be present, it would seem very odd to have it use a different UV set from the normal map.  I suppose mathematically, there's no reason to require it to use the same set, if we're clear that using an alternate set does not change the definition of tangent space.  But allowing this would permit assets to get into some fairly unorthodox territory here, intentionally mismatching tangents and UV spaces.  I'm more comfortable with the thought that when the normal map is relied upon to generate tangent space, the anisotropy texture (if it exists) must use the same UV set as the normal map, for everyone's sanity.

**Comment by lexaknyazev** [comment]
When a fragment shader is executing, what's the difference between:

> Or both could be present using different UV sets, I suppose. The latter situation would be a little weird 

and 

> But allowing this would permit assets to get into some fairly unorthodox territory here

?

---

If an engine correctly handles the "little weird" case, it should be able to handle the "fairly unorthodox territory" as well.

**Comment by emackey** [comment]
You're correct, a fragment shader would have no problem with either scenario.

I think the requirement is geared more towards users of glTF.  If both maps exist and they've gotten themselves into either situation, they likely have done something wrong or unintentional.  But, perhaps the normative requirement is overkill.

**Comment by lexaknyazev** [comment]
If non-matching UVs are "wrong or unintentional", they should be disallowed (or warned about) regardless of the tangent space. On the other hand, if it's a (sometimes) reasonable setup, it should not be invalid. Engines that already support multiple UVs likely don't care about that rule anyway.

**Comment by emackey** [comment]
The catch here is that even when `TANGENT` is supplied, there's a strong likelihood that the tangent vectors were originally created from some kind of UV map.  Particularly in the case where a normal texture is present, it wouldn't make much sense for the `TANGENT` attribute to be completely uncorrelated to the normals.  Most likely, the DCC tool or glTF exporter calculated the tangent attribute using the UV coordinates.  When could this not be the case, I wonder.  Perhaps part of the normal map is left-handed and another part is right-handed, so the tangents are flipped for the left-handed part?  Or perhaps some of the tangent/bitangent values have been rotated for some reason, and the tangent attributes are rotated the opposite way for that part?  Even in these hypothetical cases, the actual texel colors in the normal map need to end up physically near vertices with tangent vectors that agree and cooperate well with those texels.  The normal map's UV atlas and the tangent vectors are inextricably linked, even when they're supplied separately.

The same is basically true of the anisotropy texture.  The colors in that texture are used for rotating tangent space, so those texels need to end up on the mesh in the vicinity of the tangent space they're attempting to rotate.  So there's implied cooperation there as well, between the mesh attribute and the selected UVs.

We only have one `TANGENT` mesh attribute (and no engine wants separate `TANGENT_0`, `TANGENT_1` kind of attributes, because that would mean multiple TBNs per fragment).  So when both maps are present, we think they're probably both related to `TANGENT`.  Even if an engine supports multiple UVs, we don't expect two different sets of UVs to be associated with the same tangent attribute.  It would be very hard for such a setup to have any self-consistency.

**Comment by emackey** [comment]
But you're right, the shader math doesn't care.  Perhaps we just make it clear where tangent space comes from, and let the users decide for themselves what UV maps they wish to select.

**Comment by lexaknyazev** [comment]
So the plan is:
- Rephrase the anisotropy spec so that it requires a defined tangent space using only the base spec terms. Mesh primitives that do not have a tangent space are incompatible with the anisotropy materials. This is purely an editorial change.
- Allow mismatched UVs with a portability warning. Although technically breaking, this seems fair to me because fully implementing the current spec requires more work on the engine side than relying on generic support for multiple UVs.
