### ISSUE TITLE
KHR_texture_transform offset calculation

### ISSUE THREAD

**Issue by tagopinath** [KhronosGroup/glTF#2450]
Hello,

I am writing gltf exporter which will export mesh and texture details from 3ds max. 
all mesh and textures and exported fine and checked in viewer looks fine also.
problem is, the scale, offset and rotation applied is not showing properly.

so, i used KHR_texture_transform to set the scale, offset and rotation. i am getting the values from 3ds max and passing the same, but the results are not coming as same. Means, whatever i see in 3ds max scene, is not same as in viewer. 
i checked in blender by exporting with scale value (only), but this change in scale value is affecting offset also (even though offset is set as 0,0 in blender.

This is the value entered in 3ds max 
![image](https://github.com/user-attachments/assets/03c187fa-daee-4699-bfe9-eeba2384297f)

This is the value entered in Blender
![image](https://github.com/user-attachments/assets/65ee3a23-489c-4ada-9ced-7dbe03199b5b)

Gltf exported file - left is from Blender, right is from my exporter
![image](https://github.com/user-attachments/assets/78c3161d-4c07-458c-8f24-044f2a9db1df)

does anyone know about how the calculation is done before export ? what is the formula?

Regards,
Gopi.

**Comment by javagl** [comment]
On the one hand, this is not the right repository for this question. On the other hand, the answer is https://github.com/KhronosGroup/glTF-Blender-IO/blob/0b872b618ff0e5a94a5d4e2ab1f2d58051c89a3e/addons/io_scene_gltf2/blender/com/conversion.py#L57 , and unless we have to talk about "Why is it implemented like that?", this link may be sufficient...

**Comment by tagopinath** [comment]
Thank you for the link, 
will try and update you.

Regards,
Gopi.

**Comment by javagl** [comment]
One still has to know the _exact_ meaning of the parameters _within_ the respective application. For example, there's that "Use Real-World Scale" check box in the UI. What does it do, on a mathematical level? (_Theoretically_ , it might be that an application that has parameters that are called 'offset' and 'scale', but, for some reason, applies them via a matrix that is computed from `scale * offset` instead of `offset * scale`. That's likely not the case here, but ... one has to be careful...)

There have been a few discussions about details of `KHR_texture_transform`. Maybe https://github.com/KhronosGroup/glTF/issues/1563 and related issues can make the picture clearer.

**Comment by tagopinath** [comment]
Hi,

https://github.com/KhronosGroup/glTF-Blender-IO/blob/0b872b618ff0e5a94a5d4e2ab1f2d58051c89a3e/addons/io_scene_gltf2/blender/com/conversion.py#L57
Using this calculation, i am able to see proper transform if i change only scale value.

but, if i change offset and rotation along with scale, then its not coming properly

left is from 3ds max, right is after exported and loaded in gltf viewer
![image](https://github.com/user-attachments/assets/a2e84ff2-97b2-4041-81ff-5148c4dd00f1)

i import the same gltf file into Blender, i can see the same values which i added in 3ds max

![image](https://github.com/user-attachments/assets/ef1fd8bb-ea17-4a8d-b056-a7b1480f9a03)

and here is my code for calculation 
![image](https://github.com/user-attachments/assets/40111eae-e70e-47cd-81fd-53b0a669984c)

and exported gltf file

![image](https://github.com/user-attachments/assets/2c2de5aa-646e-4b01-9aac-20d483970c18)

anything else i am missing ?

Regards,
Gopi.

**Comment by javagl** [comment]
It's hard to make guesses about what might be wrong here. 

But a few debugging hints:

One could consider to use values that have a known meaning. Export the scene...
- with offset=(0,0), scale=(1,1)
- with offset=(0,0), scale=(2,2)
- with offset=(1,1), scale=(1,1)
- with offset=(1,1), scale=(2,2)
and **see** what the results are.

This could be done with a unit square (0,0,0)-(1,1,0), that has texture coordinates (0,0)-(1,1), and a texture like this...

![testTexture](https://github.com/user-attachments/assets/a1a10580-7ec5-4209-a67d-e9c0e9c9f8a1)

From the screenshots, it's not even clear what the texture is _supposed_ to look like. Screenshots of code and JSON are not so useful either...

**Comment by javagl** [comment]
Unless there are specific requests for clarifications in the [`KHR_texture_transform`](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_texture_transform) extension, I assume that this issue can be closed. (Some specific discussion could probably happen in the repos of the respective authoring tool, or here if it is still related to the interpretation of the specification itself. But otherwise, there is not really an "actionable item" here...)
