### ISSUE TITLE
Bug: aspectRatio vs. aspect_ratio

### ISSUE THREAD

**Issue by bernstein** [KhronosGroup/glTF#343]
The spec for perspective cameras uses "aspectRatio" but the converter writes out "aspect_ratio".

glTF/specification/cameraPerspective.schema.json  uses "aspectRatio"

glTF/converter/COLLADA2GLTF/COLLADA2GLTFWriter.cpp uses "aspect_ratio"

**Comment by pjcozzi** [comment]
Thanks for the report, @bernstein.

The spec is correct and consistent with the glTF naming convention.  Looks like a converter bug, @fabrobinet.

**Comment by fabrobinet** [comment]
indeed, good catch.

**Comment by pjcozzi** [comment]
The spec and converter are in-sync in the 1.0 branch.

**Comment by pjcozzi** [comment]
This was updated.  Thanks for the report, @bernstein.

**Comment by MarcoHutter** [comment]
Are there any considerations to update the sample models accordingly? I stumbled over https://github.com/KhronosGroup/glTF/blob/master/sampleModels/duck/glTF/duck.gltf#L99 recently. I'm not sure whether this will be fixed in the current repo (in view of https://github.com/KhronosGroup/glTF/issues/502 ). But it's a bit unfortunate that the sample models can not be parsed with a spec-compliant parser (and I wonder how many non-compliant parsers are currently being written based on the fact that it's called `aspect_ratio` in the sample...)

**Comment by pjcozzi** [comment]
@MarcoHutter yes, the sample models will be updated as part of #556.  Let us know if you run into any other issues with them.
