### ISSUE TITLE
collada2gltf.exe converter problem, creating a single gltf file?

### ISSUE THREAD

**Issue by yaozhihang** [KhronosGroup/glTF#355]
Hello,

I'm trying to convert my collada file to gltf file using the opensource tool collada2gltf.exe, which is downloaded from the website (https://github.com/KhronosGroup/glTF/wiki/Converter-builds)

During my test, after converting the dae file, several seperated files (gltf, glsf, bin) have been created. My question is how to create only a single gltf file, which should be similar to the converted gltf file using the online tool (https://cesiumjs.org/convertmodel.html).

thanks and best regards

Zhihang

**Comment by rap2363** [comment]
I'm not sure if you've figured out how to handle this correctly, but I use a workaround to deal with just one gltf. You can compress the output .bin and .glsl shader files (I use base64 compression) and then append the string as a data uri on the appropriate keys in your gltf json.

I think the schema for the .bin buffers is: 
"uri": "data:application/octet-stream;base64"+compressedBase64String

And for the glsl shaders:
"uri": "data:text/plain;base64"+compressedBase64String

There may also be a flag on the collada2gltf command line tool you can set to compress these and set them in the gltf automatically, but I can't seem to find any option like that, so you may have to do the compression yourself.

Hope this helps,
Rohan

**Comment by tfili** [comment]
The -e option should embed these other files as data URIs.

**Comment by lovesmall** [comment]
The -e option works for me.

**Comment by chiliblast** [comment]
I cannot see the option -e for collada2gltf.exe

Also can you please explain a bit about How to:

-----------------------------------------
compress the output .bin and .glsl shader files (I use base64 compression) and then append the string as a data uri on the appropriate keys in your gltf json

and 

schema for the .bin buffers is: 
"uri": "data:application/octet-stream;base64"+compressedBase64String

And for the glsl shaders:
"uri": "data:text/plain;base64"+compressedBase64String
-----------------------------------------------

Do I need to compress both files in same zip? What would be the name of zip? Where to write the schema? Why I don't see the option -e for collada2gltf.exe?

**Comment by lovesmall** [comment]
I'm using mac, so I ran command: 

`/path/to/collada2gltf -f /path/to/input.dae -o /path/to/output.gltf -e`

For the compression, the options available are:

-c -> compression type: available: Open3DGC [string]
-m -> compression mode: for Open3DGC can be "ascii"(default) or "binary" [string]

Sorry I don't know about append the data URI.

**Comment by rap2363** [comment]
You can use Python's base64 module to encode a file you read into base64: https://docs.python.org/2/library/base64.html

For example, if you run collada2gltf on example.dae, you'll get:
example.gltf, example.bin, exampleVS.glsl, exampleFS.glsl, which are the gltf, binary buffer, vertex shader, and fragment shader files respectively.

If you open the example.gltf JSON file, you'll see the "uri": keys filled in with references to the .bin and .glsl files. The point of the base64 compression is that you can store the data directly onto these keys, rather than references to the external files (so you can have one gltf with all the information rather than 4 different files).

Run base64 encoding on the example.bin and pipe the output of your encoding as a string on the"uri" key:
"uri": "data:application/octet-stream;base64"+compressedBase64String

Do the same for the fragment and vertex shaders.

**Comment by chiliblast** [comment]
I think the .exe for windows is not upto date. 
I am stuck. I have downloaded https://github.com/KhronosGroup/glTF/ and cmake.exe. I have visual studio 10, but compiler does give errors. Can you please send me new .exe for offline converter for windows.
Thanks

**Comment by emackey** [comment]
@tfili I just tried the `-e` option, and it works, but it's not listed in the help text.

**Comment by tfili** [comment]
Thanks @emackey.

@chiliblast Did you try using the `-e` option or did you just not see it in the help text?

**Comment by chiliblast** [comment]
I have tried -e option and it says no such option. please send me your exe

**Comment by chiliblast** [comment]
I have just downloaded from https://github.com/KhronosGroup/glTF/wiki/Converter-builds
V0.8: SHA1: df4892809111a8c6dbff4fab6c386a24745d344e 

for Windows.

When I run, it says msvcp120.dll is missing. I downloaded it.

Now when I run .exe, application does run.

option -e does not work

**Comment by tfili** [comment]
@chiliblast I just ran the v0.8 build that you were using and running `collada2gltf.exe -e -f <filename>` seems to work fine for me. As you can see from this
![ss](https://cloud.githubusercontent.com/assets/1652382/6966302/073c94b0-d926-11e4-9ad5-13b8482bd65d.png)

With `-e` it will always use data URIs for shaders and the .bin file, but it will only embed textures if it can find them, otherwise it will just include the path as is from the COLLADA file. Could that be your issue?

Regardless it was an old build. I have added the most recent master to https://github.com/KhronosGroup/glTF/wiki/Converter-builds for Windows. I'm waiting to get a Mac build before I make this the only download for v0.8. This version also contains the runtime dlls that you need.

**Comment by chiliblast** [comment]
It works now :) Thanks

**Comment by emackey** [comment]
Lack of `-e` in help text is documented in #310.
