### ISSUE TITLE
Having a single light referenced by multiple nodes doesn't work

### ISSUE THREAD

**Issue by tfili** [KhronosGroup/glTF#446]
Trying to use the same light positioned with multiple nodes doesn't work (Think directional light used as car headlights).

We'll probably have to duplicate techniques to do this.

**Comment by pjcozzi** [comment]
The issue is that `node` is only defined for a `technique` parameter, not for `material` parameter.  However, `material.parameter` would have to be changed from number/array/string to an object to support this.  This creates another level of indirection that I don't think is warranted for this corner case, but can be considered post 1.0 based on community feedback.

**Comment by tparisi** [comment]
Sounds like an edge case and I bet we can work around it anyway. Post-1.0 please

**Comment by pjcozzi** [comment]
Moved discussion to https://github.com/KhronosGroup/glTF/issues/945#issuecomment-353753859
