### ISSUE TITLE
glTF wikipedia page

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#56]

**Comment by pjcozzi** [comment]
I am surprised that there is not yet a wikipedia page for glTF.  Does anyone want to take the lead on this?

**Comment by javagl** [comment]
For the case you haven't seen it yet: Someone started it at https://en.wikipedia.org/wiki/GlTF

**Comment by emadurandal** [comment]
Good news that glTF page was posted on Wikipedia.

(It's less important that my library glboost is not on the list in the article. lol. 😂 I'm convinced that because it is still immature.)

BTW, I'm trying to write a detailed introduction article about glTF for Japan. (Perhaps it will be the most detailed, voluminous one in the past Japanese articles.)
This is WIP page: http://qiita.com/emadurandal/private/1a034c4addd7ff8b5184
The final volume of sentences is expected to be at least three times the current state (November 18, 2016).

I hope to become an (unauthorized) evangelist of glTF in Japan :)

**Comment by pjcozzi** [comment]
The wikipedia page was started by @Khronoswebmaster.  Everyone is welcome to contribute.  Please edit away!

> BTW, I'm trying to write a detailed introduction article about glTF for Japan.

@emadurandal once it is ready, please open a PR to add a link to it from https://github.com/KhronosGroup/glTF#presentations-and-articles

> I hope to become an (unauthorized) evangelist of glTF in Japan :)

Sounds great, do it!

**Comment by emadurandal** [comment]
@pjcozzi Thank you. I will! 😄

**Comment by javagl** [comment]
> The wikipedia page was started by Khronoswebmaster.

I had looked at the history and wondered who "Plattapuss" was - now I know. 

@emadurandal (Slightly off-topic) You might also be interested in the current state of the https://github.com/javagl/glTF-Tutorials/tree/master/gltfTutorial . The corresponding pull request into the Khronos repo is still pending, as there currently is a refactoring in progress, based on the feedback and first comments (I'll continue with this during the weekend). But maybe you want to have a look at it nevertheless. 
(And... thanks for the (according to Google Translate) kind words about JglTF, even though it's also still in an early WIP state)

**Comment by Khronoswebmaster** [comment]
> I had looked at the history and wondered who "Plattapuss" was - now I know.

A nickname from another life, which lives on in Wikipedia.

**Comment by pjcozzi** [comment]
Good discussion here.

I'm going to close this issue; I updated #456 to include encouraging folks to contribute to the Wikipedia page.
