### ISSUE TITLE
gltf handling of Collada animation incorrect

### ISSUE THREAD

**Issue by ryanbartley** [KhronosGroup/glTF#580]
Hi there,

I'm having a problem converting a collada file to gltf and retaining the animation keyframes correctly. I may be mistaken in how I imagine the data to show up. Basically, I've created a simple animation in Blender from Baked physics. When looking at the .dae file on my Mac, everything looks correct (I've attached the [.dae](https://github.com/KhronosGroup/glTF/files/237566/test.dae.zip)). However, as soon as I convert the file to gltf things get weird. Many of the animation objects are mostly null and the animation is separated from it's original target. I've also tried the online drag and drop version of Collada to glTF (I've also attached the [.glb](https://github.com/KhronosGroup/glTF/files/237564/test.glb.zip)) and what it presents is totally incorrect. I'm not sure if I should be exporting the animation differently but this problem also happened similarly with a Cinema4d collada file. Any help in correcting this or pointers on where to look would be greatly appreciated!

**Comment by lasalvavida** [comment]
DAE:
![coindrop](https://cloud.githubusercontent.com/assets/2489570/14853320/0bd21f10-0c59-11e6-8e86-765b7de77a0b.gif)

glTF:
![coindrop-cesium](https://cloud.githubusercontent.com/assets/2489570/14853332/187ea0c6-0c59-11e6-97ca-0fec907c0dc5.gif)

**Comment by lasalvavida** [comment]
@ryanbartley, it looks like this issue is caused by multiple animations with same target; definitely a bug in collada2gltf

**Comment by pjcozzi** [comment]
@lasalvavida can you see how involved the fix would be and make it if it is reasonable?

**Comment by lasalvavida** [comment]
@pjcozzi I had started digging a little bit on this last week, and I'm not definitely sure yet what causes this issue; I'll keep looking into it.

Either the animations aren't being flattened together correctly, or the values are just being read incorrectly from the collada file, and I'm not sure which yet.

**Comment by ryanbartley** [comment]
Wondering if you, @pjcozzi @lasalvavida, could point me in the direction of where the animation engine is translated in Collada2gltf. I may have some cycles to take a look at possible solutions and definitely want to solve this before releasing my personal gltf engine.

**Comment by lasalvavida** [comment]
@ryanbartley, COLLADA2GLTF attempts to flatten out animations where possible and that ends up being the reason why this (and other animation models) fail the conversion. COLLADA treats transforms as a set of stages and animations target a specific stage of that transform pipeline. Currently, COLLADA2GLTF does preserve nodes targeted by animation, but it flattens out all of the ones in between which creates a different transform from the desired one.

Unfortunately, with the way OpenCOLLADA splits up awareness of animation targets, this ends up being difficult to handle correctly.

Take a look at `COLLADA2GLTFWriter.writeNode` and `animationConverter.writeAnimation` if you want to take a crack at this.

I also have a decent writeup of this issue in #551.

**Comment by ryanbartley** [comment]
Thanks for the heads up. Definitely seems like an involved problem, but I'll take a look and let you know if I see anything.

**Comment by pjcozzi** [comment]
@ryanbartley thanks for investigating.  Also, let me when know when you are ready to show your glTF engine, and we will list it here: https://github.com/KhronosGroup/glTF#gltf-tools

**Comment by ryanbartley** [comment]
No problem. I've soft released the block [here](https://github.com/ryanbartley/gltf). I appreciate all the hard work and this definitely pushed Cinder. [Here's](http://discourse.libcinder.org/t/gltf-initial-release-wip/212) a write up on it. I'll have some time this week and weekend to look at the animation problem.

**Comment by pjcozzi** [comment]
Very cool, thanks for sharing your work and looking into the animation!  @chaoticbob mentioned Cinder's interest in glTF to me back at GDC.  Glad to see nice progress here!

**Comment by ryanbartley** [comment]
So, I'm starting to dig into this a bit more and just to learn what happens first, second, etc. I put out a bunch of debug that you can see [here](https://gist.github.com/ryanbartley/51b73b27f3013713c9a4423446ed4303#file-gistfile1-txt) of the above collada file. What you're seeing in the output is 6 different times a gltfanimationflattener is being created for the same object, and [here's](https://gist.github.com/ryanbartley/51b73b27f3013713c9a4423446ed4303#file-gltfanimationflattener) the changes to the source to get that debug. Note: some of the debug is coming from "writeAnimation" function. 

Now the debug output is clipped, as there was quite a bit, but what you can see there is that there are 6 flatteners being created for the same object. I think I understand why, because collada stores the data as separately for translation x, y, z, and rotation euler x, y, z. However, it produces [this](https://gist.github.com/ryanbartley/51b73b27f3013713c9a4423446ed4303#file-originalgltfanimationobject) gltf animation object output. TL;DR there are 60 animations for 10 animated objects and only 20 are actual valid animation (I broke out what it should basically be, [here](https://gist.github.com/ryanbartley/51b73b27f3013713c9a4423446ed4303#file-properflattenedobject)), which makes sense if it's creating an animation object per component animation from collada and doesn't delete them when flattening . So something is happening with the flattener, or somewhere up the chain, that isn't flattening these animations correctly.

I wanted to bring this to your attention, not because I think it's the problem above or in #551, but because as I'm getting to know the api I ran across it, and wanted to see if this is intended or something I could fix. Maybe, someone knows exactly what's happening, uninitialized bool or something.

**Comment by ryanbartley** [comment]
Also, as I read #551 deeper, it doesn't seem like the same exact problem as here, though I could definitely be wrong. It looks like the other problem is caused by incorrect hierarchy transformation and animation data targeting the wrong node. This problem looks more like it's due to incorrect flattening and timing of the actual animations, i.e. the translation and rotation are somehow not getting all the info at the correct time. The reason is that this is pretty much a flat scene, the only parent being the Y_UP_TRANSFORM. Also, this collada file was made in blender and opens in blender correctly, unlike the other problem being discussed. Finally, there doesn't seem to be any animation flattening problems in either the group_pivot_original.gltf and group_pivot_fixed.gltf. Anyway, just some observations.

**Comment by ryanbartley** [comment]
Alright, so I've narrowed down a few places that are problematic in terms of the animation conversion for collada2gltf. (please excuse my rambling)

First, as I said above, it looks like a GLTFAnimationFlattener is being made and written to for every animation component in collada, i.e. if an object has animation for translation and rotation in a 3d program and exports to collada it's represented as -> location-x, location-y, location-z, euler-x, euler-y, euler-z, all separated and when converted to glTF that becomes 6 animation objects with only two being valid (in other words, with animation data). 

Second, when i pull out the animation data for the valid animation objects from above, the translation vector (x,y,z) and/or the rotation quat(w,x,y,z) values aren't always the same as the above location-x, location-y, location-z, euler-x, euler-y, euler-z (for the eulers, this is of course after i translate them to quat's using glm). For instance, I made a quick collada with one moving cube and the values of translation from the collada file for each timestep were as follows...
``` 
<float_array id="Cube_location_X-output-array" count="4">0 4.824815 -8.336062 -3.354299</float_array>
<float_array id="Cube_location_Y-output-array" count="4">0 4.737415 -4.394554 5.722274</float_array>
<float_array id="Cube_location_Z-output-array" count="4">0 0 2.515288 2.515288</float_array>
0.041666601 = [    0.000,    0.000,    0.000]
0.541666985 = [    4.825,    4.737,    0.000]
1.083329916 = [   -8.336,   -4.395,    2.515]
1.666669965 = [   -3.354,    5.722,    2.515]
```
...which are correct. However, the rotation information...
```
<float_array id="Cube_rotation_euler_X-output-array" count="4">0 -76.64739 171.8662 -19.01184</float_array>
<float_array id="Cube_rotation_euler_Y-output-array" count="4">0 0.6319316 -58.83343 6.325599</float_array>
<float_array id="Cube_rotation_euler_Z-output-array" count="4">0 -46.86127 -43.06918 -11.13535</float_array>

// converting these to quaternions like so
auto quat1 = glm::quat( vec3( 0 ) );
auto quat2 = glm::quat( vec3( -76.64739, 0.6319316, -46.86127 ) );
auto quat3 = glm::quat( vec3( 171.8662, -58.83343, -43.06918 ) );
auto quat4 = glm::quat( vec3( -19.01184, 6.325599, -11.13535 ) );

// gives me this output
quat1: [    1.000,    0.000,    0.000,    0.000]
quat2: [   -0.281,   -0.177,   -0.584,    0.741]
quat3: [    0.193,   -0.512,    0.199,   -0.813]
quat4: [    0.751,   -0.075,   -0.037,    0.655]

// whereas, the converted .gltf file has the animation values as
0.041666601 = [    1.000,    0.000,    0.000,    0.000]
0.541666985 = [    0.721,   -0.567,    0.251,   -0.309]
1.083329916 = [    0.237,    0.795,   -0.351,    0.433]
1.666669965 = [   -0.981,    0.159,   -0.070,    0.086]
```
Another example can be found here with the translation keyframes of one of the cylinders in the original animation that opened this issue above...
```
// glTF translation animation values
 0.041666601 = [    0.302,   -0.060,    7.299]
1.125000000 = [    0.302,   -0.060,    7.267]
1.166669965 = [    0.302,   -0.060,    7.231]
1.208329916 = [    0.302,   -0.060,    7.185]
1.250000000 = [    0.302,   -0.060,    7.095]
1.291669965 = [    0.302,   -0.060,    7.022]
1.333329916 = [    0.302,   -0.060,    6.892]
1.375000119 = [    0.302,   -0.060,    6.792]
1.416669965 = [    0.302,   -0.060,    6.621]
1.458329916 = [    0.302,   -0.060,    6.494]
// original collada translation animation values
<float_array id="Cylinder_location_X-output-array" count="75">0.02090656 0.02090656 0.04546189 0.1332108 0.2170181 0.2293071 0.2542362 0.2707944 0.2945037 
<float_array id="Cylinder_location_Y-output-array" count="75">0.2276139 0.2276139 0.2336291 0.2441797 0.2339596 0.2081746 0.1658177 0.1552007 0.141029 
<float_array id="Cylinder_location_Z-output-array" count="100">7.307505 7.299331 7.266666 7.231307 7.185101 7.095483 7.02222 6.892087 6.79186 6.62135 
```
...full values can be found [here](https://gist.github.com/ryanbartley/51b73b27f3013713c9a4423446ed4303#file-numbersoutputforanimation).

Finally, what should/does Collada2glTF do if the animation isn't LINEAR, i.e. BEZIER? The only way to make a BEZIER into LINEAR is to produce intermediate keyframes. Should collada2glTF do that? Does it do that? I haven't been able to find it. And is it possible to think about adding new Animation curves to the spec?

**Comment by lasalvavida** [comment]
I'll try to answer these as best I can. Also I don't know why I didn't think to share this before. I have a branch that should work (mostly) for your coin drop: https://github.com/lasalvavida/glTF/tree/fix-animations. 

Only LINEAR is supported at this time. It would be nice to support BEZIER too.

I definitely remember having problems with animationConverter and the flatteners. In that branch, I took them out completely. 

The crux of the problem is that COLLADA will target multiple animations onto a single node. Currently, those get flattened out and you have the problem outlined in #551. My branch gets around this in a hacky way by creating more keyframes so that the transformation gets flattened out and applied at steps in between the start and end of the animation which makes it look more correct.

The work there may be helpful for adding support for BEZIER to LINEAR.

The correct way to handle this would be to create a new node for each transform step targeted by an animation.

The reason this ends up being difficult to do is that COLLADA2GLTF resolves animations based on their node targets. You would have to modify the OpenCOLLADA data structures during the conversion which is probably possible, but I had spent too long working on this already and needed to move on to other issues.

Hope that helps.

**Comment by lasalvavida** [comment]
This is your collada converted on that branch. (Providing I didn't forget to check anything in) [coins.zip](https://github.com/KhronosGroup/glTF/files/416167/coins.zip)

**Comment by ryanbartley** [comment]
Hey @lasalvavida, thanks for this work. I've checked and the motion does look correct. A few things that I noticed. 1) I still see the same amount of empty animation objects in the .gltf that you posted and the original .gltf. 2) I'm wondering why there needs to be so many additional keyframes. It looks like almost 1 per millisecond or almost 42x more keyframes. I understand if the motion needs to be corrected that additional are needed but it seems that that's a lot more. 3) definitely seems like that could help with bringing in different interpolations and baking them to linear. I'll take a look at your branch further to see if I can help out.

**Comment by lasalvavida** [comment]
I did kind of explain this above, but I'll try to make it a little clearer.

The approach in that branch is not the correct one. Inserting all of those keyframes dramatically bloats the model size which is why it was never merged.

In COLLADA, a node can have multiple transforms applied to it. COLLADA2GLTF creates a glTF node for each COLLADA node. Then the node transform is calculated from the flattened set of COLLADA transforms for that node. If the node is animated, it is stored as TRS, if not, a Matrix4. Then a glTF animation is created for each COLLADA animation and they target whatever glTF node was made from their COLLADA node target. 

The reason that this doesn't work all of the time is that COLLADA animations don't actually target nodes like glTF animations. They target the transform elements inside of the node. So using your model as an example we have a node like this:

```xml
<node id="Cylinder" name="Cylinder" type="NODE">
   <translate sid="location">0.302243 -0.05967787 0.8770488</translate>
   <rotate sid="rotationZ">0 0 1 -15.218</rotate>
   <rotate sid="rotationY">0 1 0 -17.89046</rotate>
    <rotate sid="rotationX">1 0 0 21.44238</rotate>
    <scale sid="scale">1 0.9999999 0.2</scale>
    <instance_geometry url="#Cylinder-mesh" name="Cylinder"/>
</node>
```

So, in COLLADA when we animate, the values of intermediate transforms can be targeted and changed. I can change for example the angle of `rotationY` and the transform is calculated by going through `location`->`rotationZ`->`rotationY`->`rotationX`->`scale`. 

We flatten those steps out on the nodes in glTF. If I have an animation targeting `rotationY`, that doesn't mean the same thing because the transform pipeline from COLLADA doesn't really exist anymore.

My branch flattens out the transform at each animation keyframe using the COLLADA transform pipeline to correct this. However this alone also has problems. For example, the animation may only have two keyframes, the start and end like in #551. In that example, the box is supposed to rotate about a center position. What will happen instead is that the box will rotate, but it will translate linearly from its start location to the end location instead of following a circular path.

No problem, right? We can just add a keyframe in the middle. Except now, the box will translate linearly to the edge of the circle then linearly up to its end position. You have to add many keyframes to make the linear animation approximate a circular one.

What needs to be done instead is that each COLLADA animation step needs to be separated out as its own node. Using the example from before: `location`->`rotationZ`->`rotationY`->`rotationX`->`scale`. Let's say that only `rotationY` is animated. The node hierarchy should be:

`node_0.transform` -> `location` * `rotationZ`
-> `node_1.transform` -> `rotationY`
-> -> `Cylinder.transform` -> `rotationX` * `scale`

In this way, we duplicate the functionality of the COLLADA animation pipeline by not mapping the COLLADA structure 1-to-1 with the glTF structure and needing to generate an absurd number of keyframes for smooth animation.

**Comment by ryanbartley** [comment]
Ahhh, that makes total sense. Sorry I wasn't totally getting it. Thank you so much for the explanation.

**Comment by lasalvavida** [comment]
No problem, happy to help!

**Comment by lasalvavida** [comment]
@ryanbartley Feel free to take a look at #684 if you get a chance. Should fix this.

**Comment by ryanbartley** [comment]
Wow, that was fast. I'll def check it out as soon as possible.

**Comment by ryanbartley** [comment]
Hey @lasalvavida, sorry it took me so long to check this out. It definitely fixed the problem! I appreciate it.

**Comment by ryanbartley** [comment]
Also @lasalvavida, is there a specific fail case where this fix becomes absolutely necessary? In other words, is it that anytime there's rotation animations along the x, y, z eulers, they always have to be separated out into the node structure? It seems like many of the original glTF samples in the repo have rotations that don't seem broken. Just wondering if there's a way to watch out for it.

**Comment by lasalvavida** [comment]
> Is there a spec on how added nodes will be addressed and named?

That ends up being more of a specific implementation detail than a something we would state in the spec. COLLADA2GLTF is really just designed to output valid glTF from COLLADA, but it doesn't make guarantees about node names, etc.

>Is there a specific fail case where this fix becomes absolutely necessary?

This can only happen when a single COLLADA node has multiple transforms targeted for animation. In that subset of cases, this fix is necessary if your transform pipeline contains anything besides a trivial set of translation, rotation, and scale transforms.

**Comment by lasalvavida** [comment]
#684 has been merged, so this can be closed

**Comment by ryanbartley** [comment]
Thanks so much for your help!
