### ISSUE TITLE
Required top-level object properties

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#639]
For example, just asset metadata and geometry objects so a valid glTF asset doesn't need to include materials and friends.

@lexaknyazev would you be able to open a PR into the `1.0.1` branch with a proposal?

**Comment by lexaknyazev** [comment]
> would you be able to open a PR into the `1.0.1` branch with a proposal?

As soon as we agree on specifics:

- `asset` dictionary is required (this implies existence of `asset.version`).
- `meshes` dictionary is required and must not be empty.
- `mesh.primitives` array is required and must not be empty. (Btw, what's the point in empty array here?)
- `[mesh.]primitive.attributes` dictionary is required. (Again, why isn't it already?) This implies requirements for non-empty `accessors`, `bufferViews` and `buffers` dictionaries.
- `[mesh.]primitive.material` is not required.

Not sure about `nodes`.

@pjcozzi What do you think?

---

Is there any valid use case for explicit `null` anywhere in glTF?

**Comment by pjcozzi** [comment]
All looks good.  As for the previously optional properties, I think we were just being too aggressive with defaults.

I am tempted to require `nodes`, but there have been requests to use glTF for purely geometry, e.g., in one global coordinate system.

> Is there any valid use case for explicit null anywhere in glTF?

What do you mean?  Do you have an example?

**Comment by lexaknyazev** [comment]
>> Is there any valid use case for explicit `null` anywhere in glTF?

> What do you mean? Do you have an example?

JSON values can be `null` (instead of `undefined`). It could be used as a placeholder for app-specific usage or as a stub for required fields. For example, `buffer.uri` for `KHR_binary_glTF` could be like this:

```js
{
  "buffers": {
    "binary_glTF": {
      "byteLength": 12345,
      "uri": null // instead of "data:,"
    }
}
```

**Comment by lexaknyazev** [comment]
At the current state of spec, default material is defined as a material without `technique` (or `extensions`).
Should `primitive` without `material` property be rendered with default material or should it be excluded from rendering? 

Since default material doesn't have any `values`, I propose to refine that part like this:

- `primitive` with no `material` renders with default material (here's one more possible use case for `null`: use `"material": null` to disable object rendering).

- `material` can't have `values` if `material.technique` is undefined.

**Comment by pjcozzi** [comment]
> Is there any valid use case for explicit null anywhere in glTF?

Ah, I see what you mean (https://github.com/KhronosGroup/glTF/issues/639#issuecomment-231074266).  I guess a property could be `null`, and the default value applies if the property is missing, `undefined`, or `null`?  Or the default value only applies if the property is missing.

> Since default material doesn't have any values, I propose to refine that part like this:

> * primitive with no material renders with default material (here's one more possible use case for null: use "material": null to disable object rendering).

> * material can't have values if material.technique is undefined.

All OK with me.

**Comment by lexaknyazev** [comment]
If a property is missing, it is `undefined`. `null` is explicit, so it should be used carefully.

**Comment by pjcozzi** [comment]
@lexaknyazev OK to close this?  Or is there anything else to discuss about `null`.

**Comment by lexaknyazev** [comment]
If there's nothing else for mandatory asset data, let's close this and discuss `null` in a separate issue.

**Comment by lexaknyazev** [comment]
See #646 for `null`.

**Comment by thokra1** [comment]
I know this issue is closed, but I am befuddled that there is no rationale stated here. For our company we decided to adopt glTF 1.0 exactly for the reason that nothing was mandatory by default. This way, we are able to specify materials and all the transitively mandatory assets as we needed while the meshes are currently stored in a custom binary format and loaded by other means (i.e. not by a glTF loader). While we want to transition to glTF for all assets at some point, we cannot make this transition right now. 

I'm totally fine with metadata being mandatory but what is the rational behind forcing the inclusion of at a non-empty dictionary of buffers and transitive dependencies?

Is there another, more appropriate place to discuss this?

**Comment by pjcozzi** [comment]
I think it is a valid use case to use glTF for just materials, so I would be fine with loosening the 2.0 spec so that `nodes` is optional (which implicitly makes `meshes`, `accessors`, etc. optional).  The asset just would not be rendered when loaded as a glTF alone, but could be used when combined with another payload, which is increasingly common.

Also see https://github.com/KhronosGroup/glTF/issues/815#issuecomment-274287933

> Perhaps if scenes is not defined, nothing is rendered; this is only used when glTF is packaged with another format, e.g., a game engine format might reference glTF nodes directly.

**Comment by thokra1** [comment]
@pjcozzi: thank you!
