### ISSUE TITLE
TEXCOORD ambiguity

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#645]
Spec says:
> Valid attribute semantic property names include `POSITION`, `NORMAL`, `TEXCOORD`, `COLOR`, `JOINT`, and `WEIGHT`. `TEXCOORD` and `COLOR` attribute semantic property names can be of the form `[semantic]_[set_index]`, e.g., `TEXCOORD_0`, `TEXCOORD_1`, `COLOR_1`, etc.

Such language means that that both `TEXCOORD` and `TEXCOORD_0` are allowed. However, all examples use `TEXCOORD_0`. This may be OK for custom shaders but can complicate implementations of material extensions.

Same about `COLOR`.

**Comment by pjcozzi** [comment]
> Such language means that that both TEXCOORD and TEXCOORD_0 are allowed.

I think it is fine to allow only `TEXCOORD_0` (and `COLOR_0`).  I don't think this will break existing users in practice, and it treats texture coordinates and colors consistency as arrays, instead of allowing them to be scalars when the array size is 1.

If you agree, please open a PR for the 1.0.1 spec.
