### ISSUE TITLE
COLLADA2GLTF does not enforce top-level skeleton node must be top-level glTF node

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#648]
See `RiggedSimple.gltf` and https://github.com/KhronosGroup/glTF/issues/624#issuecomment-231539452.

**Comment by lasalvavida** [comment]
@lexaknyazev Is there a compelling reason to force a top level skeleton node to be a top level node?

If not, it may be better to remove what seems like an arbitrary restriction to me.

**Comment by lexaknyazev** [comment]
Here's example layout:
- `node_4`
 -  `Armature`
   - `Bone`
     - `Bone_001`
    - `Bone2`
      - `Bone2_001`
 - `Cylinder`

Skinned node (`Cylinder`) references `Bone` as its skeleton:

```json
"Cylinder": {
  "meshes": [
    "Cylinder-mesh"
  ],
  "skeletons": [
    "Bone"
  ],
  "skin": "Armature_Cylinder-skin"
},
```

Since we've decided to forbid mixing skeleton nodes with non-skeleton nodes in one tree, we need to move `Armature` out of `node4`:

- `node_4`
 - `Cylinder`
-  `Armature`
    - `Bone`
      - `Bone_001`
    - `Bone2`
      - `Bone2_001`

@pjcozzi [said](https://github.com/KhronosGroup/glTF/issues/624#issuecomment-232782426), that `jointName` has skeleton-tree scope. So how many skeleton-tree scopes are here:
- Two: (`Bone` + its children) and (`Bone2` + its children), __or__
- One: (`Armature` + its children)?

With actual skeletons being top-level, we could also avoid extra parent transformations: `Armature` matrix could be pre-applied to `Bone` and `Bone2`.

**Comment by lexaknyazev** [comment]
@pjcozzi Could you confirm this restriction or should it be reconsidered?

**Comment by lasalvavida** [comment]
If this is something we want to do, I can pretty easily throw something into gltf-pipeline in the short term to correct the sampleModels. However, a collada2gltf fix is going to be a lot more involved.

**Comment by pjcozzi** [comment]
I am open to reconsidering this if it makes exporters/converters complicated.  I don't like the idea of putting workarounds in gltf-pipeline ("output an invalid glTF then let gltf-pipeline fix it" is not the foundation we want to build on).

@lexaknyazev what does this improve for loaders?  Is it significant?  Perhaps the tradeoff isn't worth keeping it.

**Comment by lexaknyazev** [comment]
See my [comment](https://github.com/KhronosGroup/glTF/issues/648#issuecomment-237976364) above. It's about defining local scope for `jointName`.

**Comment by pjcozzi** [comment]
Ah, OK.

@lasalvavida what is hard about updating COLLADA2GLTF?

One non-ideal solution could be to:
* Update the sample model by hand
* Have a COLLADA2GLTF issue and mark it as a known limitation, https://github.com/KhronosGroup/glTF/wiki/converter-limitations, perhaps with a workaround of how to update the source COLLADA model before conversion if possible.

**Comment by lasalvavida** [comment]
> @lasalvavida what is hard about updating COLLADA2GLTF?

I'll see what I can do with COLLADA2GLTF. It just isn't super consistent with its memory management, so adding post-processing stages usually involves digging through SEGFAULTS.

**Comment by lexaknyazev** [comment]
Continuation:
https://github.com/KhronosGroup/COLLADA2GLTF/issues/16
