### ISSUE TITLE
Compatibility of CESIUM_RTC and materials extensions

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#658]
If a `material` doesn't have any `technique` because of materials extension use, where should parameter with `"CESIUM_RTC_MODELVIEW"` semantic be located?

**Comment by pjcozzi** [comment]
We haven't ran into this in practice, but we could, especially since Cesium supports both extensions.  I feel like the solution will be when the materials extension is used to allow the material/technique to still list parameters to be merged with it.  That could be messy though.

Perhaps table this until we have more cycles or there is community feedback to prioritize it, e.g., because it becomes a more broad problem with extension compatibility.

**Comment by lexaknyazev** [comment]
The issue is bigger than just `CESIUM_RTC`, since any extension could define new parameter semantics and therefore be incompatible with materials extensions. Something to think of for future cycles.

**Comment by lexaknyazev** [comment]
@pjcozzi Any updates on `CESIUM_RTC` with glTF 2.0?

**Comment by emackey** [comment]
Seems like this is OBE.
