### ISSUE TITLE
technique.parameter.value polymorphism

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#664]
Not sure if it was discussed before, but why `technique.parameter.value` isn't always defined as an array?

One have to check `parameter.type` and `parameter.count` combination before touching `parameter.value`. It makes runtime more complicated in that part, imho. Same comment about `material.values`.

Btw, values of `technique.states.functions` are arrays even when they contain only one element.

**Comment by lexaknyazev** [comment]
`parameter.value` can be defined only for uniform parameters, so allowed `parameter.type`s are: `BYTE`, `UNSIGNED_BYTE`, `SHORT`, `UNSIGNED_SHORT`, `INT`, `UNSIGNED_INT`, `FLOAT`, `FLOAT_VEC2`, `FLOAT_VEC3`, `FLOAT_VEC4`, `INT_VEC2`, `INT_VEC3`, `INT_VEC4`, `BOOL`, `BOOL_VEC2`, `BOOL_VEC3`, `BOOL_VEC4`, `FLOAT_MAT2`, `FLOAT_MAT3`, `FLOAT_MAT4`, and `SAMPLER_2D`. 

More than half of them already require `parameter.value` to be an array. Moreover, if `parameter.count` is defined `parameter.value` must be an array too.

I also think that allowing both following setups may be a source of possible runtime errors:
```json
{
  "param1": {
    "type": 5126,
    "count": 1,
    "value": [0.42]
  },
  "param2": {
    "type": 5126,
    "value": 0.42
  }
}
```
Proposal is to require `value` always to be an array, and make `count` default to `1`.

**Comment by lexaknyazev** [comment]
Also, current approach can cause unwanted type weakening for non-JS runtimes: e.g., [JglTF](https://github.com/javagl/JglTF/blob/master/jgltf-impl/src/main/java/de/javagl/jgltf/impl/TechniqueParameters.java#L55).
Moreover, __tinygltfloader__ [uses](https://github.com/syoyo/tinygltfloader/blob/master/tiny_gltf_loader.h#L145) array for numbers already.

CC @pjcozzi @lasalvavida @javagl @syoyo

**Comment by lasalvavida** [comment]
I agree with this. We already require accessor mins and maxes to be arrays even if they only have a single component and this seems consistent with that decision.

**Comment by javagl** [comment]
The type weakening in the linked source code is hardly an issue. Even if it was always an array, it could only be an array (i.e. `List` of `Object`). Beyond that: Take the jgltf-impl with a grain of salt. It's auto-generated from the schema, and this auto-generation may have its own issues. 

What's more relevant in this sense is the interpretation of this `Object` or `List<Object>`. In my [current implementation](https://github.com/javagl/JglTF/blob/master/jgltf-model/src/main/java/de/javagl/jgltf/model/GltfModels.java#L92), the case of having `count>1` is not handled yet. But as the comment suggests, my interpretation of the *meaning* of `count>1` would have been different. 

I'll try to state this as two questions:

1), just to be sure: The issue is **not** related to something like a parameter that consists of **two** `FLOAT_VEC3` elements? This will still be 

    "param1": {
      "type": FLOAT_VEC3, 
      "count": 2,
      "value": [ [1.23, 2.34, 3.45],  [ 4.56, 5.67, 7.89 ] ] 
    },

i.e. an array of arrays, correct?

2), More importantly: If you have a shader with two uniforms,

    uniform vec3 exampleA[1];
    uniform vec3 exampleB;

are you sure that it will never be necessary to differentiate between the types of these two, as in 

    "exampleA": {
      "type": FLOAT_VEC3, 
      "count":1,
      "value": [[1.23, 2.34, 3.45]]  
    },
    "exampleB": {
      "type": FLOAT_VEC3, 
      "value": [1.23, 2.34, 3.45] 
    },

?


(I'd have to think about this again, but thought that might at least be related to https://github.com/KhronosGroup/glTF/pull/614 ...)

**Comment by lexaknyazev** [comment]
1. According to [the current spec] (https://github.com/KhronosGroup/glTF/tree/master/specification#parametercount) and JSON schemas array is flat.

 > When defined, `value` is an array with length equal to `count`, times the number of components in the type, e.g., `3` for `FLOAT_VEC3`.

2. According to [OpenGL ES 2.0.25](https://www.khronos.org/registry/gles/specs/2.0/es_full_spec_2.0.25.pdf) (p. 35) you can refer to the first element of the uniform array by using just the uniform name (without `[0]`).

**Comment by javagl** [comment]
1. Sorry, I should have looked at the `gltf_detailedDescription` (which was updated related to #614 )
2. Sorry again, I was not sure about possible implications of the proposed change (maybe also regarding layout qualifiers etc - I'm still learning the details...)

**Comment by lexaknyazev** [comment]
Just to elaborate a bit more on uniform arrays. 
- If shader has `uniform float u_b[1];`, `parameter.count` must be `1` and `value` must be an array of 1 element (no changes here).
- If shader like `uniform flloat u_b;`, `parameter.count` must be `1` and `value` must be an array of 1 element, instead of just scalar value.

These examples are almost the same for GL, because it's possible to use `glGetUniformLocation(program, "u_b")` and `glUniform1fv(location, 1, value);` in both cases.

Moreover, GL man pages for `glUniform{1234}{if}v` clearly state:
> `count`: <...> This should be 1 if the targeted uniform variable is not an array, and 1 or more if it is an array.

The only implementation caveat that I see here: if runtime chooses to use `glUniform{1234}{if}` (with explicit arguments instead of array reference, since the former is faster in WebGL), it mustn't use `glGetUniformLocation(program, "u_b[1]")`, because it will fail in the second case.

**Comment by pjcozzi** [comment]
@lexaknyazev just to confirm my understanding here, you are suggesting that when `value` is an array of length `1`, treat it as a scalar (well, not an array); otherwise, treat it as an array...so basically, there will never be an array of length 1.

I see where you are coming from, but are you sure this more easily maps to the WebGL API?  Although it simplifies the glTF schema a tad, it seems like it is harder to map to WebGL API, which has explicit support for non-array uniforms that are widely used.

**Comment by lexaknyazev** [comment]
My point here is that having `value` as array maps to API more consistently;

```json
{
  "p0": {
    "type": 5126,
    "value": 0.42
  },
  "p1": {
    "type": 5126,
    "count": 1,
    "value": [0.42]
  },
  "p2": {
    "type": 35664,
    "count": 1,
    "value": [0.42, 0.56]
  },
 "p3": {
    "type": 35665,
    "count": 1,
    "value": [0.42, 0.56, 0.71]
  }  
}
```

Compare:
```js
// to use p0:
gl.uniform1fv(location, [p0.value]); // OR
gl.uniform1f(location, p0.value);

// to use p1:
gl.uniform1fv(location, p1.value); // OR
gl.uniform1f(location, p1.value[0]);

// to use p2:
gl.uniform2fv(location, p2.value); // OR
gl.uniform2f(location, p2.value[0], p2.value[1]);

// to use p3:
gl.uniform3fv(location, p3.value); // OR
gl.uniform3f(location, p3.value[0], p3.value[1], p3.value[2]);

```

**Comment by pjcozzi** [comment]
So always use the `v` version of `uniform*` unless you want to optimize for the special case of `length === 1`, right?

**Comment by lexaknyazev** [comment]
Someone may also choose to optimize for all sizes and always use non-`v` functions.
Either way, having `value` as an array makes all `uniform*` calls aligned.

**Comment by pjcozzi** [comment]
OK, +1 from me, let's do it.

**Comment by lexaknyazev** [comment]
I'll prepare PR soon.

**Comment by pjcozzi** [comment]
Updated in #826
