### ISSUE TITLE
Trailing zeros storage

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#749]
Should glTF require presence of accessor's trailing zeros? E.g.:

**two points, ubyte attribute, stride of 4:**

```
vertexAttribPointer(index, 1, UNSIGNED_BYTE, false, 4, *pointer);

Data layout:
|00|01|02|03|04|05|06|07|
|-----------------------|
|xx|00|00|00|xx|00|00|00|
```

Must bytes 5-7 be stored in glTF buffer or not?

CC @pjcozzi @mre4ce

**Comment by pjcozzi** [comment]
I suppose it is not required (but could be there) as long as the data is true to the `bufferView` offset and length.  Does GL require this for the last attribute?

**Comment by lexaknyazev** [comment]
> Does GL require this for the last attribute?

Looks like it doesn't. So valid `bufferView.byteLength` for a given accessor is a range, not a single value:
```c
int byteStride = accessor.byteStride == 0 ? COMPONENTS * COMPONENT_TYPE_LENGTH : byteStride;

int minLength = byteStride * (accessor.count - 1) + COMPONENTS * COMPONENT_TYPE_LENGTH;
int maxLength = byteStride * accessor.count;
```
Or should we limit only minimal length?

**Comment by pjcozzi** [comment]
What is the right approach to keep the client as simple as possible, just say that:
```
byteLength  === byteStride * accessor.count
```

**Comment by lexaknyazev** [comment]
If a client just passes values to the GL, it should be unaffected by either approach.
_Maybe_, tooling ecosystem will benefit a little from fixed byteLength.

**Comment by pjcozzi** [comment]
> If a client just passes values to the GL, it should be unaffected by either approach.

Yes, but what if, for example, the client is doing mesh decompression.

Perhaps this fixed approach keeps things simple without loosing any useful use cases.

**Comment by lexaknyazev** [comment]
OK, let's be more precise there.

**Comment by pjcozzi** [comment]
Please open a PR into `1.0.1`

**Comment by lexaknyazev** [comment]
__two verts, vec3 position + vec3 normal interleaved and aligned, float attribute, stride of 32 (2 x 4 x 4):__
```json
{
  "accessors": {
    "accessor_pos": {
      "byteOffset": 0,
      "byteStride": 32,
      "componentType": 5126,
      "count": 2,
      "type": "VEC3"
    },
    "accessor_nor": {
      "byteOffset": 16,
      "byteStride": 32,
      "componentType": 5126,
      "count": 2,
      "type": "VEC3",
    }
  }
}
```

```
vertexAttribPointer(index_pos, 3, GL_FLOAT, false, 32, 0);
vertexAttribPointer(index_nor, 3, GL_FLOAT, false, 32, 16);

Data layout:
|00|01|02|03|04|05|06|07|08|09|0A|0B|0C|0D|0E|0F|10|11|12|13|14|15|16|17|18|19|1A|1B|1C|1D|1E|1F|
|-----------------------------------------------------------------------------------------------|
|px|px|px|px|py|py|py|py|pz|pz|pz|pz|00|00|00|00|nx|nx|nx|nx|ny|ny|ny|ny|nz|nz|nz|nz|00|00|00|00|

|20|21|22|23|24|25|26|27|28|29|2A|2B|2C|2D|2E|2F|30|31|32|33|34|35|36|37|38|39|3A|3B|3C|3D|3E|3F|
|-----------------------------------------------------------------------------------------------|
|px|px|px|px|py|py|py|py|pz|pz|pz|pz|00|00|00|00|nx|nx|nx|nx|ny|ny|ny|ny|nz|nz|nz|nz|00|00|00|00|
```

To satisfy `accessor.byteLength === byteStride * accessor.count` for `accessor_nor`, we need to add 16 more zero bytes. Does it look good to you?

**Comment by pjcozzi** [comment]
Why wouldn't we use stride=24 for both and offset=12?  Or is this example just highlighting that the content pipeline may generate padding to conform to the spec, which is also OK since the padding doesn't appear to be significant in typical cases, e.g., lots of vertices.

**Comment by lexaknyazev** [comment]
My example wasn't accurate, I meant a case, with 4-byte aligning, but actually, question is about attribute interleaving:

__two verts, vec3 position + vec3 normal interleaved and aligned, short attribute, stride of 16 (2 x 2 x 4):__
```json
{
  "accessors": {
    "accessor_pos": {
      "byteOffset": 0,
      "byteStride": 16,
      "componentType": 5123,
      "count": 2,
      "type": "VEC3"
    },
    "accessor_nor": {
      "byteOffset": 8,
      "byteStride": 16,
      "componentType": 5123,
      "count": 2,
      "type": "VEC3",
    }
  }
}
```

```
Data layout:
|00|01|02|03|04|05|06|07|08|09|0A|0B|0C|0D|0E|0F|10|11|12|13|14|15|16|17|18|19|1A|1B|1C|1D|1E|1F|
|-----------------------------------------------------------------------------------------------|
|px|px|py|py|pz|pz|00|00|nx|nx|ny|ny|nz|nz|00|00|px|px|py|py|pz|pz|00|00|nx|nx|ny|ny|nz|nz|00|00|
|10|11|12|13|14|15|16|17|
|-----------------------|
|00|00|00|00|00|00|00|00|

```

Are we OK with all those zeros?

**Comment by pjcozzi** [comment]
You are asking about the trailing zeros, right?  I think it is OK.

The zeros in each attribute are required, of course, so each vertex is 4-byte aligned.

**Comment by lexaknyazev** [comment]
@pjcozzi please review #758.

@mre4ce Is this change OK with you?

**Comment by javagl** [comment]
I just tried to match this issue and the changes in the pull request with what I had written in the tutorial referring to the image at https://github.com/javagl/glTF-Tutorials/blob/a9921eab0ff15cd540436ede69e25ef3d8b8e2b8/gltfTutorial/gltfTutorial_005_BuffersBufferViewsAccessors.md#data-layout . 

I'll have to re-read the spec changes a few times (the ASCII-images and the (large) numbers in the text are somewhat hard to match). But **if** I understood this correctly, then 
- it would be neceessary to add 12 zero bytes (for 3*`float` components) at the end of the `bufferView` 
- **only** to make sure that after the start of normal (n1x, n1y, n1z), (which starts at byte 36), there are 24 bytes available (which are somehow "required in order to satisfy" the `byteStride` of 24 of the normals accessor)

**If** this is the intention, then this looks a bit odd at the first glance. The `acesssor` does not "store" any data - it is only a parameter object for `glVertexAttribPointer`. (Nitpickingly, one could say that there is no such thing like "accessor data" - although we all know what we mean here). However, I'll have to think about the consequences that this constraint has, and ... maybe I just misinterpreted something here.

**Comment by lexaknyazev** [comment]
I don't like those 12 zero bytes too. Maybe, we could come up with more nice solution to tighten data layout?

CC @pjcozzi

**Comment by javagl** [comment]
Sorry, I'm probably overlooking something here - the more you know, the more subtle questions arise. What confuses me here is that some comments seemed to mention an `accessor.byteLength`, but this does not exist.The valid **`bufferView`**`.byteLength` is a different story. From the comments, it seems like one key point was the question:

Given the `accessor` objects that refer to one `bufferView`: Under which condition is a `bufferView.byteLength` **valid**?

(with "valid" being related to the validator?)

I think that, informally, one could say: The `bufferView.byteLength` has to be *at least* large enough so that all elements of all `accessor` objects refer to a valid part of this `bufferView`. 

As an example (similar to the image that I linked to), consider an `accessor` with

    count : 2
    byteOffset: 4
    byteStride: 8
    type/componentType : SCALAR/float (4 bytes)

This could refer to the `X` bytes of this `bufferView`:

    0123456789ABCDEF
    ....XXXX....XXXX

I don't see why the `byteStride` of 8 should imply that there are 4 additional padding bytes at the end. 

Who would ever have a reason or justification to assume that these bytes existed (or even to actually *access* these bytes)?

**Comment by lexaknyazev** [comment]
Obsolete with #802.
