### ISSUE TITLE
Update reference card for glTF 2.0

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#761]
@javagl are you up for this?

1.0 -> 2.0 changes are here: #605

**Comment by javagl** [comment]
Sure! I've been watching the linked issue and the upcoming changes. Many of them are very "low-level" and not explicitly covered in the overview, but I still have to sort out how they will affect the overview. I did not integrate them as long as they were being discussed. Do you think that now is the right time to create a "1.1-beta" version of the overview?

---

I still hesitate to call it a "reference card". It's supposed to be rather "educational" and give a basic understanding of the concepts. Creating a true reference card (with more specification details, tables containing valid enum values etc.) should probably be considered as well.

**Comment by pjcozzi** [comment]
> Do you think that now is the right time to create a "1.1-beta" version of the overview?

Yes, I think 1.1 is very close.  CC @lexaknyazev 

> I still hesitate to call it a "reference card". It's supposed to be rather "educational" and give a basic understanding of the concepts...

We can position it however you would "overview", "introduction", etc.

**Comment by lexaknyazev** [comment]
@javagl 
> Do you think that now is the right time to create a "1.1-beta" version of the overview?

Everything except skinning should be in its final state.

**Comment by pjcozzi** [comment]
@javagl would you be able to update the reference card now that the 1.1 spec pull request is open, #784?

**Comment by javagl** [comment]
The changes that are relevant for the 1.1 update should be included now via https://github.com/javagl/gltfOverview/commit/df8bfc4a4fe8197347d9603e7ae250e7580f5cad and https://github.com/javagl/gltfOverview/commit/11a2faad3a681bf8d6aa13ff4c551ef1a3e3f204 : 

- Removed "parameters" indirection from animation
- Added a few words about interpolation, including "STEP"
- Added "extensionsRequired" property
- Added accessor.min/max
- Technique and material parameter values must be arrays
- In KHR_binary_glTF changed "scene" to "content"
- Updated version number to 1.1.0

If there are no objections or further changes that I overlooked, I'd try to create a "release" (PNG/PDF as 1,2 and 4 pages) tomorrow.

--- 

Many of the changes in the spec refer to "technical details" that are not explicitly covered in the overview. In https://github.com/javagl/gltfOverview/issues/2 I mentioned a few points that could be added in the overview *beyond* the pure spec changes, possibly involving a larger extension or restructuring. If there are ideas for that, or how the overview could be improved in general, I'm open for a disucssion.

**Comment by javagl** [comment]
The new release is at https://github.com/javagl/gltfOverview/releases/tag/v1.1.0 

Suggestions for future updates can be added in https://github.com/javagl/gltfOverview/issues/2 or in separate issues.

**Comment by pjcozzi** [comment]
Very nice @javagl!  Can you please open a PR into #784 (branch: `lexaknyazev:master-test`) to update the reference card in the README.md and perhaps add the corresponding reference card to the README.md in the 1.0 and 1.1 directories so users have the older versions if needed?

**Comment by javagl** [comment]
The first PR is open. 

By
> add the corresponding reference card to the README.md in the 1.0 and 1.1 directories  

do you mean just as links, or should the images really be inlined like in the main README? (If so: maybe after the https://github.com/javagl/glTF/tree/master-test/specification/1.0#introduction section?)

**Comment by lexaknyazev** [comment]
@javagl 
Could you please remove `buffer.type` from overview  (#786)?
Also, skinning part will likely change, (https://github.com/KhronosGroup/glTF/issues/723#issuecomment-254674004) so we shouldn't call current state of the reference card "release".

---

@pjcozzi 
It was my mistake to open PR from my fork instead of creating new branch in KhronosGroup repo. Should I fix that to keep all glTF discussions and PRs nearby?

**Comment by javagl** [comment]
The current state already "is" a "release", but I should probably have waited with that until the end of the PR. 

However, I will...

- remove the `buffer.type` (assuming that this is agreed upon now. I was a bit suprised, because the `type` was optional and did not harm, but it's probably a trade-off, and "keeping things lean and clean" may justify this backward-incompatible change)
- re-read the issues about the skinning (I did not have all of them on the radar, but since skinning is one of the more complex topics and has many subtleties, I'll definitely worth to have another look at this) and update the overview once this has settled
- Release this as version 1.1.0**b**
- Update this PR (or create a new one into Khronos repo, if appropriate)

**Comment by pjcozzi** [comment]
> @pjcozzi
It was my mistake to open PR from my fork instead of creating new branch in KhronosGroup repo. Should I fix that to keep all glTF discussions and PRs nearby?

Whatever is easiest for you, @lexaknyazev.  I don't think it will make a big different from a history perspective.

**Comment by pjcozzi** [comment]
> do you mean just as links, or should the images really be inlined like in the main README? (If so: maybe after the https://github.com/javagl/glTF/tree/master-test/specification/1.0#introduction section?)

Whatever you think, perhaps an image is best just after the intro as you suggest.

**Comment by donmccurdy** [comment]
Reference card is up to date: https://github.com/KhronosGroup/glTF/#overview
