### ISSUE TITLE
how to make gltf model geographically located?

### ISSUE THREAD

**Issue by iWun** [KhronosGroup/glTF#781]
Hello,
  I have a gltf model and I know its location (longitude,latitude,height).How should I write the location information into the model to make it geographically located?
  I have tried this way:
     `var origin = Cesium.Cartesian3.fromDegrees(110.211930717672, 28.2190616557563, 161.6954);`
     ` var modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(origin);`
  Then I put the modelMatrix into the gltf's root nodes.
  This works,but when I convert the gltf into the glb,the textures of model are in chaos.
  Anybody can help me? Thanks.
`
`

**Comment by javagl** [comment]
Converting the model into binary glTF (`.glb`) should not change anything about how the model is rendered. Can you provide more information, and maybe an example of such a model in `.gltf` and `.glb` format?

**Comment by iWun** [comment]
Thanks for replying. I  have upload a [model](https://github.com/iWun/model/blob/master/model.zip) .gltf and .glb format to my github.You can download it.Thanks again.

**Comment by iWun** [comment]
By the way,I converted the model by [gltf-pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline),and then loaded into [Cesiumjs](https://cesiumjs.org/)

**Comment by javagl** [comment]
I probably won't be able to resolve this (I'm not yet familiar with gltf-pipeline), but some preliminary results and guesses that might help the Cesium folks to point you in the right direction:

The resulting translation is **huge**. The translation part of the matrix is

        -1943202.650449179,
        5278078.365236855,
        2997994.9297714364,

(In any case, you may hit some limits of single-precision floating point values with this translation. Depending on the renderer, this may result in different artifacts (although likely *not* in Cesium))

The reason of why you are experiencing problems (only) with the `glb` file is probably (!) that the translation is "baked" into the geometry data:

![largetranslation](https://cloud.githubusercontent.com/assets/5597569/20649813/ce1eddc6-b4c7-11e6-9416-de6e4cb42a4d.png)

(I think this is happening in https://github.com/AnalyticalGraphicsInc/gltf-pipeline/blob/fd7011bf7eb1956889328785e6b55a37878251d7/lib/PrimitiveHelpers.js#L66 , but this is just a guess from quickly skimming over the code).

There seems to be no "obvious" command line parameter, but maybe there's another way to disable this.

**Comment by iWun** [comment]
Thanks anyway.
Which software you use to open the model?
Can you recommend other tools that convert gltf to glb like gltf-pipeline?
Thanks.

**Comment by javagl** [comment]
We should probably wait until it is officially confirmed that the problem *is* due to the baked transforms.

But when comparing the model that you provided

![modelglb](https://cloud.githubusercontent.com/assets/5597569/20667275/b703f940-b568-11e6-9242-4dbdfc584aa9.png)

with one that was created *without* baking the translation into the geometry data

![modeljgltfglb](https://cloud.githubusercontent.com/assets/5597569/20667335/051fe85a-b569-11e6-8481-3f50405f4b05.png)

then one can see that it is not really the textures, but indeed the geometry data that is broken there...

---

The software is the [jgltf-browser](https://github.com/javagl/JglTF/tree/master/jgltf-browser). It this is still under construction, and there have been some changes and updated recently that are **not** yet available in the releases (particularly, a fix for a bug that I only discovered when I converted your model to glb!). But for the case that you want to have a look at the converted model without the baked transforms, I have uploaded it at http://javagl.de/modelJgltf.glb

**Comment by iWun** [comment]
You’ve been so helpful.Thank you very much.

**Comment by pjcozzi** [comment]
@iWun OK to close this?  In the future, if you have Cesium questions, please post them on the Cesium forum, http://cesiumjs.org/forum.html

**Comment by iWun** [comment]
@pjcozzi OK.
