### ISSUE TITLE
how to calculate  the  normal and the count of  position?

### ISSUE THREAD

**Issue by yanliasdf789** [KhronosGroup/glTF#795]
I try  to read the example file of "Box.glb", I get the position count is 24, the normal count is 24.
I doubt that   a box with 8 vertex , why  is 24 in the file?
i know that   the indics number is 36= the number of triangle* 3  =12*3
i don't know how to calculate the  normal  either.

**Comment by javagl** [comment]
The reason of why there are 24 normals is that there are 6 faces, and each face has 4 corners, and *each corner (!) needs its own normal*. You have to imagine each face like it was rendered "separately" from the others, to make sure that the lighting really considers it as a flat surface. Have a look at the following image (which is just one quick result of searching for `box with smoothed vertex normals`) :

http://wiki.polycount.com/w/images/e/e5/FrostSoft_doc-3.png

In the left image, you see the 24 small, orange arrows that indicate the vertex normals. 

And when there are 6*4 = 24 normals, then there also have to be 24 positions (even though there are only 8 *distinct* vertex positions), because the `count` of all attributes for one mesh primitive must be equal. (This is because models are "single indexed" for efficient rendering with OpenGL, but this might lead to far right now). 

In order to compute a vertex normal, you also need information about the *face* (i.e. the triangle) to which this vertex belongs, because one vertex may belong to different faces, and for each face, it needs a special normal. 

One common approach is thus to compute the face normals, as in this pseudocode

    edge1 = face.vertex1.position - face.vertex0.position;
    edge2 = face.vertex2.position - face.vertex0.position;
    normal = normalize(crossProduct(edge1, edge2));

and apply this normal to all vertices of the face, **but**, as explained above, this will cause "flat shading". If you want to achieve smooth shading, you'll have to compute the sum of all normals of all faces that belong to one vertex (possibly weighted by the *area* of the faces - there are several different approaches out there!), then normalize this summed normal, and assign it as the normal to the vertex (this is basically what you see in the middle of the image linked above). 

The https://github.com/AnalyticalGraphicsInc/gltf-pipeline/ offers some options for normal handling, you might want to have a look at that.

**Comment by pjcozzi** [comment]
I don't think there are any more actions here.
