### ISSUE TITLE
state parameters should be an array instead of a list of named parameters

### ISSUE THREAD

**Issue by RemiArnaud** [KhronosGroup/glTF#85]
for example:
```
                    "states": {
                        "blendEnable": false,
                        "depthMask": true,
                        "depthTestEnable": true
                    },
```

the spec needs the entire list to be defined so the application know what to expect

**Comment by pjcozzi** [comment]
Useful comment from #85 (duplicate): https://github.com/KhronosGroup/glTF/issues/249#issuecomment-42711173

**Comment by pjcozzi** [comment]
@tparisi here is content on render states for the draft 1.0 spec:

---

Render states define the fixed-function GL state when a `primitive` is rendered.  Each `primitive` refers to a `material`, which refers to a `technique`, which has a `pass`, which has a `state` dictionary object defining the fixed-function GL state that should be applied.  `states` contains two properties:

* `enable`: an array of integers corresponding to boolean GL states that should be enabled using GL's `enable` function.
* `functions`: a dictionary object containing properties corresponding to the names of GL state functions to call.  Each property is an array, where the elements correspond to the arguments to the GL function.

Valid values for elements in the `enable` array are: `3042` (`BLEND`), `2884` (`CULL_FACE`), `2929` (`DEPTH_TEST`), `32823` (`POLYGON_OFFSET_FILL`), `32926` (`SAMPLE_ALPHA_TO_COVERAGE`), and `3089` (`SCISSOR_TEST`).  If any of these values are not in the array, the GL state should be disabled (which is the GL default state).  If the `enable` array is not defined in the `pass`, all of these boolean GL states are disabled.

Each property in `functions` indicates a GL function to call and the arguments to provide.  Valid property names are: `"blendColor"`, `"blendEquationSeparate"`, `"blendFuncSeparate"`, `"colorMask"`, `"cullFace"`, `"depthFunc"`, `"depthMask"`, `"depthRange"`, `"frontFace"`, `"lineWidth"`, `"polygonOffset"`, and `"scissor"`.  If a property is not defined, the GL state for that function should be set to the default value(s) shown in the example below.

The following example `states` object indicates to enable all boolean states (see the `enable` array) and use the default values for all the GL state functions (which could be omitted).  Enum strings, instead of integers, are shown for clarity (_@tparisi if you don't like this, perhaps do, for example, `3042 /* BLEND */`, which isn't valid JSON, but is fine for an example_).
```javascript
"states" : {
    "enable" : [BLEND, CULL_FACE, DEPTH_TEST, POLYGON_OFFSET_FILL, SAMPLE_ALPHA_TO_COVERAGE, SCISSOR_TEST], // empty by default
    "functions" : {
      "blendColor": [0.0, 0.0, 0.0, 0.0], // (red, green, blue, alpha)
      "blendEquationSeparate" : [FUNC_ADD, FUNC_ADD], // (rgb, alpha)
      "blendFuncSeparate" : [ONE, ONE, ZERO, ZERO], // (srcRGB, srcAlpha, dstRGB, dstAlpha)
      "colorMask" : [true, true, true, true], // (red, green, blue, alpha)
      "cullFace" : [BACK],
      "depthFunc" : [LESS],
      "depthMask" : [true],
      "depthRange" : [0.0, 1.0], // (zNear, zFar)
      "frontFace" : [CCW],
      "lineWidth" : [1.0],
      "polygonOffset" : [0.0, 0.0], // (factor, units)
      "scissor" : [0, 0, 0, 0], // (x, y, width, height)
    }
}
```

The following example shows a typical `"states"` object for closed opaque geometry.  Culling and the depth test are enabled, and all other GL states are their default value.
```javascript
"states": {
    "enable": [
        2884,
        2929
    ]
}
```

**Implementation Note**: It is recommended that a runtime use the minimal number of GL state function calls.  This generally means ordering draw calls by technique, and then only making GL state function calls for the states that vary between techniques.

---

Of course, this will also need a table that containing the schema details: https://github.com/KhronosGroup/glTF/blob/spec-1.0/specification/schema/examples/techniques.json
