### ISSUE TITLE
depthClear missing from state spec

### ISSUE THREAD

**Issue by RemiArnaud** [KhronosGroup/glTF#88]
```
 "depthClear" : {
            "type" : "number",
            "description" : "depthClear()",
            "default" : 1.0,
            "minimum" : 0.0,
            "maximum" : 1.0,
        },
```

**Comment by pjcozzi** [comment]
CC #163

**Comment by pjcozzi** [comment]
`states` is now part of [KHR_technique_webgl](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_technique_webgl).  Before this spec is finished, we plan to discuss what `states` should be included since glTF does not have multipass.  It may be something like depth test, culling, and blending.  We are starting a new issue to discuss.
