### ISSUE TITLE
Should node matrices be restricted to affine?

### ISSUE THREAD

**Issue by sbtron** [KhronosGroup/glTF#892]
TRS transformations are all affine transformations but matrices could create non-affine transformation.
To simplify implementations should the spec restrict node matrices to affine?
Is anyone using matrices for non-affine transformations?

**Comment by pjcozzi** [comment]
No strong opinion, but I am OK with restricting to affine transforms.  We just just state how this makes implementations easier perhaps in a non-normative section of the spec.

**Comment by peteroupc** [comment]
Most 3D graphics implementations will support 4x4 matrices, not just 4x3 matrices.  A restriction to affine transformations seems rather artificial (an relevant example here is three.js's [recent change to `applyMatrix`](https://github.com/mrdoob/three.js/pull/10405/files) to support projective and not just affine matrices; for background, [see this issue](https://github.com/mrdoob/three.js/issues/6039)). Rather than a restriction to affine matrices, I would support allowing the `matrix` property to optionally contain 12 rather than 16 elements (treating the projective portion as `(0, 0, 0, 1)`, since most of the time, the matrix will be affine and not projective.

**Comment by fta2012** [comment]
Random technical point about definitions: TRS transformations are all affine transformations but not all affine transformations are TRS. So restricting to allowing arbitrary affine matrices won't simplify your implementations to just TRS (e.g., if somebody gives you a shear matrix, which is affine, there's no equivalent TRS decomposition).

There are 9 degrees of freedom (meaning 3 parameters each) in a 3D translate, rotate, and scale representation. But there are 12 degrees of freedom in an affine matrix (4x3). If you want to represent all affine transformations you will need to add more degrees of freedom to your decomposition (for example with shear as part of your decomposition).

In [CSS matrix3d](https://www.w3.org/TR/2012/WD-css3-transforms-20120911/#matrix-decomposing), they use the unmatrix algorithm from "Graphic Gems II" to decompose a 4x4 homogeneous matrix (15 parameters) into a perspective part (3 dof) and an affine part (4x3 12dof), then decomposes that affine into translate-rotate-shear-scale (3dof each). There are other decompositions though.

(sorry for random drive by comment, I know nothing about this project and only saw it from the link to my issue in another project)

**Comment by peteroupc** [comment]
@fta2012:

For context, see the draft version of the glTF 2.0 specification, in the "Transformations" section.
https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0#transformations

As you can see, in the draft, transformations are defined "either by supplying a `matrix`  property, or any of `translation`, `rotation`, and `scale` properties (also known as _TRS properties_)". In the draft, the `matrix` property is a 4x4 array of 16 elements (so can currently represent not just TRS transformations and not just affine transformations, but also projective transformations). If I understand the issue correctly, the issue is only about the `matrix` property (and not the TRS properties `translation`, `rotation`, or `scale`), and  @sbtron wants the glTF specification to "restrict node matrices", that is, the `matrix` property, "to affine", that is, if I understand correctly, the projective portion of the 4x4 array can only consist of `(0, 0, 0, 1)` and nothing else.  And as I explain in my previous comment, such a restriction "seems rather artificial".  explain in my previous comment, such a restriction "seems rather artificial".  (Moreover, your findings on the performance of `applyMatrix4` in the issue I linked to argue against making the change @sbtron suggests in this issue, in my opinion.)

**Comment by fta2012** [comment]
If I understand correctly, currently you can set a transform with TRS since it's more usable for humans but you also allow more general matrices if needed. What OP is trying to do is restrict the class of matrices to exactly that of TRS by only allowing affine (which is a mistake, see below).

This situation is similar in three.js. Their "source of truth" is a matrix although they expect the vast majority of their users to manipulate it by setting TRS properties. If you need a more general class of transforms you can choose to stop having the TRS decomposition updated (and lose the convenient api) but things keep working since under the hood everything is still in terms of matrices.

The point of my last comment was that you can even avoid three.js's api problem by choosing a more general decomposition (by adding a shear or a perspective to your decomposition):

4x4 Projection matrices: Perspective-Translate-Rotate-Shear-Scale
4x3 Affine matrices: Translate-Rotate-Shear-Scale
4x3 TRS matrices (tautology, no good description): Translate-Rotate-Scale

Then both representation are convertible to each other (outside a small number of degenerate matrices) and it won't matter whether you choose the matrix or the decomposition as your "source of truth" representation internally.

What I was objecting to is keeping Translate-Rotate-Scale but allowing 4x3 since there's no good reason for that.

Keeping Translate-Rotate-Scale and 4x4 isn't so bad either but then you should definitely choose the matrix as your canonical representation.

Anyway no more drive-by comments from me!

**Comment by bghgary** [comment]
Some popular engines (e.g. Unity and Unreal to a certain extent) only support TRS on node transforms. Assets with matrices that shear or skew will not import into these engines.

Core glTF should set the minimum bar for implementers. My opinion is that the single reason above is enough to restrict the matrix to not allow shear or skew.

Thoughts?

**Comment by peteroupc** [comment]
In my opinion, not just a restriction of the `matrix` property to affine matrices is artificial, but also a restriction to TRS transformations.  I would prefer changing the `matrix` property to indicate that implementations must support _at least_ TRS transformations in that property, not that the property is limited to such transformations.  This will avoid implementations having to decompose the `matrix` property to see if the property meets the TRS restriction, which is prone to numerical inaccuracy and can lead to undefined results if the matrix, for example, includes a skew and not just a rotation.

**Comment by pjcozzi** [comment]
Updated in #826
