### ISSUE TITLE
converter should propagate original IDs from COLLADA files

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/glTF#9]

**Comment by pjcozzi** [comment]
> need to fix for animations - dev-8.

Was this fixed?

**Comment by pjcozzi** [comment]
CC #235 (propagate names)

**Comment by pjcozzi** [comment]
@fabrobinet do you recall?

>> need to fix for animations - dev-8.

> Was this fixed?

**Comment by pjcozzi** [comment]
@tfili can you evaluate this when your looking at name propagation (#235)?

**Comment by tfili** [comment]
Just a quick look, the following look correct
COLLADA geometry -> glTF mesh
Lights
Cameras
Nodes
Materials
COLLADA controller -> glTF skin
Images

Looks like animations and scenes need to have the ID propagated before we can close this.

**Comment by pjcozzi** [comment]
How hard do you think it is?

**Comment by tfili** [comment]
@pjcozzi These are actually going to be pretty difficult. Animation handling is complicated because the converter flattens all animations for a node into a single animation, so preserving the ID doesn't make sense if there is more than one. If there is only one animation targeting a node, then it would make sense but the logic for the more complicated case makes it difficult.

As for scenes, OpenCOLLADA seems to be missing the `getOriginalID()` accessor, so that why it was never done. There is a comment in there for it
`//FIXME: should use this id -> visualScene->getOriginalId()`

**Comment by pjcozzi** [comment]
OK, let's push this post 1.0.  Can you create a new wiki page in this repo for COLLADA2GLTF limitations to document this?  Then we'll close this issue.

**Comment by tfili** [comment]
Created https://github.com/KhronosGroup/glTF/wiki/converter-limitations.
