### ISSUE TITLE
Light Semantics

### ISSUE THREAD

**Issue by tparisi** [KhronosGroup/glTF#93]
We need to have a general semantic scheme for lighting, similar to how we deal with matrices and other parameters that get passed to the shader.

**Comment by tparisi** [comment]
I'm not following... are we saying we would get rid of the light-specific parameters? I don't want to lose that info, it's useful for higher-level engines like Three.js where we can optionally use common techniques like Phong.

**Comment by fabrobinet** [comment]
We will keep all the parameters within techniques, but will remove lights objects in the node hierarchy because they are not really useful here as have to declared anyway also in the techniques to set the parameters and uniforms.

**Comment by tparisi** [comment]
If they're not in the node hierarchy, how can they be transformed and animated?

**Comment by fabrobinet** [comment]
Oops, sorry I didn't meant that :) 

The intention here is actually to remove the `lights` property at the root level of the JSON - but of course not node that hold the transform.
`lights` hold entries to describes values such as color of the lights, attenuation... but these parameters are eventually redundant in the technique.

**Comment by tparisi** [comment]
Ah ok, well that makes me feel better. However I don't quite understand what the resulting file would look like. Do you have a quick example? I don't need to see all the technique info, just where the light would be defined in the file, and how it would be referenced as a node. So, pseudo-glTF would suffice...

**Comment by fabrobinet** [comment]
Based the proposed changes in #361 we extend here the discussion to lights.

1. We can remove the `lights` properties at the root level of `glTF` as the ones who directly use the shaders provided by glTF  have all the paramaters/values for lights already set within the techniques. 

2. For the ones who do not want to use the shaders provided by `glTF` and re-create their owns,  light properties should be specified within the context of a specific extension as explained in #361 . 
Because glTF is not about specifying lightingModel and depending of input format this information could vary a lot, it is safer to handle through extensions.

As an example for 2 with the converter available on this repo, then we'd have an extension defined within `pass`  such as:
```json
"allExtensions" : "[COLLADA-1.4.1/commonProfile]",
"extensions": {
    "COLLADA-1.4.1/commonProfile": {
        "extras": {
            "doubleSided": false
        },
        "lightingModel": "Blinn",
        "parameters": {
            "ambient" : "ambient",
            "diffuse" : "diffuse",
            "emission" : "emission",
            "reflective" : "reflective",
            "shininess" : "shininess",
            "specular" : "specular",
            "transparency" : "opacity",
            "lights" : {
                "light1" : {
                    "color" : "light1Color",
                    "constantAttenuation": "light1ConstantAttenuation",
                    "linearAttenuation": "light1LinearAttenuation",
                    "quadraticAttenuation" : "light1QuadraticAttenuation"
                }
            }
        }
    },
    "texcoordBindings": {
        "ambient": "TEXCOORD_0",
        "diffuse": "TEXCOORD_0",
        "reflective": "TEXCOORD_0"
    }
},
```

- the biggest benefit is that glTF core won't be impacted in any way about concepts tied to lights.
- when using specific extensions to get information about the lighting model being used, this way is now consistent with other material properties. (as semantic such as "specular" and "constantAttenuation" point both to actual parameters within techniques)

**Comment by fabrobinet** [comment]
@tparisi @pjcozzi @RemiArnaud what do you think ?
Also I am completely sure here about the schema for the `extension` named `COLLADA-1.4.1/commonProfile` but we can refine it here https://github.com/KhronosGroup/glTF/issues/362

**Comment by pjcozzi** [comment]
All sounds good to me.  I am happy to update the schema when we determine the exact details for this extension.

**Comment by RemiArnaud** [comment]
I�m not sure what the question is.

If this is an extension to the �pass� object, then I would call this �extra� and then underneath have �profile� sections for each extensions
not sure what the �allExtensions' is for, or what 'COLLADA-1.4.1/commonProfile� is referring to exactly.

Regards
� Remi

**Comment by tparisi** [comment]
I'm sorry I object to this whole change. I personally thought the lights stuff was fine the way it is and now this is getting more COLLADA-like as the design evolves.

Why do we need extensions to handle something as basic as lights? 

In practice, a runtime wants to know about the lights, cameras and animations in a scene. Having them in a list at the top level is extremely helpful. For implementations that don't need that, they can just ignore the property.

What I have liked about glTF so far is that we have kept the design practical. Design choices like this move away from practical.

**Comment by fabrobinet** [comment]
> I'm sorry I object to this whole change. I personally thought the lights stuff was fine the way it is and now this is getting more COLLADA-like as the design evolves.

This is actually quite the opposite - LightingModel specification in `COLLADA` was mostly inherited from the OpenGL fixed pipeline and removing all references about lights has been the trend since OpenGL ES 2.0. So this move would bring glTF in a closer place to modern GL APis than COLLADA.

> Why do we need extensions to handle something as basic as lights?

If you use the provided shaders (as Cesium) developers write based on glTF a completly data-driven engine and do not need to know about high levels such as lights to actually perform a rendering that contains lighting. 

For the ones who want to re-create shaders (as you do), I find it risky to commit on specifying in lights as depending on tools where lighting modeling may vary and we could be very soon limited with only the traditional 4 types of lights (ambient, omni, directional, spot). One could write a glTF exporter right in a tool (3DSMAX...) and export other types of lights that we aren't aware of, and the place to describe such light should be in a specific extension.

> In practice, a runtime wants to know about the lights, cameras and animations in a scene. Having them in a list at the top level is extremely helpful. For implementations that don't need that, they can just ignore the property.

I got your point but addressing this could be easy.
We can an add also extension property at the root level of the JSON and instead of directly parsing the `lights` property you'd have the go through the extension first.

> What I have liked about glTF so far is that we have kept the design practical. Design choices like this move away from practical.

Again I get your argument, but it's the exact same debate as if you were going to OpenGL WG and were asking to put back the fixed pipeline because it was practical...

**Comment by tparisi** [comment]
@fabrobinet @pjcozzi Guys I am coming around to this way of thinking. HOWEVER can we consider changing the naming from "extensions"? This doesn't feel like an *extension* to me-- extensions are for significant added capability-- and I think the naming will confuse people. It sounds a lot more like a technique or profile or something. In fact, "profiles" seems like a pretty good name for this one. Let's leave "extensions" for true extensions. What do you think?

Secondary naming thing: I think we should not have COLLADA in this name but rather call it something like "Materials-FixedFunction" because this is a generally useful set of information whether or not it is implemented in COLLADA. For my applications I don't care about COLLADA, I just want to make sure I can get the fixed function material and lighting information for simple applications such as viewers or previewing tools.

**Comment by fabrobinet** [comment]
@tparisi profile is already taken by asset/profile (https://github.com/KhronosGroup/glTF/blob/master/specification/asset.schema.json) but I get your concern about `extension` that may not be the most natural naming for this and we can think of another name. It's related to the tool/exporter who generated the `glTF` file...   I don't have anything that sounds right on the top of my head right now for this. We'll see if we circle back on `pass/profile`...

Then yes, we can revise how we will actually name the extension. We can discuss that in https://github.com/KhronosGroup/glTF/issues/362

**Comment by tparisi** [comment]
It's a plan. 

FWIW I think "profiles" is still OK, it's in a different context.

"extras?"

I will meditate on it, maybe I can think of something?

**Comment by pjcozzi** [comment]
All sounds good to me.

**Comment by pjcozzi** [comment]
We can close this when we finish materials in #84.

**Comment by pjcozzi** [comment]
@tparisi can you quickly review this and close as duplicate with #424 if you agree?

**Comment by tparisi** [comment]
Closing, moved to common materials extension. Duplicate of #424
