### ISSUE TITLE
Refine node animation computation

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#982]
When only one or two node transforms are targeted by animation, what must the value of untouched transform(s) be: default or node-defined?

E.g., let's say that a node has all three properties set with non-default values: `rotation`, `translation`, `scale`.
Also let's say that animation targets only `rotation`. In that case, should values of `translation` and `scale` be changed to default before applying keyframe data or not?

I'm asking this, because COLLADA2GLTF writes all three channels even when keyframe values equal JSON-defined node transforms (see `RiggedSimple`).

CC @pjcozzi @bghgary @lasalvavida @javagl

**Comment by javagl** [comment]
> In that case, should values of translation and scale be changed to default before applying keyframe data or not?

If I understood this correctly, doing an (translation) animation of an object that should be scaled by a factor of (2,2,2) throughout the animation would then require to define an *explicit* animation channel target for the scaling, for all the keyframes, which all have the (constant) value (2,2,2). This doesn't seem to make sense for me.

If someone sets a scaling of (2,2,2) which is not animated, then there does not seem to be a reason to overwrite it. (Principle of least astonishment: Assume someone creates a model, and later adds an animation, and then wonders why his scaling is gone, although he didn't do anything that should affect the scaling). 

Is there any reason or (non-obvious) application case where overwriting the properties with default values would make sense?

**Comment by lexaknyazev** [comment]
> ...would then require to define an explicit animation channel target for the scaling, for all the keyframes, which all have the (constant) value (2,2,2). This doesn't seem to make sense for me.

That's what COLLADA2GLTF outputs (3 explicit channels, 2 of them have constant values).

> Is there any reason or (non-obvious) application case where overwriting the properties with default values would make sense?

I can't imagine any reasonable case for this.

**Comment by javagl** [comment]
I haven't looked into the files and code yet, but when you say ...

> That's what COLLADA2GLTF outputs (3 explicit channels, 2 of them have constant values).

then I assume that this is *not* already contained in the COLLADA input file. (If it was, there would hardly be any alternatives, except for something like `if (allValuesAreEqualIn(someColladaData)) doNotWriteThemToGltf();` ...)

**Comment by lasalvavida** [comment]
Just for the record, this usually only happens if the COLLADA animates a matrix transform. We decompose it into translation, rotation, and scale channels and write them. However, in many COLLADA models with matrix transforms, only a single component is actually being varied. If the COLLADA animates a strictly translation or rotation transform, then only that channel will have an animation written. Optimizing out decomposed animation values that are the same as the node transform is an optimization I can add, but the reason this happens at all is due to poor authoring of COLLADA assets.

And yes, I agree that if a channel is not animated, it should default to the node transform for that component.

**Comment by lexaknyazev** [comment]
See #983 for proposed clarification.
