### ISSUE TITLE
Why do we need glTF?

### ISSUE THREAD

**Issue by computersarecool** [KhronosGroup/glTF#986]
Hi,
I have watched a and read a bit about glTF and I am just curious why exactly we need this format.
I hear that it is trying to be the ".jpeg of the web". For images there are obviously many more standardized file formats than .jpeg, and similarly there are many file formats for 3D as well.

Mainly I do not see too much functionality here that is not in .FBX and .DAE (Collada) files.  I get that .FBX is not open-sourced, (which alone is reason enough not to use it) but does glTF offer anything that Collada does not (other than smaller file sizes)?

**Comment by pjcozzi** [comment]
Hi @computersarecool.  The main difference between COLLADA and glTF is that COLLADA is designed for exchange between modeling tools, and glTF is designed for efficient runtime use.

Before glTF, a typical workflow would be to use something like COLLADA or FBX for content creation, and then convert to an optimized proprietary format for use in an engine.  The problem being that each engine designed their **own** format and then had to write their **own** content pipeline!  Creating a standard like glTF allows the community to create an ecosystem of software that everyone can use and helps with robustness as the community collaborates on this ecosystem.

For a bit more background, check out the short story on how I got interested in glTF, http://blog.virtualglobebook.com/2013/03/how-i-got-involved-in-gltf-and-khronos.html

**Comment by kyasbal-1994** [comment]
@computersarecool
I was asked same thing by a my friend. 
I think I need to describe a change of 3D era. Basically 3D data was a middle data format to generate movies or images by using DCC software or game engines.
Therefore the most of 3D data formats are like .psd file in 2D image or .xls format in spreadsheets file. We often use jpg or PDF files to upload to show another person.
COLLADA is more like .odt in spreadsheet file. These are specificated in public but mainly designed for editing.

Recently end users can use 3D models only for seeing the models because new technologies such as VR or WebGL is reachable by them. This is why we need glTF.

@pjcozzi is one of the respected contributor around glTF. His answer might be what glTF will be. But I hope my examples help you to think this era definitely needs a 3D format like glTF.

**Comment by computersarecool** [comment]
Thanks both for the clarification. I am excited that there seems to be a good community around this file format too which is great to see.

**Comment by pjcozzi** [comment]
@computersarecool indeed, there is a really amazing community around glTF, welcome!
