### ISSUE TITLE
Must supplied normal map vectors be normalized?

### ISSUE THREAD

**Issue by stevenvergenz** [KhronosGroup/glTF#993]
It took far too long to figure out what to expect from supplied normal maps in glTF. In the Properties Reference, it looks like this:

> material.normalTexture
> 
> A tangent space normal map. The texture contains RGB components in linear space. Each texel represents the XYZ components of a normal vector in tangent space. Red [0 to 255] maps to X [-1 to 1]. Green [0 to 255] maps to Y [-1 to 1]. Blue [128 to 255] maps to Z [1/255 to 1]. The normal vectors use OpenGL conventions where +X is right and +Y is up. +Z points toward the viewer.

But nowhere in that description does it say that the resulting vector must (or may not) be of length 1. The closest I could find was this formula in the description of normalTextureInfo.scale, where the computation explicitly calls `normalize`:

> scaledNormal = normalize((normalize(\<sampled normal texture value\>) * 2.0 - 1.0) * vec3(\<normal scale\>, \<normal scale\>, 1.0))

The sample models (the Corset and the FarmLand Diorama) are *not* normalized, which forces GPUs to spend time correcting it. I think it would be preferable to require supplied normal maps to be normalized, but in either case this should be discussed.

**Comment by lexaknyazev** [comment]
> ... which forces GPUs to spend time correcting it

Pre-normalized normal vectros will be not of length 1 after texture sampling, so explicit `normalize` seems to be unavoidable.

CC @bghgary

**Comment by stevenvergenz** [comment]
@lexaknyazev that's true, but I'd expect filtering/mipmapping to produce no more than a fraction of a percent difference from a length-1 vector due to 8-bit channel quantification, which I expect would have a marginal effect on the final lighting calculation. The normal maps provided by the sample models mentioned have a uniformly fully-saturated blue channel, regardless of the R/G components. I wasn't expecting that, so others might not either. That's why I propose adding some clarification on the topic to the spec. Perhaps this is less a spec issue than a sample model issue, but it never hurts to state the obvious in a specification.

A representative pixel from the Corset sample model normal map:
![image](https://cloud.githubusercontent.com/assets/1882376/26748717/18192e7e-47b5-11e7-8a29-e313d2e47fe3.png)

**Comment by andreasplesch** [comment]
I think the expectation of normalized normals also applies to the NORMAL attribute of mesh primitives ?
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#meshes
I came across this issue when an existing shader was reused for glTF support and found that some glTF samples had non unit vector vertex normals, seemingly due to exporter convenience (?).

If non unit vector normals are deemed acceptable/conforming, there needs to be guidance on if the non unit length of a supplied normal needs to be respected/interpreted by a viewer or if it should be ignored by normalizing. A non unit length could be intentional to have the effect of a specular factor.

Since I cannot think of a less contrived example, I think currently the implicit assumption is that the supplied normals should be normalized for the intended shading. If this is the case, there needs to be an explicit statement or, alternatively and preferably, a requirement for the supplied normals to be already normalized. Viewers could still be free to accommodate non unit length normals by normalizing but would not be required to do so.

[This line of argument assumes that the spec. is concerned with how a glTF is intended to be rendered. If it does not then the discussion above may also be out of scope.]

**Comment by bghgary** [comment]
> some glTF samples had non unit vector vertex normals, seemingly due to exporter convenience

Can you point us to samples that have this issue?

> currently the implicit assumption is that the supplied normals should be normalized

I believe this is true. I can't think of any good reason why vertex normals should be normalized since they are required to be FLOATs.

> explicit statement or, alternatively and preferably, a requirement for the supplied normals to be already normalized

+1

**Comment by andreasplesch** [comment]
This caused me to dive deeper after I double checked the sample normals and found them to be unit vectors without fail. I was misled since a normalize() in the shader had fixed an issue. Closer inspection revealed that it was the view space normal which needed to be normalized, a step which was previously missed for some reason when reusing the existing shader for glTF.
While the samples are ok, it should still be made explicit that vertex normals are expected to be provided as unit vectors by viewers.

**Comment by pjcozzi** [comment]
@stevenvergenz thanks for bring this topic up.

The working group discussed this offline.

Engines will always have to normalize after sampling.  For storage, the normals are not required to be normalized.

We will add an implementation note to the spec.

@bghgary volunteered to update this.

**Comment by pjcozzi** [comment]
> @bghgary volunteered to update this.

Gentle reminder @bghgary. :)
